/**
 * @file board_config.h
 * @brief Chip BSP mapping for HPM5E31
 */

#ifndef BSP_CHIP_BOARD_CONFIG_H
#define BSP_CHIP_BOARD_CONFIG_H

#include "hpm_soc.h"
#include "board.h"

#ifdef __cplusplus
extern "C" {
#endif

#define BSP_CHIP_HPM5E31

/*
 * Single-source BSP resource lists:
 * Add/remove resources by editing only these list macros.
 * Interface enums and HPM port mapping tables are generated from them.
 */
#define BSP_GPIO_LIST(X) \
    X(BSP_GPIO_LED, HPM_GPIO0, GPIO_DI_GPIOA, 3U) \
    X(BSP_GPIO_LED2, HPM_GPIO0, GPIO_DI_GPIOA, 28U) \
    X(BSP_GPIO_LED3, HPM_GPIO0, GPIO_DI_GPIOA, 20U) \
    X(BSP_GPIO_LED4, HPM_GPIO0, GPIO_DI_GPIOA, 19U) \
    X(BSP_GPIO_KEY, HPM_GPIO0, GPIO_DI_GPIOF, 19U) \
    X(BSP_GPIO_LCD_CS, HPM_GPIO0, GPIO_DI_GPIOC, 11U) \
    X(BSP_GPIO_LCD_DC, HPM_GPIO0, GPIO_DI_GPIOB, 26U) \
    X(BSP_GPIO_LCD_RST, HPM_GPIO0, GPIO_DI_GPIOB, 27U) \
    X(BSP_GPIO_LCD_BL, HPM_GPIO0, GPIO_DI_GPIOC, 16U)

#define BSP_PWM_LIST(X) \
    X(BSP_PWM_MAIN, BSP_PWM_BACKEND_HPM_PWMV2, HPM_PWM0, IRQn_PWM0, clock_pwm0, 0U, 1U, \
      BSP_PWM_FEATURE_EDGE_ALIGNED | BSP_PWM_FEATURE_CENTER_ALIGNED | BSP_PWM_FEATURE_COMPLEMENTARY | BSP_PWM_FEATURE_DEADTIME | BSP_PWM_FEATURE_TRIGGER_COMPARE) \
    X(BSP_PWM_TIMER, BSP_PWM_BACKEND_HPM_GPTMR, HPM_GPTMR1, IRQn_GPTMR1, clock_gptmr1, 1U, 1U, \
      BSP_PWM_FEATURE_EDGE_ALIGNED)

#define BSP_UART_LIST(X) \
    X(BSP_UART_DEBUG, HPM_UART0, IRQn_UART0, \
      BSP_UART_FEATURE_BLOCKING_TX | BSP_UART_FEATURE_INTERRUPT_RX | BSP_UART_FEATURE_DMA_TX | \
      BSP_UART_FEATURE_DMA_RX | BSP_UART_FEATURE_RX_IDLE | BSP_UART_FEATURE_CONFIGURABLE_BAUD | \
      BSP_UART_FEATURE_PARITY_NONE | BSP_UART_FEATURE_PARITY_ODD | BSP_UART_FEATURE_PARITY_EVEN | \
      BSP_UART_FEATURE_PARITY_FORCED | BSP_UART_FEATURE_STOP_1 | BSP_UART_FEATURE_STOP_1_5 | \
      BSP_UART_FEATURE_STOP_2 | BSP_UART_FEATURE_WORD_7 | BSP_UART_FEATURE_WORD_8) \
    X(BSP_UART_APP, HPM_UART3, IRQn_UART3, \
      BSP_UART_FEATURE_BLOCKING_TX | BSP_UART_FEATURE_INTERRUPT_RX | BSP_UART_FEATURE_DMA_TX | \
      BSP_UART_FEATURE_DMA_RX | BSP_UART_FEATURE_RX_IDLE | BSP_UART_FEATURE_CONFIGURABLE_BAUD | \
      BSP_UART_FEATURE_PARITY_NONE | BSP_UART_FEATURE_PARITY_ODD | BSP_UART_FEATURE_PARITY_EVEN | \
      BSP_UART_FEATURE_PARITY_FORCED | BSP_UART_FEATURE_STOP_1 | BSP_UART_FEATURE_STOP_1_5 | \
      BSP_UART_FEATURE_STOP_2 | BSP_UART_FEATURE_WORD_7 | BSP_UART_FEATURE_WORD_8)

#define BSP_ADC16_LIST(X) \
    X(BSP_ADC16_MAIN, HPM_ADC0, IRQn_ADC0, clock_adc0, 1U, 1U, 1U, \
      BSP_ADC16_FEATURE_ONESHOT | BSP_ADC16_FEATURE_BLOCKING_READ | BSP_ADC16_FEATURE_INTERRUPT_READ | \
      BSP_ADC16_FEATURE_PERIOD | BSP_ADC16_FEATURE_SEQUENCE | BSP_ADC16_FEATURE_SEQUENCE_HARDWARE_TRIGGER | \
      BSP_ADC16_FEATURE_PREEMPTION | BSP_ADC16_FEATURE_PREEMPTION_HARDWARE_TRIGGER | \
      BSP_ADC16_FEATURE_CONFIGURABLE_RESOLUTION | BSP_ADC16_FEATURE_CONFIGURABLE_CLOCK_DIVIDER | \
      BSP_ADC16_FEATURE_GET_CLOCK | BSP_ADC16_FEATURE_TRIGGER_ROUTE | \
      BSP_ADC16_FEATURE_SEQUENCE_DMA | BSP_ADC16_FEATURE_CONTINUOUS_DMA)

#define BSP_GPTMR_LIST(X) \
    X(BSP_GPTMR_TIMER, HPM_GPTMR3, 1U, IRQn_GPTMR3, clock_gptmr3, BSP_GPTMR_FEATURE_PERIODIC | BSP_GPTMR_FEATURE_ONESHOT, 1U) \
    X(BSP_GPTMR_CAPTURE, HPM_GPTMR2, 0U, IRQn_GPTMR2, clock_gptmr2, BSP_GPTMR_FEATURE_CAPTURE, 1U) \
    X(BSP_GPTMR_COMPARE, HPM_GPTMR3, 0U, IRQn_GPTMR3, clock_gptmr3, BSP_GPTMR_FEATURE_COMPARE, 1U)

#define BSP_TRGM_LIST(X) \
    X(BSP_TRGM_MAIN, HPM_TRGM0)

#define BSP_PWMV2_LIST(X) \
    X(BSP_PWMV2_MAIN, HPM_PWM0, IRQn_PWM0, clock_pwm0, 1U)

#define BSP_SPI_LIST(X) \
    X(BSP_SPI_MAIN, HPM_SPI1, IRQn_SPI1, clock_spi1, 1U, \
      BSP_SPI_FEATURE_MASTER | BSP_SPI_FEATURE_BLOCKING | BSP_SPI_FEATURE_INTERRUPT | \
      BSP_SPI_FEATURE_DMA_TX | BSP_SPI_FEATURE_DMA_RX | BSP_SPI_FEATURE_FULL_DUPLEX | \
      BSP_SPI_FEATURE_TX_ONLY | BSP_SPI_FEATURE_RX_ONLY | BSP_SPI_FEATURE_CONFIGURABLE_CLOCK | \
      BSP_SPI_FEATURE_MSB_FIRST | BSP_SPI_FEATURE_LSB_FIRST)

#define BSP_I2C_LIST(X) \
    X(BSP_I2C_MAIN, HPM_I2C3, IRQn_I2C3, clock_i2c3, 1U, \
      BSP_I2C_FEATURE_MASTER | BSP_I2C_FEATURE_BLOCKING | BSP_I2C_FEATURE_INTERRUPT | \
      BSP_I2C_FEATURE_DMA | BSP_I2C_FEATURE_TEN_BIT_ADDRESS | BSP_I2C_FEATURE_CONFIGURABLE_CLOCK)

#define BSP_MCAN_LIST(X) \
    X(BSP_MCAN_MAIN, HPM_MCAN2, IRQn_MCAN2, clock_can2, 1U, \
      BSP_MCAN_FEATURE_CLASSIC | BSP_MCAN_FEATURE_CAN_FD | BSP_MCAN_FEATURE_BITRATE_SWITCH | \
      BSP_MCAN_FEATURE_INTERNAL_LOOPBACK | BSP_MCAN_FEATURE_TX_BLOCKING | BSP_MCAN_FEATURE_TX_FIFO | \
      BSP_MCAN_FEATURE_TX_BUFFER | BSP_MCAN_FEATURE_RX_FIFO0 | BSP_MCAN_FEATURE_RX_FIFO1 | \
      BSP_MCAN_FEATURE_RX_BUFFER | BSP_MCAN_FEATURE_STANDARD_ID | BSP_MCAN_FEATURE_EXTENDED_ID | \
      BSP_MCAN_FEATURE_REMOTE_FRAME | BSP_MCAN_FEATURE_FILTERS | BSP_MCAN_FEATURE_GLOBAL_FILTER | \
      BSP_MCAN_FEATURE_TX_EVENT_FIFO | BSP_MCAN_FEATURE_PROTOCOL_STATUS | BSP_MCAN_FEATURE_ERROR_COUNT | \
      BSP_MCAN_FEATURE_TIMESTAMP | BSP_MCAN_FEATURE_CANCEL_TX | BSP_MCAN_FEATURE_AUTO_BITRATE | \
      BSP_MCAN_FEATURE_RX_CALLBACK | BSP_MCAN_FEATURE_TX_CALLBACK | BSP_MCAN_FEATURE_EVENT_CALLBACK)

#define BSP_QEIV2_LIST(X) \
    X(BSP_QEIV2_MAIN, HPM_QEI1, IRQn_QEI1, clock_qei1, BOARD_BLDC_QEI_FOC_PHASE_COUNT_PER_REV, 1U)

#define BSP_CRC_LIST(X) \
    X(BSP_CRC_MAIN, HPM_CRC, clock_crc0, BSP_CRC_FEATURE_CRC32)

#define BSP_TSNS_LIST(X) \
    X(BSP_TSNS_MAIN, HPM_TSNS, clock_tsns)

#define BSP_EWDG_LIST(X) \
    X(BSP_EWDG_MAIN, HPM_EWDG0, clock_watchdog0, BSP_EWDG_FEATURE_INIT | BSP_EWDG_FEATURE_REFRESH | BSP_EWDG_FEATURE_DEINIT)

#define BSP_RNG_LIST(X) \
    X(BSP_RNG_NONE, 0U, 0U)

#define BSP_RTC_LIST(X) \
    X(BSP_RTC_NONE, 0U, 0U)

#define BSP_DAC_LIST(X) \
    X(BSP_DAC_NONE, 0U, 0U, 0U)

#define BSP_I2S_LIST(X) \
    X(BSP_I2S_NONE, 0U, 0U, 0U)

#define BSP_SAI_LIST(X) \
    X(BSP_SAI_NONE, 0U, 0U, 0U)

#define BSP_SDIO_LIST(X) \
    X(BSP_SDIO_NONE, 0U, 0U, 0U)

#define BSP_SD_LIST(X) \
    X(BSP_SD_NONE, 0U, 0U, 0U)

#define BSP_MMC_LIST(X) \
    X(BSP_MMC_NONE, 0U, 0U, 0U)

#define BSP_OSPI_LIST(X) \
    X(BSP_OSPI_NONE, 0U, 0U, 0U)

#define BSP_QSPI_LIST(X) \
    X(BSP_QSPI_NONE, 0U, 0U, 0U)

#define BSP_MCHTMR_LIST(X) \
    X(BSP_MCHTMR_MAIN, HPM_MCHTMR, clock_mchtmr0)

#define BSP_DMAV2_LIST(X) \
    X(BSP_DMAV2_MAIN, HPM_XDMA, IRQn_XDMA, clock_xdma)

#define BSP_ACMP_LIST(X) \
    X(BSP_ACMP_MAIN, HPM_ACMP0, clock_acmp0, 0U)

#define BSP_QEOV2_LIST(X) \
    X(BSP_QEOV2_MAIN, HPM_QEO0, clock_qeo0, 0U)

#define BSP_SDM_LIST(X) \
    X(BSP_SDM_MAIN, HPM_SDM0, clock_sdm0, 0U)

#define BSP_EUI_LIST(X) \
    X(BSP_EUI_MAIN, HPM_EUI0, clock_eui0, 0U)

#define BSP_OWR_LIST(X) \
    X(BSP_OWR_MAIN, HPM_OWR0, clock_owire0, 0U)

#define BSP_MBX_LIST(X) \
    X(BSP_MBX_LOCAL, HPM_MBX0A, clock_mbx0) \
    X(BSP_MBX_REMOTE, HPM_MBX0B, clock_mbx0)

#define BSP_LOBS_LIST(X) \
    X(BSP_LOBS_MAIN, HPM_LOBS, clock_lobs)

#define BSP_PLIC_LIST(X) \
    X(BSP_PLIC_MAIN, HPM_PLIC)

#define BSP_PPI_LIST(X) \
    X(BSP_PPI_MAIN, HPM_PPI, clock_ppi0, 0U)

#define BSP_PLB_LIST(X) \
    X(BSP_PLB_MAIN, HPM_PLB, clock_plb0)

#define BSP_PTPC_LIST(X) \
    X(BSP_PTPC_MAIN, HPM_PTPC, IRQn_PTPC, clock_ptpc)

#define BSP_SYNT_LIST(X) \
    X(BSP_SYNT_MAIN, HPM_SYNT)

#define BSP_PLLCTLV2_LIST(X) \
    X(BSP_PLLCTLV2_MAIN, HPM_PLLCTLV2)

#define BSP_PPOR_LIST(X) \
    X(BSP_PPOR_MAIN, HPM_PPOR)

#define BSP_PDGO_LIST(X) \
    X(BSP_PDGO_MAIN, HPM_PDGO)

/* GPIO mapping (aligned to current pinmux.c) */
#define BSP_GPIO_LED_PORT       HPM_GPIO0
#define BSP_GPIO_LED_PIN        IOC_PAD_PA03
#define BSP_GPIO_LED_INDEX      GPIO_DI_GPIOA
#define BSP_GPIO_LED_PIN_INDEX  3U

#define BSP_GPIO_LED2_PORT      HPM_GPIO0
#define BSP_GPIO_LED2_PIN       IOC_PAD_PA28
#define BSP_GPIO_LED2_INDEX     GPIO_DI_GPIOA
#define BSP_GPIO_LED2_PIN_INDEX 28U

#define BSP_GPIO_LED3_PORT      HPM_GPIO0
#define BSP_GPIO_LED3_PIN       IOC_PAD_PA20
#define BSP_GPIO_LED3_INDEX     GPIO_DI_GPIOA
#define BSP_GPIO_LED3_PIN_INDEX 20U

#define BSP_GPIO_LED4_PORT      HPM_GPIO0
#define BSP_GPIO_LED4_PIN       IOC_PAD_PA19
#define BSP_GPIO_LED4_INDEX     GPIO_DI_GPIOA
#define BSP_GPIO_LED4_PIN_INDEX 19U

#define BSP_GPIO_KEY_PORT       HPM_GPIO0
#define BSP_GPIO_KEY_PIN        IOC_PAD_PF19
#define BSP_GPIO_KEY_INDEX      GPIO_DI_GPIOF
#define BSP_GPIO_KEY_PIN_INDEX  19U

#define BSP_GPIO_LCD_CS_PORT       HPM_GPIO0
#define BSP_GPIO_LCD_CS_PIN        IOC_PAD_PC11
#define BSP_GPIO_LCD_CS_INDEX      GPIO_DI_GPIOC
#define BSP_GPIO_LCD_CS_PIN_INDEX  11U

#define BSP_GPIO_LCD_DC_PORT       HPM_GPIO0
#define BSP_GPIO_LCD_DC_PIN        IOC_PAD_PB26
#define BSP_GPIO_LCD_DC_INDEX      GPIO_DI_GPIOB
#define BSP_GPIO_LCD_DC_PIN_INDEX  26U

#define BSP_GPIO_LCD_RST_PORT       HPM_GPIO0
#define BSP_GPIO_LCD_RST_PIN        IOC_PAD_PB27
#define BSP_GPIO_LCD_RST_INDEX      GPIO_DI_GPIOB
#define BSP_GPIO_LCD_RST_PIN_INDEX  27U

#define BSP_GPIO_LCD_BL_PORT       HPM_GPIO0
#define BSP_GPIO_LCD_BL_PIN        IOC_PAD_PC16
#define BSP_GPIO_LCD_BL_INDEX      GPIO_DI_GPIOC
#define BSP_GPIO_LCD_BL_PIN_INDEX  16U

/* UART mapping */
#define BSP_UART_DEBUG_BASE     HPM_UART0
#define BSP_UART_DEBUG_IRQ      IRQn_UART0
#define BSP_UART_DEBUG_DMA_CONTROLLER HPM_XDMA
#define BSP_UART_DEBUG_DMA_IRQ        BOARD_APP_XDMA_IRQ
#define BSP_UART_DEBUG_DMAMUX         HPM_DMAMUX
#define BSP_UART_DEBUG_DMA_RX_REQ     HPM_DMA_SRC_UART0_RX
#define BSP_UART_DEBUG_DMA_TX_REQ     HPM_DMA_SRC_UART0_TX
#define BSP_UART_DEBUG_DMA_RX_CH      3U
#define BSP_UART_DEBUG_DMA_TX_CH      4U
#define BSP_UART_APP_BASE       HPM_UART3
#define BSP_UART_APP_IRQ        IRQn_UART3
#define BSP_UART_APP_DMA_CONTROLLER   HPM_XDMA
#define BSP_UART_APP_DMA_IRQ          BOARD_APP_XDMA_IRQ
#define BSP_UART_APP_DMAMUX           HPM_DMAMUX
#define BSP_UART_APP_DMA_RX_REQ       HPM_DMA_SRC_UART3_RX
#define BSP_UART_APP_DMA_TX_REQ       HPM_DMA_SRC_UART3_TX
#define BSP_UART_APP_DMA_RX_CH        5U
#define BSP_UART_APP_DMA_TX_CH        6U

/* PWM mapping (PA02 -> GPTMR1_COMP_1 in pinmux) */
#define BSP_PWM_LED_GPTMR       HPM_GPTMR1
#define BSP_PWM_LED_CHANNEL     1U
#define BSP_PWM_LED_CMP_INDEX   0U

/* GPTMR feature flags */
#define BSP_GPTMR_FEATURE_PERIODIC   (1U << 0)
#define BSP_GPTMR_FEATURE_ONESHOT    (1U << 1)
#define BSP_GPTMR_FEATURE_CAPTURE    (1U << 2)
#define BSP_GPTMR_FEATURE_COMPARE    (1U << 3)

/* ADC16 mapping */
#define BSP_ADC16_MAIN_BASE            HPM_ADC0
#define BSP_ADC16_MAIN_IRQ             IRQn_ADC0
#define BSP_ADC16_MAIN_CLK_NAME        clock_adc0
#define BSP_ADC16_MAIN_DEFAULT_CH      1U
#define BSP_ADC16_MAIN_CLK_SRC_BUS     1U
#define BSP_ADC16_MAIN_HAS_PINMUX      1U

/* GPTMR mapping */
#define BSP_GPTMR_TIMER_BASE           HPM_GPTMR3
#define BSP_GPTMR_TIMER_CHANNEL        1U
#define BSP_GPTMR_TIMER_IRQ            IRQn_GPTMR3
#define BSP_GPTMR_TIMER_CLK_NAME       clock_gptmr3

#define BSP_GPTMR_CAPTURE_BASE         HPM_GPTMR2
#define BSP_GPTMR_CAPTURE_CHANNEL      0U
#define BSP_GPTMR_CAPTURE_IRQ          IRQn_GPTMR2
#define BSP_GPTMR_CAPTURE_CLK_NAME     clock_gptmr2

#define BSP_GPTMR_COMPARE_BASE         HPM_GPTMR3
#define BSP_GPTMR_COMPARE_CHANNEL      0U
#define BSP_GPTMR_COMPARE_IRQ          IRQn_GPTMR3
#define BSP_GPTMR_COMPARE_CLK_NAME     clock_gptmr3

/* TRGM mapping */
#define BSP_TRGM_MAIN_BASE             HPM_TRGM0

/* PWMV2 mapping */
#define BSP_PWMV2_MAIN_BASE            HPM_PWM0
#define BSP_PWMV2_MAIN_IRQ             IRQn_PWM0
#define BSP_PWMV2_MAIN_CLK_NAME        clock_pwm0
#define BSP_PWMV2_MAIN_HAS_PINMUX      1U

/* SPI mapping */
#define BSP_SPI_MAIN_BASE              HPM_SPI1
#define BSP_SPI_MAIN_IRQ               IRQn_SPI1
#define BSP_SPI_MAIN_CLK_NAME          clock_spi1
#define BSP_SPI_MAIN_SCLK_FREQ         (20000000UL)
#define BSP_SPI_MAIN_DATA_LEN_IN_BITS  (8U)
#define BSP_SPI_MAIN_HAS_PINMUX        1U
#define BSP_SPI_MAIN_DMA_CONTROLLER    HPM_XDMA
#define BSP_SPI_MAIN_DMA_IRQ           BOARD_APP_XDMA_IRQ
#define BSP_SPI_MAIN_DMAMUX            HPM_DMAMUX
#define BSP_SPI_MAIN_DMA_TX_REQ        HPM_DMA_SRC_SPI1_TX
#define BSP_SPI_MAIN_DMA_RX_REQ        HPM_DMA_SRC_SPI1_RX
#define BSP_SPI_MAIN_DMA_TX_CH         1U
#define BSP_SPI_MAIN_DMA_RX_CH         0U

/* I2C mapping */
#define BSP_I2C_MAIN_BASE              HPM_I2C3
#define BSP_I2C_MAIN_IRQ               IRQn_I2C3
#define BSP_I2C_MAIN_CLK_NAME          clock_i2c3
#define BSP_I2C_MAIN_HAS_PINMUX        1U
#define BSP_I2C_MAIN_DMA_CONTROLLER    HPM_XDMA
#define BSP_I2C_MAIN_DMA_IRQ           BOARD_APP_XDMA_IRQ
#define BSP_I2C_MAIN_DMAMUX            HPM_DMAMUX
#define BSP_I2C_MAIN_DMA_REQ           HPM_DMA_SRC_I2C3
#define BSP_I2C_MAIN_DMA_CH            2U

/* MCAN mapping */
#define BSP_MCAN_MAIN_BASE             HPM_MCAN2
#define BSP_MCAN_MAIN_IRQ              IRQn_MCAN2
#define BSP_MCAN_MAIN_CLK_NAME         clock_can2
#define BSP_MCAN_MAIN_HAS_PINMUX       1U

/* QEIV2 mapping */
#define BSP_QEIV2_MAIN_BASE                HPM_QEI1
#define BSP_QEIV2_MAIN_IRQ                 IRQn_QEI1
#define BSP_QEIV2_MAIN_CLK_NAME            clock_qei1
#define BSP_QEIV2_MAIN_PHASE_COUNT_PER_REV BOARD_BLDC_QEI_FOC_PHASE_COUNT_PER_REV
#define BSP_QEIV2_MAIN_HAS_PINMUX          1U

/* CRC mapping */
#define BSP_CRC_MAIN_BASE                  HPM_CRC
#define BSP_CRC_MAIN_CLK_NAME              clock_crc0

/* TSNS mapping */
#define BSP_TSNS_MAIN_BASE                 HPM_TSNS
#define BSP_TSNS_MAIN_CLK_NAME             clock_tsns

/* EWDG mapping */
#define BSP_EWDG_MAIN_BASE                 HPM_EWDG0
#define BSP_EWDG_MAIN_CLK_NAME             clock_watchdog0

/* MCHTMR mapping */
#define BSP_MCHTMR_MAIN_BASE               HPM_MCHTMR
#define BSP_MCHTMR_MAIN_CLK_NAME           clock_mchtmr0

/* DMAV2 mapping */
#define BSP_DMAV2_MAIN_BASE                HPM_XDMA
#define BSP_DMAV2_MAIN_IRQ                 IRQn_XDMA
#define BSP_DMAV2_MAIN_CLK_NAME            clock_xdma

/* ACMP mapping */
#define BSP_ACMP_MAIN_BASE                 HPM_ACMP0
#define BSP_ACMP_MAIN_CLK_NAME             clock_acmp0
#define BSP_ACMP_MAIN_DEFAULT_CHANNEL      0U
#define BSP_ACMP_MAIN_HAS_PINMUX           0U

/* QEOV2 mapping */
#define BSP_QEOV2_MAIN_BASE                HPM_QEO0
#define BSP_QEOV2_MAIN_CLK_NAME            clock_qeo0
#define BSP_QEOV2_MAIN_HAS_PINMUX          0U

/* SDM mapping */
#define BSP_SDM_MAIN_BASE                  HPM_SDM0
#define BSP_SDM_MAIN_CLK_NAME              clock_sdm0
#define BSP_SDM_MAIN_DEFAULT_CHANNEL       0U
#define BSP_SDM_MAIN_HAS_PINMUX            0U

/* EUI mapping */
#define BSP_EUI_MAIN_BASE                  HPM_EUI0
#define BSP_EUI_MAIN_CLK_NAME              clock_eui0
#define BSP_EUI_MAIN_HAS_PINMUX            0U

/* OWR mapping */
#define BSP_OWR_MAIN_BASE                  HPM_OWR0
#define BSP_OWR_MAIN_CLK_NAME              clock_owire0
#define BSP_OWR_MAIN_HAS_PINMUX            0U

/* MBX mapping */
#define BSP_MBX_LOCAL_BASE                 HPM_MBX0A
#define BSP_MBX_LOCAL_CLK_NAME             clock_mbx0
#define BSP_MBX_REMOTE_BASE                HPM_MBX0B
#define BSP_MBX_REMOTE_CLK_NAME            clock_mbx0

/* LOBS mapping */
#define BSP_LOBS_MAIN_BASE                 HPM_LOBS
#define BSP_LOBS_MAIN_CLK_NAME             clock_lobs

/* PLIC mapping */
#define BSP_PLIC_MAIN_BASE                 HPM_PLIC

/* PPI mapping */
#define BSP_PPI_MAIN_BASE                  HPM_PPI
#define BSP_PPI_MAIN_CLK_NAME              clock_ppi0
#define BSP_PPI_MAIN_HAS_PINMUX            0U

/* PLB mapping */
#define BSP_PLB_MAIN_BASE                  HPM_PLB
#define BSP_PLB_MAIN_CLK_NAME              clock_plb0
#define BSP_PLB_MAIN_DEFAULT_CHANNEL       0U

/* PTPC mapping */
#define BSP_PTPC_MAIN_BASE                 HPM_PTPC
#define BSP_PTPC_MAIN_IRQ                  IRQn_PTPC
#define BSP_PTPC_MAIN_CLK_NAME             clock_ptpc
#define BSP_PTPC_MAIN_DEFAULT_INDEX        0U

/* SYNT mapping */
#define BSP_SYNT_MAIN_BASE                 HPM_SYNT
#define BSP_SYNT_MAIN_DEFAULT_RELOAD       0x1000U

/* PLLCTLV2 mapping */
#define BSP_PLLCTLV2_MAIN_BASE             HPM_PLLCTLV2
#define BSP_PLLCTLV2_MAIN_DEFAULT_PLL      1U
#define BSP_PLLCTLV2_MAIN_DEFAULT_CLK      0U

/* PPOR mapping */
#define BSP_PPOR_MAIN_BASE                 HPM_PPOR

/* PDGO mapping */
#define BSP_PDGO_MAIN_BASE                 HPM_PDGO
#define BSP_PDGO_MAIN_GPR_COUNT            8U

/* ENET mapping (RTL8211 + RGMII) */
#define BSP_ENET0_BASE              HPM_ENET0
#define BSP_ENET0_PHY_ADDR          2U
#define BSP_ENET0_PHY_RESET_GPIO    HPM_GPIO0
#define BSP_ENET0_PHY_RESET_INDEX   GPIO_DO_GPIOA
#define BSP_ENET0_PHY_RESET_PIN     21U
#define BSP_ENET0_MDIO_SHARED_ESC   1U

/* EtherCAT mapping (LAN8720A + ESC port0) */
#define BSP_ECAT0_BASE              HPM_ESC
#define BSP_ECAT0_PHY_ADDR          0U
#define BSP_ECAT0_PHY_RESET_GPIO    HPM_GPIO0
#define BSP_ECAT0_PHY_RESET_INDEX   GPIO_DO_GPIOA
#define BSP_ECAT0_PHY_RESET_PIN     21U
#define BSP_ECAT_PHY_LAN8720        1U

#ifdef __cplusplus
}
#endif

#endif /* BSP_CHIP_BOARD_CONFIG_H */
