
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 */

#include "clock.h"
#include "hpm_soc.h"
#include "hpm_clock_drv.h"
#include "hpm_pllctlv2_drv.h"


void init_clocks(void)
{
    /* Generate pll0 code */
    pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 25, 0);

    /* Generate clk0_pll0 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 0, 0);

    /* Generate clk1_pll0 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 1, 3);

    /* Generate pll1 code */
    pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 33, 80000000);

    /* Generate clk0_pll1 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 0, 5);

    /* Generate clk1_pll1 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 1, 7);

    /* Generate clk2_pll1 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 2, 10);

    /* Generate pll2 code */
    pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL2, 20, 200000000);

    /* Generate clk0_pll2 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL2, 0, 0);

    /* Generate clk1_pll2 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL2, 1, 5);

}
