
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 * Note:
 * PY and PZ IOs: if any SOC pin function needs to be routed to these IOs,
 * besides of IOC, PIOC/BIOC needs to be configured SOC_GPIO_X_xx, so that
 * expected SoC function can be enabled on these IOs.
 */

#ifndef HPM_PINMUX_H
#define HPM_PINMUX_H

#include "hpm_soc.h"

#ifdef __cplusplus
extern "C" {
#endif

void init_pins(void);
void init_led_pins(void);
void init_uart_pins(UART_Type *ptr);
void init_i2c_pins(I2C_Type *ptr);
void init_spi_pins(void);
void init_can_pins(MCAN_Type *ptr);
void init_adc16_pins(void);
void init_gptmr_pins(GPTMR_Type *ptr);
void init_esc_pins(void);
void init_esc_in_out_pin(void);
void init_esc_eeprom_pin(void);
void init_esc_eeprom_as_i2c_pin(void);

#ifdef __cplusplus
}
#endif
#endif /* HPM_PINMUX_H */
