#!/usr/bin/env python3
"""
Generate thin public C++ wrappers on top of the internal BSP C++ classes.

The config file uses JSON syntax saved as .yaml. JSON is valid YAML and keeps
the generator dependency-free.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List


MODULE_ORDER = [
    "gpio",
    "timer",
    "pwm",
    "adc",
    "trgm",
    "uart",
    "spi",
    "i2c",
    "can",
    "encoder",
    "encoder_output",
    "dma",
    "crc",
    "watchdog",
    "rng",
    "rtc",
    "wwdg",
    "cordic",
    "fmac",
    "dma2d",
    "mdma",
    "dac",
    "comp",
    "dcmi",
    "dfsdm",
    "eth",
    "ecat",
    "hcd",
    "jpeg",
    "ltdc",
    "mmc",
    "opamp",
    "ospi",
    "pcd",
    "pssi",
    "qspi",
    "sai",
    "sd",
    "sdio",
    "smartcard",
    "smbus",
    "usart",
    "tsns",
    "tsens",
    "mchtmr",
    "mailbox",
    "cache",
    "eui",
    "owr",
    "lobs",
    "plic",
    "plb",
    "ppi",
    "ptpc",
    "synt",
    "pll_ctl",
    "ppor",
    "pdgo",
    "usb_serial_jtag",
    "ana_cmpr",
    "cam",
    "parlio",
    "ppa",
    "pcnt",
    "rmt",
    "mcpwm",
    "sdspi",
    "sdmmc",
    "sdm",
    "lcd",
    "wifi",
    "touch",
    "i2s",
]


COMMON_HEADER = """// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include <array>
#include <cstdint>
#include <span>
#include <string_view>

#include "bsp/interface/bsp_common.h"
#include "bsp/interface/bsp_adc16.h"
#include "bsp/interface/bsp_enet.h"
#include "bsp/interface/bsp_gpio.h"
#include "bsp/interface/bsp_i2c.h"
#include "bsp/interface/bsp_pwm.h"
#include "bsp/interface/bsp_spi.h"
#include "bsp/interface/bsp_timer_common.h"
#include "bsp/interface/bsp_trgm.h"
#include "bsp/interface/bsp_uart.h"

enum class Status : std::int32_t {
    Ok = 0,
    Error = -1,
    Param = -2,
    Timeout = -3,
    Busy = -4,
    Unsupported = -5,
};

enum class Level : std::uint8_t {
    Low = 0,
    High = 1,
};

enum class GpioPull : std::uint8_t {
    None = 0,
    Up = 1,
    Down = 2,
};

enum class GpioOutputType : std::uint8_t {
    PushPull = 0,
    OpenDrain = 1,
};

enum class GpioMode : std::uint8_t {
    Input = 0,
    Output = 1,
    InterruptRising = 2,
    InterruptFalling = 3,
    InterruptBoth = 4,
};

enum class SpiMode : std::uint8_t {
    Mode0 = 0,
    Mode1 = 1,
    Mode2 = 2,
    Mode3 = 3,
};

enum class SpiBitOrder : std::uint8_t {
    MsbFirst = 0,
    LsbFirst = 1,
};

enum class SpiEvent : std::uint8_t {
    Write = 0,
    Read = 1,
    Transfer = 2,
};

enum class I2cEvent : std::uint8_t {
    Write = 0,
    Read = 1,
};

enum class TimerEvent : std::uint8_t {
    Elapsed = 0,
    Capture = 1,
    Compare = 2,
};

enum class PwmEvent : std::uint32_t {
    Reload = 1U << 0,
    Compare = 1U << 1,
    Fault = 1U << 2,
};

enum class UartParity : std::uint8_t {
    None = 0,
    Odd = 1,
    Even = 2,
    Always1 = 3,
    Always0 = 4,
};

enum class UartStopBits : std::uint8_t {
    One = 0,
    OneAndHalf = 1,
    Two = 2,
};

enum class UartWordLength : std::uint8_t {
    Bits5 = 0,
    Bits6 = 1,
    Bits7 = 2,
    Bits8 = 3,
};

enum class UartEvent : std::uint8_t {
    RxReady = 0,
    RxDone = 1,
    RxHalf = 2,
    RxIdle = 3,
    RxTimeout = 4,
    TxDone = 5,
    TxHalf = 6,
    Error = 7,
};

enum class TransferMode : std::uint8_t {
    Auto = 0,
    Blocking = 1,
    Interrupt = 2,
    Dma = 3,
};

using ByteView = std::span<const std::uint8_t>;
using ByteSpan = std::span<std::uint8_t>;
using AdcSample = bsp_adc16_sample_t;
using AdcTriggerRoute = bsp_adc16_trigger_route_t;
using AdcTriggerOutput = bsp_adc16_trigger_output_t;
using AdcResolution = bsp_adc16_resolution_t;
using AdcClockDivider = bsp_adc16_clock_divider_t;
using AdcInitConfig = bsp_adc16_init_config_t;
using AdcDmaSequenceConfig = bsp_adc16_dma_sequence_config_t;
using TrgmOutputRoute = bsp_trgm_output_route_t;
using TrgmOutputType = bsp_trgm_output_type_t;
using AdcSampleCallback = bsp_adc16_callback_t;
using AdcSequenceCallback = bsp_adc16_sequence_callback_t;
using AdcPreemptionCallback = bsp_adc16_preemption_callback_t;
using TimerEventCallback = bsp_timer_event_callback_t;
using PwmEventCallback = bsp_pwm_event_callback_t;
using SpiEventCallback = void(*)(bsp_spi_event_t event, std::int32_t status, void *arg);
using I2cEventCallback = void(*)(bsp_i2c_event_t event, std::int32_t status, void *arg);
using UartEventCallback = void(*)(bsp_uart_event_t event, std::uint8_t *data, std::uint16_t len, std::int32_t status, void *arg);
inline constexpr std::uint8_t DefaultIrqPriority = static_cast<std::uint8_t>(BSP_IRQ_PRIORITY_DEFAULT);

enum class MdioOwner : std::uint8_t {
    Enet = 0,
    Esc = 1,
};

enum class EthSpeed : std::uint8_t {
    Speed10M = 0,
    Speed100M = 1,
    Speed1000M = 2,
    Unknown = 3,
};

enum class EthDuplex : std::uint8_t {
    Half = 0,
    Full = 1,
    Unknown = 2,
};

struct EthLinkState {
    bool linkUp = false;
    EthSpeed speed = EthSpeed::Unknown;
    EthDuplex duplex = EthDuplex::Unknown;
};

struct CanFrame {
    std::uint32_t id = 0;
    std::uint8_t dlc = 0;
    bool extendedId = false;
    bool remoteFrame = false;
    bool fdFrame = false;
    bool bitrateSwitch = false;
    bool errorStateIndicator = false;
    std::array<std::uint8_t, 64> data{};
};

inline constexpr Status statusFromInternal(int status)
{
    switch (status) {
    case BSP_OK:
        return Status::Ok;
    case BSP_ERROR:
        return Status::Error;
    case BSP_ERROR_PARAM:
        return Status::Param;
    case BSP_ERROR_TIMEOUT:
        return Status::Timeout;
    case BSP_ERROR_BUSY:
        return Status::Busy;
    case BSP_ERROR_UNSUPPORTED:
        return Status::Unsupported;
    default:
        return Status::Error;
    }
}

inline constexpr bsp_level_t levelToInternal(Level level)
{
    return (level == Level::High) ? BSP_LEVEL_HIGH : BSP_LEVEL_LOW;
}

inline constexpr bsp_state_t stateFromBool(bool enabled)
{
    return enabled ? BSP_ENABLE : BSP_DISABLE;
}

inline constexpr bsp_gpio_pull_t gpioPullToInternal(GpioPull pull)
{
    switch (pull) {
    case GpioPull::Up:
        return BSP_GPIO_PULL_UP;
    case GpioPull::Down:
        return BSP_GPIO_PULL_DOWN;
    case GpioPull::None:
    default:
        return BSP_GPIO_PULL_NONE;
    }
}

inline constexpr bsp_gpio_output_type_t gpioOutputTypeToInternal(GpioOutputType type)
{
    return (type == GpioOutputType::OpenDrain) ? BSP_GPIO_OUTPUT_OPEN_DRAIN : BSP_GPIO_OUTPUT_PUSH_PULL;
}

inline constexpr bsp_gpio_mode_t gpioModeToInternal(GpioMode mode)
{
    switch (mode) {
    case GpioMode::Input:
        return BSP_GPIO_MODE_INPUT;
    case GpioMode::InterruptRising:
        return BSP_GPIO_MODE_IT_RISING;
    case GpioMode::InterruptFalling:
        return BSP_GPIO_MODE_IT_FALLING;
    case GpioMode::InterruptBoth:
        return BSP_GPIO_MODE_IT_BOTH;
    case GpioMode::Output:
    default:
        return BSP_GPIO_MODE_OUTPUT;
    }
}

inline constexpr bsp_spi_mode_t spiModeToInternal(SpiMode mode)
{
    switch (mode) {
    case SpiMode::Mode0:
        return BSP_SPI_MODE_0;
    case SpiMode::Mode1:
        return BSP_SPI_MODE_1;
    case SpiMode::Mode2:
        return BSP_SPI_MODE_2;
    case SpiMode::Mode3:
    default:
        return BSP_SPI_MODE_3;
    }
}

inline constexpr bsp_spi_bit_order_t spiBitOrderToInternal(SpiBitOrder order)
{
    return (order == SpiBitOrder::LsbFirst) ? BSP_SPI_BIT_ORDER_LSB_FIRST : BSP_SPI_BIT_ORDER_MSB_FIRST;
}

inline constexpr bsp_uart_parity_t uartParityToInternal(UartParity parity)
{
    switch (parity) {
    case UartParity::Odd:
        return BSP_UART_PARITY_ODD;
    case UartParity::Even:
        return BSP_UART_PARITY_EVEN;
    case UartParity::Always1:
        return BSP_UART_PARITY_ALWAYS_1;
    case UartParity::Always0:
        return BSP_UART_PARITY_ALWAYS_0;
    case UartParity::None:
    default:
        return BSP_UART_PARITY_NONE;
    }
}

inline constexpr bsp_uart_stop_bits_t uartStopBitsToInternal(UartStopBits stopBits)
{
    switch (stopBits) {
    case UartStopBits::OneAndHalf:
        return BSP_UART_STOP_BITS_1_5;
    case UartStopBits::Two:
        return BSP_UART_STOP_BITS_2;
    case UartStopBits::One:
    default:
        return BSP_UART_STOP_BITS_1;
    }
}

inline constexpr bsp_uart_word_length_t uartWordLengthToInternal(UartWordLength wordLength)
{
    switch (wordLength) {
    case UartWordLength::Bits5:
        return BSP_UART_WORD_LENGTH_5;
    case UartWordLength::Bits6:
        return BSP_UART_WORD_LENGTH_6;
    case UartWordLength::Bits7:
        return BSP_UART_WORD_LENGTH_7;
    case UartWordLength::Bits8:
    default:
        return BSP_UART_WORD_LENGTH_8;
    }
}

inline constexpr bsp_transfer_mode_t transferModeToInternal(TransferMode transferMode)
{
    switch (transferMode) {
    case TransferMode::Blocking:
        return BSP_TRANSFER_MODE_BLOCKING;
    case TransferMode::Interrupt:
        return BSP_TRANSFER_MODE_INTERRUPT;
    case TransferMode::Dma:
        return BSP_TRANSFER_MODE_DMA;
    case TransferMode::Auto:
    default:
        return BSP_TRANSFER_MODE_AUTO;
    }
}

inline constexpr bsp_mdio_owner_t mdioOwnerToInternal(MdioOwner owner)
{
    return (owner == MdioOwner::Esc) ? BSP_MDIO_OWNER_ESC : BSP_MDIO_OWNER_ENET;
}
"""


def enum_block(enum_name: str, instances: Dict[str, str]) -> str:
    lines = [f"enum class {enum_name} : std::uint8_t {{"]
    for public_name in instances:
        lines.append(f"    {public_name},")
    lines.append("};")
    return "\n".join(lines)


def switch_block(enum_name: str, internal_type: str, instances: Dict[str, str]) -> str:
    first_internal = next(iter(instances.values()))
    lines = [f"    static constexpr {internal_type} toInternal({enum_name} id)", "    {"]
    lines.append("        switch (id) {")
    for public_name, internal_name in instances.items():
        lines.append(f"        case {enum_name}::{public_name}:")
        lines.append(f"            return {internal_name};")
    lines.append("        }")
    lines.append(f"        return {first_internal};")
    lines.append("    }")
    return "\n".join(lines)


def class_block(class_name: str, enum_name: str, methods: List[str], private_helpers: List[str]) -> str:
    lines = [
        f"class {class_name} {{",
        "public:",
        f"    explicit constexpr {class_name}({enum_name} id) : id_(id) {{}}",
    ]
    for method in methods:
        lines.append(f"    {method}")
    lines.extend([
        "",
        "private:",
    ])
    for helper in private_helpers:
        lines.append(helper)
        lines.append("")
    lines.append(f"    {enum_name} id_;")
    lines.append("};")
    return "\n".join(lines)


MODULES = {
    "gpio": {
        "file": "Gpio.hpp",
        "include": "gpio.hpp",
        "header_include": "bsp/interface/bsp_gpio.h",
        "id_enum": "GpioId",
        "class": "Gpio",
        "internal_id_type": "bsp_gpio_pin_t",
        "methods": [
            "Status init(GpioMode mode = GpioMode::Output, GpioPull pull = GpioPull::None, GpioOutputType type = GpioOutputType::PushPull) const { return statusFromInternal(bsp_gpio_init(toInternal(id_), gpioModeToInternal(mode), gpioPullToInternal(pull), gpioOutputTypeToInternal(type))); }",
            "Status initInput(GpioPull pull = GpioPull::None) const { return init(GpioMode::Input, pull, GpioOutputType::PushPull); }",
            "Status initOutput(GpioOutputType type = GpioOutputType::PushPull, GpioPull pull = GpioPull::None) const { return init(GpioMode::Output, pull, type); }",
            "Status initInterruptRising(GpioPull pull = GpioPull::None) const { return init(GpioMode::InterruptRising, pull, GpioOutputType::PushPull); }",
            "Status initInterruptFalling(GpioPull pull = GpioPull::None) const { return init(GpioMode::InterruptFalling, pull, GpioOutputType::PushPull); }",
            "Status initInterruptBoth(GpioPull pull = GpioPull::None) const { return init(GpioMode::InterruptBoth, pull, GpioOutputType::PushPull); }",
            "Status onInterrupt(bsp_gpio_irq_callback_t callback, void *arg) const { return statusFromInternal(bsp_gpio_register_callback(toInternal(id_), callback, arg)); }",
            "void write(bool high) const { bsp_gpio_write(toInternal(id_), high ? BSP_LEVEL_HIGH : BSP_LEVEL_LOW); }",
            "bool read() const { return bsp_gpio_read(toInternal(id_)) == BSP_LEVEL_HIGH; }",
            "void toggle() const { bsp_gpio_toggle(toInternal(id_)); }",
        ],
    },
    "timer": {
        "file": "Timer.hpp",
        "include": "gptmr.hpp",
        "header_include": "bsp/interface/bsp_gptmr.h",
        "id_enum": "TimerId",
        "class": "Timer",
        "internal_id_type": "bsp_gptmr_instance_t",
        "module_enums": [
            """enum class TimerMode : std::uint8_t {
    Periodic = 0,
    Oneshot = 1,
    CaptureRising = 2,
    Compare = 3,
};""",
        ],
        "methods": [
            "Status init(TimerMode mode, std::uint32_t ticks) const { return statusFromInternal(bsp_gptmr_init(toInternal(id_), toInternal(mode), ticks)); }",
            "Status start() const { return statusFromInternal(bsp_gptmr_start(toInternal(id_))); }",
            "Status stop() const { return statusFromInternal(bsp_gptmr_stop(toInternal(id_))); }",
            "Status read(std::uint32_t &value) const { return statusFromInternal(bsp_gptmr_get_counter(toInternal(id_), &value)); }",
            "Status capture(std::uint32_t &value) const { return statusFromInternal(bsp_gptmr_get_capture(toInternal(id_), &value)); }",
            "Status compare(std::uint32_t ticks) const { return statusFromInternal(bsp_gptmr_set_compare(toInternal(id_), ticks)); }",
            "Status onEvent(TimerEventCallback callback, void *arg) const { return statusFromInternal(bsp_gptmr_register_event_callback(toInternal(id_), callback, arg)); }",
        ],
        "extra_helpers": [
            """    static constexpr bsp_gptmr_mode_t toInternal(TimerMode mode)
    {
        switch (mode) {
        case TimerMode::Periodic:
            return BSP_GPTMR_MODE_PERIODIC;
        case TimerMode::Oneshot:
            return BSP_GPTMR_MODE_ONESHOT;
        case TimerMode::CaptureRising:
            return BSP_GPTMR_MODE_CAPTURE_RISING;
        case TimerMode::Compare:
            return BSP_GPTMR_MODE_COMPARE;
        }
        return BSP_GPTMR_MODE_PERIODIC;
    }""",
        ],
    },
    "pwm": {
        "file": "Pwm.hpp",
        "include": "pwm.hpp",
        "header_include": "bsp/interface/bsp_pwm.h",
        "id_enum": "PwmId",
        "class": "Pwm",
        "internal_id_type": "bsp_pwm_instance_t",
        "module_enums": [
            """enum class PwmAlign : std::uint8_t {
    Edge = 0,
    Center = 1,
};""",
        ],
        "methods": [
            "Status init(std::uint32_t frequencyHz, PwmAlign align) const { return statusFromInternal(bsp_pwm_init(toInternal(id_), frequencyHz, toInternal(align))); }",
            "Status frequency(std::uint32_t &frequencyHz) const { return statusFromInternal(bsp_pwm_get_frequency(toInternal(id_), &frequencyHz)); }",
            "Status duty(std::uint8_t channel, float percent) const { return statusFromInternal(bsp_pwm_set_duty(toInternal(id_), channel, percent)); }",
            "Status compareTicks(std::uint8_t compareIndex, std::uint32_t ticks) const { return statusFromInternal(bsp_pwm_set_compare_ticks(toInternal(id_), compareIndex, ticks)); }",
            "Status output(std::uint8_t channel, bool enable) const { return statusFromInternal(bsp_pwm_enable_output(toInternal(id_), channel, stateFromBool(enable))); }",
            "Status pair(std::uint8_t channel, bool enable) const { return statusFromInternal(bsp_pwm_enable_pair(toInternal(id_), channel, stateFromBool(enable))); }",
            "Status deadtime(std::uint8_t channel, std::uint16_t ticks) const { return statusFromInternal(bsp_pwm_set_deadtime(toInternal(id_), channel, ticks)); }",
            "Status complementary(std::uint8_t channel, bool enable, std::uint16_t deadtimeTicks = 0U) const\n    {\n        const auto deadtimeStatus = deadtime(channel, deadtimeTicks);\n        if ((deadtimeStatus != Status::Ok) && (deadtimeStatus != Status::Unsupported)) {\n            return deadtimeStatus;\n        }\n        return pair(channel, enable);\n    }",
            "Status force(std::uint8_t channel, Level level) const { return statusFromInternal(bsp_pwm_force_output(toInternal(id_), channel, levelToInternal(level))); }",
            "Status start() const { return statusFromInternal(bsp_pwm_start(toInternal(id_))); }",
            "Status stop() const { return statusFromInternal(bsp_pwm_stop(toInternal(id_))); }",
            "Status onEvent(PwmEventCallback callback, void *arg) const { return statusFromInternal(bsp_pwm_register_event_callback(toInternal(id_), callback, arg)); }",
        ],
        "extra_helpers": [
            """    static constexpr bsp_pwm_align_t toInternal(PwmAlign align)
    {
        return (align == PwmAlign::Center) ? BSP_PWM_ALIGN_CENTER : BSP_PWM_ALIGN_EDGE;
    }""",
        ],
    },
    "adc": {
        "file": "Adc.hpp",
        "include": "adc.hpp",
        "header_include": "bsp/interface/bsp_adc16.h",
        "id_enum": "AdcId",
        "class": "Adc",
        "internal_id_type": "bsp_adc16_instance_t",
        "methods": [
            "Status init(AdcInitConfig config = {.resolution = BSP_ADC16_RESOLUTION_16_BITS, .clock_divider = BSP_ADC16_CLOCK_DIVIDER_4}) const { return statusFromInternal(bsp_adc16_init_ex(toInternal(id_), &config)); }",
            "Status clock(std::uint32_t &frequencyHz) const { return statusFromInternal(bsp_adc16_get_clock(toInternal(id_), &frequencyHz)); }",
            "Status read(std::uint16_t &value) const { return statusFromInternal(bsp_adc16_read_default(toInternal(id_), &value)); }",
            "Status read(std::uint8_t channel, std::uint16_t &value) const { return statusFromInternal(bsp_adc16_read_channel(toInternal(id_), channel, &value)); }",
            "Status configurePeriod(std::uint8_t channel, std::uint8_t prescalePow2, std::uint8_t periodCountMinus1) const { return statusFromInternal(bsp_adc16_configure_period(toInternal(id_), channel, prescalePow2, periodCountMinus1)); }",
            "Status configurePeriodHz(std::uint8_t channel, std::uint32_t sampleHz) const\n    {\n        if (sampleHz == 0U) {\n            return Status::Param;\n        }\n        std::uint32_t adcClockHz = 0U;\n        const auto clockStatus = clock(adcClockHz);\n        if (clockStatus != Status::Ok) {\n            return clockStatus;\n        }\n        std::uint8_t bestPrescalePow2 = 0U;\n        std::uint8_t bestPeriodCountMinus1 = 0U;\n        std::uint32_t bestErrorHz = 0xFFFFFFFFU;\n        for (std::uint32_t prescalePow2 = 0U; prescalePow2 <= 31U; ++prescalePow2) {\n            const std::uint64_t scale = (1ULL << prescalePow2);\n            const std::uint64_t periodCounts = static_cast<std::uint64_t>(adcClockHz) / (static_cast<std::uint64_t>(sampleHz) * scale);\n            if ((periodCounts == 0ULL) || (periodCounts > 256ULL)) {\n                continue;\n            }\n            const std::uint32_t periodCountMinus1 = static_cast<std::uint32_t>(periodCounts - 1ULL);\n            const std::uint64_t actualHz = static_cast<std::uint64_t>(adcClockHz) / (scale * static_cast<std::uint64_t>(periodCountMinus1 + 1U));\n            const std::uint32_t errorHz = (actualHz > sampleHz)\n                ? static_cast<std::uint32_t>(actualHz - sampleHz)\n                : static_cast<std::uint32_t>(sampleHz - actualHz);\n            if (errorHz < bestErrorHz) {\n                bestErrorHz = errorHz;\n                bestPrescalePow2 = static_cast<std::uint8_t>(prescalePow2);\n                bestPeriodCountMinus1 = static_cast<std::uint8_t>(periodCountMinus1);\n                if (errorHz == 0U) {\n                    break;\n                }\n            }\n        }\n        if (bestErrorHz == 0xFFFFFFFFU) {\n            return Status::Unsupported;\n        }\n        return configurePeriod(channel, bestPrescalePow2, bestPeriodCountMinus1);\n    }",
            "Status readPeriod(std::uint8_t channel, std::uint16_t &value) const { return statusFromInternal(bsp_adc16_read_period(toInternal(id_), channel, &value)); }",
            "Status readAsync() const { return statusFromInternal(bsp_adc16_read_default_async(toInternal(id_))); }",
            "Status readAsync(std::uint8_t channel) const { return statusFromInternal(bsp_adc16_read_channel_async(toInternal(id_), channel)); }",
            "Status onSample(AdcSampleCallback callback, void *arg) const { return statusFromInternal(bsp_adc16_register_callback(toInternal(id_), callback, arg)); }",
            "Status routeSequenceTrigger(const AdcTriggerRoute &route) const { return statusFromInternal(bsp_adc16_set_sequence_trigger_route(toInternal(id_), &route)); }",
            "Status configureSequence(std::span<const std::uint8_t> channels, bool continuous = true, bool hardwareTrigger = false) const { return statusFromInternal(bsp_adc16_configure_sequence(toInternal(id_), channels.data(), static_cast<std::uint8_t>(channels.size()), stateFromBool(continuous), stateFromBool(hardwareTrigger))); }",
            "Status startSequence() const { return statusFromInternal(bsp_adc16_start_sequence(toInternal(id_))); }",
            "Status startSequenceDma(std::span<std::uint32_t> buffer, bool circular = true) const\n    {\n        const AdcDmaSequenceConfig config{.buffer = buffer.data(), .sample_count = static_cast<std::uint32_t>(buffer.size()), .circular = stateFromBool(circular)};\n        return statusFromInternal(bsp_adc16_start_sequence_dma(toInternal(id_), &config));\n    }",
            "Status onSequence(AdcSequenceCallback callback, void *arg) const { return statusFromInternal(bsp_adc16_register_sequence_callback(toInternal(id_), callback, arg)); }",
            "Status routePreemptionTrigger(const AdcTriggerRoute &route) const { return statusFromInternal(bsp_adc16_set_preemption_trigger_route(toInternal(id_), &route)); }",
            "Status configurePreemption(std::uint8_t triggerChannel, std::span<const std::uint8_t> channels, bool hardwareTrigger = false) const { return statusFromInternal(bsp_adc16_configure_preemption(toInternal(id_), triggerChannel, channels.data(), static_cast<std::uint8_t>(channels.size()), stateFromBool(hardwareTrigger))); }",
            "Status startPreemption() const { return statusFromInternal(bsp_adc16_start_preemption(toInternal(id_))); }",
            "Status onPreemption(AdcPreemptionCallback callback, void *arg) const { return statusFromInternal(bsp_adc16_register_preemption_callback(toInternal(id_), callback, arg)); }",
        ],
    },
    "trgm": {
        "file": "Trgm.hpp",
        "include": "trgm.hpp",
        "header_include": "bsp/interface/bsp_trgm.h",
        "id_enum": "TrgmId",
        "class": "Trgm",
        "internal_id_type": "bsp_trgm_instance_t",
        "methods": [
            "Status routeOutput(const TrgmOutputRoute &route) const { return statusFromInternal(bsp_trgm_route_output(toInternal(id_), &route)); }",
            "Status dmaRequest(std::uint8_t dmaOutput, std::uint8_t dmaSource) const { return statusFromInternal(bsp_trgm_dma_request(toInternal(id_), dmaOutput, dmaSource)); }",
            "Status ioOutput(std::uint32_t mask, bool enable) const { return statusFromInternal(bsp_trgm_io_output(toInternal(id_), mask, stateFromBool(enable))); }",
        ],
    },
    "uart": {
        "file": "Uart.hpp",
        "include": "uart.hpp",
        "header_include": "bsp/interface/bsp_uart.h",
        "id_enum": "UartId",
        "class": "Uart",
        "internal_id_type": "bsp_uart_instance_t",
        "methods": [
            "Status init(std::uint32_t baudrate = 0U, UartParity parity = UartParity::None, UartStopBits stopBits = UartStopBits::One, UartWordLength wordLength = UartWordLength::Bits8, TransferMode transferMode = TransferMode::Auto, std::uint8_t irqPriority = DefaultIrqPriority) const { return statusFromInternal(bsp_uart_init(toInternal(id_), baudrate, uartParityToInternal(parity), uartStopBitsToInternal(stopBits), uartWordLengthToInternal(wordLength), transferModeToInternal(transferMode), irqPriority)); }",
            "Status write(ByteView data, std::uint32_t timeoutMs = 0U) const { return statusFromInternal(bsp_uart_send(toInternal(id_), const_cast<std::uint8_t *>(data.data()), static_cast<std::uint16_t>(data.size()), timeoutMs)); }",
            "Status write(std::string_view text, std::uint32_t timeoutMs = 0U) const { return write(ByteView(reinterpret_cast<const std::uint8_t *>(text.data()), text.size()), timeoutMs); }",
            "Status writeAsync(ByteView data) const { return statusFromInternal(bsp_uart_send_async(toInternal(id_), data.data(), static_cast<std::uint16_t>(data.size()))); }",
            "Status writeAsync(std::string_view text) const { return writeAsync(ByteView(reinterpret_cast<const std::uint8_t *>(text.data()), text.size())); }",
            "Status readAsync(ByteSpan buffer) const { return statusFromInternal(bsp_uart_receive_it(toInternal(id_), buffer.data(), static_cast<std::uint16_t>(buffer.size()))); }",
            "Status onEvent(UartEventCallback callback, void *arg) const { return statusFromInternal(bsp_uart_register_event_callback(toInternal(id_), callback, arg)); }",
        ],
    },
    "spi": {
        "file": "Spi.hpp",
        "include": "spi.hpp",
        "header_include": "bsp/interface/bsp_spi.h",
        "id_enum": "SpiId",
        "class": "Spi",
        "internal_id_type": "bsp_spi_instance_t",
        "methods": [
            "Status init(SpiMode mode = SpiMode::Mode3, std::uint32_t frequencyHz = 0U, SpiBitOrder bitOrder = SpiBitOrder::MsbFirst, TransferMode transferMode = TransferMode::Auto, std::uint8_t irqPriority = DefaultIrqPriority) const { return statusFromInternal(bsp_spi_init(toInternal(id_), spiModeToInternal(mode), frequencyHz, spiBitOrderToInternal(bitOrder), transferModeToInternal(transferMode), irqPriority)); }",
            "Status transfer(ByteView tx, ByteSpan rx) const\n    {\n        if (tx.size() != rx.size()) {\n            return Status::Param;\n        }\n        return statusFromInternal(bsp_spi_transfer(toInternal(id_), tx.data(), rx.data(), static_cast<std::uint32_t>(tx.size())));\n    }",
            "Status write(ByteView data) const { return statusFromInternal(bsp_spi_transfer(toInternal(id_), data.data(), nullptr, static_cast<std::uint32_t>(data.size()))); }",
            "Status transferAsync(ByteView tx, ByteSpan rx) const\n    {\n        if (tx.size() != rx.size()) {\n            return Status::Param;\n        }\n        return statusFromInternal(bsp_spi_transfer_async(toInternal(id_), tx.data(), rx.data(), static_cast<std::uint32_t>(tx.size())));\n    }",
            "Status onEvent(SpiEventCallback callback, void *arg) const { return statusFromInternal(bsp_spi_register_event_callback(toInternal(id_), callback, arg)); }",
        ],
    },
    "i2c": {
        "file": "I2c.hpp",
        "include": "i2c.hpp",
        "header_include": "bsp/interface/bsp_i2c.h",
        "id_enum": "I2cId",
        "class": "I2c",
        "internal_id_type": "bsp_i2c_instance_t",
        "methods": [
            "Status init(std::uint32_t frequencyHz = 0U, bool tenBitAddressing = false, TransferMode transferMode = TransferMode::Auto, std::uint8_t irqPriority = DefaultIrqPriority) const { return statusFromInternal(bsp_i2c_init(toInternal(id_), frequencyHz, stateFromBool(tenBitAddressing), transferModeToInternal(transferMode), irqPriority)); }",
            "Status write(std::uint16_t deviceAddress, ByteView data) const { return statusFromInternal(bsp_i2c_write(toInternal(id_), deviceAddress, data.data(), static_cast<std::uint32_t>(data.size()))); }",
            "Status read(std::uint16_t deviceAddress, ByteSpan data) const { return statusFromInternal(bsp_i2c_read(toInternal(id_), deviceAddress, data.data(), static_cast<std::uint32_t>(data.size()))); }",
            "Status writeRegister(std::uint16_t deviceAddress, std::uint8_t reg, std::uint8_t value) const { const std::array<std::uint8_t, 2> payload = {reg, value}; return write(deviceAddress, ByteView(payload.data(), payload.size())); }",
            "Status writeAsync(std::uint16_t deviceAddress, ByteView data) const { return statusFromInternal(bsp_i2c_write_async(toInternal(id_), deviceAddress, data.data(), static_cast<std::uint32_t>(data.size()))); }",
            "Status readAsync(std::uint16_t deviceAddress, ByteSpan data) const { return statusFromInternal(bsp_i2c_read_async(toInternal(id_), deviceAddress, data.data(), static_cast<std::uint32_t>(data.size()))); }",
            "Status onEvent(I2cEventCallback callback, void *arg) const { return statusFromInternal(bsp_i2c_register_event_callback(toInternal(id_), callback, arg)); }",
            """Status readRegister(std::uint16_t deviceAddress, std::uint8_t reg, ByteSpan data) const
    {
        const auto status = write(deviceAddress, ByteView(&reg, 1U));
        if (status != Status::Ok) {
            return status;
        }
        return read(deviceAddress, data);
    }""",
        ],
    },
    "can": {
        "file": "Can.hpp",
        "include": "mcan.hpp",
        "header_include": "bsp/interface/bsp_mcan.h",
        "id_enum": "CanId",
        "class": "Can",
        "internal_id_type": "bsp_mcan_instance_t",
        "extra_includes": ["<cstring>"],
        "methods": [
            "Status init(bool loopback = false) const { return statusFromInternal(bsp_mcan_init(toInternal(id_), loopback)); }",
            "Status defaultConfig(bsp_mcan_config_t &config, bool enableCanFd = false) const { return statusFromInternal(bsp_mcan_get_default_config(toInternal(id_), &config, enableCanFd)); }",
            "Status init(const bsp_mcan_config_t &config, std::uint8_t irqPriority = DefaultIrqPriority) const { return statusFromInternal(bsp_mcan_init_ex(toInternal(id_), &config, irqPriority)); }",
            "Status deinit() const { return statusFromInternal(bsp_mcan_deinit(toInternal(id_))); }",
            """Status write(const CanFrame &frame) const
    {
        if (frame.dlc > 8U) {
            return Status::Param;
        }
        const auto raw = toRawClassic(frame);
        return statusFromInternal(bsp_mcan_transmit(toInternal(id_), &raw));
    }""",
            """Status read(CanFrame &frame) const
    {
        bsp_mcan_frame_t raw{};
        const auto status = statusFromInternal(bsp_mcan_receive(toInternal(id_), &raw));
        if (status != Status::Ok) {
            return status;
        }
        return fromRawClassic(raw, frame);
    }""",
            "Status writeRaw(const bsp_mcan_frame_t &frame) const { return statusFromInternal(bsp_mcan_transmit(toInternal(id_), &frame)); }",
            "Status writeFifo(const bsp_mcan_frame_t &frame, std::uint32_t *fifoIndex = nullptr) const { return statusFromInternal(bsp_mcan_transmit_fifo(toInternal(id_), &frame, fifoIndex)); }",
            "Status writeBuffer(std::uint32_t bufferIndex, const bsp_mcan_frame_t &frame) const { return statusFromInternal(bsp_mcan_transmit_buffer(toInternal(id_), bufferIndex, &frame)); }",
            "Status readRaw(bsp_mcan_frame_t &frame) const { return statusFromInternal(bsp_mcan_receive(toInternal(id_), &frame)); }",
            "Status readFifo(std::uint32_t fifoIndex, bsp_mcan_frame_t &frame) const { return statusFromInternal(bsp_mcan_receive_fifo(toInternal(id_), fifoIndex, &frame)); }",
            "Status readBuffer(std::uint32_t bufferIndex, bsp_mcan_frame_t &frame) const { return statusFromInternal(bsp_mcan_receive_buffer(toInternal(id_), bufferIndex, &frame)); }",
            """Status loopback(const CanFrame &tx, CanFrame &rx) const
    {
        if (tx.dlc > 8U) {
            return Status::Param;
        }
        const auto rawTx = toRawClassic(tx);
        bsp_mcan_frame_t rawRx{};
        const auto status = statusFromInternal(bsp_mcan_loopback(toInternal(id_), &rawTx, &rawRx));
        if (status != Status::Ok) {
            return status;
        }
        return fromRawClassic(rawRx, rx);
    }""",
            """Status loopbackRaw(const bsp_mcan_frame_t &tx, bsp_mcan_frame_t &rx) const
    {
        return statusFromInternal(bsp_mcan_loopback(toInternal(id_), &tx, &rx));
    }""",
            "Status filters(const bsp_mcan_all_filters_config_t &config) const { return statusFromInternal(bsp_mcan_config_filters(toInternal(id_), &config)); }",
            "Status globalFilter(const bsp_mcan_global_filter_config_t &config) const { return statusFromInternal(bsp_mcan_set_global_filter(toInternal(id_), &config)); }",
            "Status protocolStatus(bsp_mcan_protocol_status_t &status) const { return statusFromInternal(bsp_mcan_get_protocol_status(toInternal(id_), &status)); }",
            "Status errorCount(bsp_mcan_error_count_t &count) const { return statusFromInternal(bsp_mcan_get_error_count(toInternal(id_), &count)); }",
            "Status readTxEvent(bsp_mcan_tx_event_fifo_elem_t &event) const { return statusFromInternal(bsp_mcan_read_tx_event(toInternal(id_), &event)); }",
            "Status rxTimestamp(const bsp_mcan_frame_t &frame, bsp_mcan_timestamp_value_t &timestamp) const { return statusFromInternal(bsp_mcan_get_timestamp_from_frame(toInternal(id_), &frame, &timestamp)); }",
            "Status txTimestamp(const bsp_mcan_tx_event_fifo_elem_t &event, bsp_mcan_timestamp_value_t &timestamp) const { return statusFromInternal(bsp_mcan_get_timestamp_from_tx_event(toInternal(id_), &event, &timestamp)); }",
            "Status cancel(std::uint32_t bufferIndex) const { return statusFromInternal(bsp_mcan_cancel_tx_request(toInternal(id_), bufferIndex)); }",
            "Status cancelled(std::uint32_t bufferIndex, bool &finished) const { return statusFromInternal(bsp_mcan_is_tx_request_cancelled(toInternal(id_), bufferIndex, &finished)); }",
            "Status onReceive(bsp_mcan_rx_callback_t callback, void *arg) const { return statusFromInternal(bsp_mcan_register_rx_callback(toInternal(id_), callback, arg)); }",
            "Status onTransmit(bsp_mcan_tx_callback_t callback, void *arg) const { return statusFromInternal(bsp_mcan_register_tx_callback(toInternal(id_), callback, arg)); }",
            "Status onEvent(bsp_mcan_event_callback_t callback, void *arg) const { return statusFromInternal(bsp_mcan_register_event_callback(toInternal(id_), callback, arg)); }",
            "static std::uint8_t payloadSize(std::uint8_t dlc) { return mcan_get_message_size_from_dlc(dlc); }",
        ],
        "extra_helpers": [
            """    static inline bsp_mcan_frame_t toRawClassic(const CanFrame &frame)
    {
        bsp_mcan_frame_t raw{};
        raw.id = frame.id;
        raw.dlc = frame.dlc;
        raw.extended_id = frame.extendedId;
        std::memcpy(raw.data, frame.data.data(), frame.data.size());
        return raw;
    }""",
            """    static inline Status fromRawClassic(const bsp_mcan_frame_t &frame, CanFrame &publicFrame)
    {
        const auto bytes = mcan_get_message_size_from_dlc(frame.dlc);
        if (frame.fd_frame || frame.remote_frame || (bytes > publicFrame.data.size())) {
            return Status::Unsupported;
        }
        publicFrame = {};
        publicFrame.id = frame.id;
        publicFrame.dlc = frame.dlc;
        publicFrame.extendedId = frame.extended_id;
        if (bytes > 0U) {
            std::memcpy(publicFrame.data.data(), frame.data, bytes);
        }
        return Status::Ok;
    }""",
        ],
    },
    "encoder": {
        "file": "Encoder.hpp",
        "include": "qeiv2.hpp",
        "header_include": "bsp/interface/bsp_qeiv2.h",
        "id_enum": "EncoderId",
        "class": "Encoder",
        "internal_id_type": "bsp_qeiv2_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_qeiv2_init(toInternal(id_))); }",
            "Status position(std::uint32_t &value) const { return statusFromInternal(bsp_qeiv2_get_position(toInternal(id_), &value)); }",
            "Status angle(std::uint32_t &value) const { return statusFromInternal(bsp_qeiv2_get_angle(toInternal(id_), &value)); }",
            "Status phaseCount(std::uint32_t &value) const { return statusFromInternal(bsp_qeiv2_get_phase_count(toInternal(id_), &value)); }",
            "Status speed(std::uint32_t &value) const { return statusFromInternal(bsp_qeiv2_get_speed(toInternal(id_), &value)); }",
        ],
    },
    "encoder_output": {
        "file": "EncoderOutput.hpp",
        "include": "qeov2.hpp",
        "header_include": "bsp/interface/bsp_qeov2.h",
        "id_enum": "EncoderOutputId",
        "class": "EncoderOutput",
        "internal_id_type": "bsp_qeov2_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_qeov2_init(toInternal(id_))); }",
            "Status start() const { return statusFromInternal(bsp_qeov2_start(toInternal(id_))); }",
            "Status stop() const { return statusFromInternal(bsp_qeov2_stop(toInternal(id_))); }",
        ],
    },
    "dma": {
        "file": "Dma.hpp",
        "include": "dmav2.hpp",
        "header_include": "bsp/interface/bsp_dmav2.h",
        "id_enum": "DmaId",
        "class": "Dma",
        "internal_id_type": "bsp_dmav2_instance_t",
        "methods": [
            """Status copy(ByteSpan destination, ByteView source) const
    {
        if (destination.size() != source.size()) {
            return Status::Param;
        }
        return statusFromInternal(bsp_dmav2_memcpy(toInternal(id_), destination.data(), source.data(), static_cast<std::uint32_t>(source.size())));
    }""",
            """Status copyAsync(ByteSpan destination, ByteView source) const
    {
        if (destination.size() != source.size()) {
            return Status::Param;
        }
        return statusFromInternal(bsp_dmav2_memcpy_async(toInternal(id_), destination.data(), source.data(), static_cast<std::uint32_t>(source.size())));
    }""",
            "Status onComplete(bsp_dmav2_callback_t callback, void *arg) const { return statusFromInternal(bsp_dmav2_register_callback(toInternal(id_), callback, arg)); }",
        ],
    },
    "crc": {
        "file": "Crc.hpp",
        "include": "crc.hpp",
        "header_include": "bsp/interface/bsp_crc.h",
        "id_enum": "CrcId",
        "class": "Crc",
        "internal_id_type": "bsp_crc_instance_t",
        "methods": [
            "Status calculate(ByteView data, std::uint32_t &crc) const { return statusFromInternal(bsp_crc32_calculate(toInternal(id_), data.data(), static_cast<std::uint32_t>(data.size()), &crc)); }",
        ],
    },
    "watchdog": {
        "file": "Watchdog.hpp",
        "include": "ewdg.hpp",
        "header_include": "bsp/interface/bsp_ewdg.h",
        "id_enum": "WatchdogId",
        "class": "Watchdog",
        "internal_id_type": "bsp_ewdg_instance_t",
        "methods": [
            "Status init(std::uint32_t timeoutMs) const { return statusFromInternal(bsp_ewdg_init(toInternal(id_), timeoutMs)); }",
            "Status refresh() const { return statusFromInternal(bsp_ewdg_refresh(toInternal(id_))); }",
            "Status deinit() const { return statusFromInternal(bsp_ewdg_deinit(toInternal(id_))); }",
        ],
    },
    "rng": {
        "file": "Rng.hpp",
        "include": "rng.hpp",
        "header_include": "bsp/interface/bsp_rng.h",
        "id_enum": "RngId",
        "class": "Rng",
        "internal_id_type": "bsp_rng_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_rng_init(toInternal(id_))); }",
            "Status read(std::uint32_t &value) const { return statusFromInternal(bsp_rng_get_u32(toInternal(id_), &value)); }",
        ],
    },
    "rtc": {
        "file": "Rtc.hpp",
        "include": "rtc.hpp",
        "header_include": "bsp/interface/bsp_rtc.h",
        "id_enum": "RtcId",
        "class": "Rtc",
        "internal_id_type": "bsp_rtc_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_rtc_init(toInternal(id_))); }",
            "Status now(std::uint32_t &unixSeconds) const { return statusFromInternal(bsp_rtc_get_unix_time(toInternal(id_), &unixSeconds)); }",
        ],
    },
    "wwdg": {
        "file": "Wwdg.hpp",
        "include": "wwdg.hpp",
        "header_include": "bsp/interface/bsp_wwdg.h",
        "id_enum": "WwdgId",
        "class": "Wwdg",
        "internal_id_type": "bsp_wwdg_instance_t",
        "methods": [
            "Status init(std::uint32_t timeoutMs) const { return statusFromInternal(bsp_wwdg_init(toInternal(id_), timeoutMs)); }",
            "Status refresh() const { return statusFromInternal(bsp_wwdg_refresh(toInternal(id_))); }",
        ],
    },
    "cordic": {
        "file": "Cordic.hpp",
        "include": "cordic.hpp",
        "header_include": "bsp/interface/bsp_cordic.h",
        "id_enum": "CordicId",
        "class": "Cordic",
        "internal_id_type": "bsp_cordic_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_cordic_init(toInternal(id_))); }",
        ],
    },
    "fmac": {
        "file": "Fmac.hpp",
        "include": "fmac.hpp",
        "header_include": "bsp/interface/bsp_fmac.h",
        "id_enum": "FmacId",
        "class": "Fmac",
        "internal_id_type": "bsp_fmac_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_fmac_init(toInternal(id_))); }",
        ],
    },
    "dma2d": {
        "file": "Dma2d.hpp",
        "include": "dma2d.hpp",
        "header_include": "bsp/interface/bsp_dma2d.h",
        "id_enum": "Dma2dId",
        "class": "Dma2d",
        "internal_id_type": "bsp_dma2d_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_dma2d_init(toInternal(id_))); }",
        ],
    },
    "mdma": {
        "file": "Mdma.hpp",
        "include": "mdma.hpp",
        "header_include": "bsp/interface/bsp_mdma.h",
        "id_enum": "MdmaId",
        "class": "Mdma",
        "internal_id_type": "bsp_mdma_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_mdma_init(toInternal(id_))); }",
        ],
    },
    "dac": {
        "file": "Dac.hpp",
        "include": "dac.hpp",
        "header_include": "bsp/interface/bsp_dac.h",
        "id_enum": "DacId",
        "class": "Dac",
        "internal_id_type": "bsp_dac_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_dac_init(toInternal(id_))); }",
            "Status write(std::uint8_t channel, std::uint32_t value) const { return statusFromInternal(bsp_dac_write(toInternal(id_), channel, value)); }",
        ],
    },
    "comp": {
        "file": "Comp.hpp",
        "include": "comp.hpp",
        "header_include": "bsp/interface/bsp_comp.h",
        "id_enum": "CompId",
        "class": "Comp",
        "internal_id_type": "bsp_comp_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_comp_init(toInternal(id_))); }",
        ],
    },
    "dcmi": {
        "file": "Dcmi.hpp",
        "include": "dcmi.hpp",
        "header_include": "bsp/interface/bsp_dcmi.h",
        "id_enum": "DcmiId",
        "class": "Dcmi",
        "internal_id_type": "bsp_dcmi_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_dcmi_init(toInternal(id_))); }",
        ],
    },
    "dfsdm": {
        "file": "Dfsdm.hpp",
        "include": "dfsdm.hpp",
        "header_include": "bsp/interface/bsp_dfsdm.h",
        "id_enum": "DfsdmId",
        "class": "Dfsdm",
        "internal_id_type": "bsp_dfsdm_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_dfsdm_init(toInternal(id_))); }",
        ],
    },
    "eth": {
        "file": "Eth.hpp",
        "include": "enet.hpp",
        "header_include": "bsp/interface/bsp_enet.h",
        "id_enum": "EthId",
        "class": "Eth",
        "internal_id_type": "bsp_enet_port_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_enet_init(toInternal(id_))); }",
            "Status selectMdioOwner(MdioOwner owner) const { return statusFromInternal(bsp_enet_set_mdio_owner(mdioOwnerToInternal(owner))); }",
            """Status linkState(EthLinkState &state) const
    {
        bsp_enet_link_state_t internal{};
        const auto status = statusFromInternal(bsp_enet_get_link_state(toInternal(id_), &internal));
        if (status == Status::Ok) {
            state.linkUp = (internal.link_up == BSP_ENABLE);
            switch (internal.speed) {
            case BSP_ENET_SPEED_10M:
                state.speed = EthSpeed::Speed10M;
                break;
            case BSP_ENET_SPEED_100M:
                state.speed = EthSpeed::Speed100M;
                break;
            case BSP_ENET_SPEED_1000M:
                state.speed = EthSpeed::Speed1000M;
                break;
            default:
                state.speed = EthSpeed::Unknown;
                break;
            }
            switch (internal.duplex) {
            case BSP_ENET_DUPLEX_HALF:
                state.duplex = EthDuplex::Half;
                break;
            case BSP_ENET_DUPLEX_FULL:
                state.duplex = EthDuplex::Full;
                break;
            default:
                state.duplex = EthDuplex::Unknown;
                break;
            }
        }
        return status;
    }""",
        ],
    },
    "ecat": {
        "file": "Ecat.hpp",
        "include": "ecat.hpp",
        "header_include": "bsp/interface/bsp_ecat.h",
        "id_enum": "EcatId",
        "class": "Ecat",
        "internal_id_type": "bsp_ecat_port_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_ecat_init(toInternal(id_))); }",
            "Status initSwitchLed() const { return statusFromInternal(bsp_ecat_init_switch_led(toInternal(id_))); }",
            "Status selectMdioOwner(MdioOwner owner) const { return statusFromInternal(bsp_ecat_set_mdio_owner(mdioOwnerToInternal(owner))); }",
        ],
    },
    "hcd": {
        "file": "Hcd.hpp",
        "include": "hcd.hpp",
        "header_include": "bsp/interface/bsp_hcd.h",
        "id_enum": "HcdId",
        "class": "Hcd",
        "internal_id_type": "bsp_hcd_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_hcd_init(toInternal(id_))); }",
        ],
    },
    "jpeg": {
        "file": "Jpeg.hpp",
        "include": "jpeg.hpp",
        "header_include": "bsp/interface/bsp_jpeg.h",
        "id_enum": "JpegId",
        "class": "Jpeg",
        "internal_id_type": "bsp_jpeg_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_jpeg_init(toInternal(id_))); }",
        ],
    },
    "ltdc": {
        "file": "Ltdc.hpp",
        "include": "ltdc.hpp",
        "header_include": "bsp/interface/bsp_ltdc.h",
        "id_enum": "LtdcId",
        "class": "Ltdc",
        "internal_id_type": "bsp_ltdc_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_ltdc_init(toInternal(id_))); }",
        ],
    },
    "mmc": {
        "file": "Mmc.hpp",
        "include": "mmc.hpp",
        "header_include": "bsp/interface/bsp_mmc.h",
        "id_enum": "MmcId",
        "class": "Mmc",
        "internal_id_type": "bsp_mmc_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_mmc_init(toInternal(id_))); }",
            "Status readBlocks(std::uint32_t block, ByteSpan data, std::uint32_t blockCount) const { return statusFromInternal(bsp_mmc_read_blocks(toInternal(id_), block, data.data(), blockCount)); }",
            "Status writeBlocks(std::uint32_t block, ByteView data, std::uint32_t blockCount) const { return statusFromInternal(bsp_mmc_write_blocks(toInternal(id_), block, data.data(), blockCount)); }",
        ],
    },
    "opamp": {
        "file": "Opamp.hpp",
        "include": "opamp.hpp",
        "header_include": "bsp/interface/bsp_opamp.h",
        "id_enum": "OpampId",
        "class": "Opamp",
        "internal_id_type": "bsp_opamp_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_opamp_init(toInternal(id_))); }",
        ],
    },
    "ospi": {
        "file": "Ospi.hpp",
        "include": "ospi.hpp",
        "header_include": "bsp/interface/bsp_ospi.h",
        "id_enum": "OspiId",
        "class": "Ospi",
        "internal_id_type": "bsp_ospi_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_ospi_init(toInternal(id_))); }",
            "Status read(std::uint32_t address, ByteSpan data) const { return statusFromInternal(bsp_ospi_read(toInternal(id_), address, data.data(), static_cast<std::uint32_t>(data.size()))); }",
            "Status write(std::uint32_t address, ByteView data) const { return statusFromInternal(bsp_ospi_write(toInternal(id_), address, data.data(), static_cast<std::uint32_t>(data.size()))); }",
        ],
    },
    "pcd": {
        "file": "Pcd.hpp",
        "include": "pcd.hpp",
        "header_include": "bsp/interface/bsp_pcd.h",
        "id_enum": "PcdId",
        "class": "Pcd",
        "internal_id_type": "bsp_pcd_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_pcd_init(toInternal(id_))); }",
        ],
    },
    "pssi": {
        "file": "Pssi.hpp",
        "include": "pssi.hpp",
        "header_include": "bsp/interface/bsp_pssi.h",
        "id_enum": "PssiId",
        "class": "Pssi",
        "internal_id_type": "bsp_pssi_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_pssi_init(toInternal(id_))); }",
        ],
    },
    "qspi": {
        "file": "Qspi.hpp",
        "include": "qspi.hpp",
        "header_include": "bsp/interface/bsp_qspi.h",
        "id_enum": "QspiId",
        "class": "Qspi",
        "internal_id_type": "bsp_qspi_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_qspi_init(toInternal(id_))); }",
            "Status read(std::uint32_t address, ByteSpan data) const { return statusFromInternal(bsp_qspi_read(toInternal(id_), address, data.data(), static_cast<std::uint32_t>(data.size()))); }",
            "Status write(std::uint32_t address, ByteView data) const { return statusFromInternal(bsp_qspi_write(toInternal(id_), address, data.data(), static_cast<std::uint32_t>(data.size()))); }",
        ],
    },
    "sai": {
        "file": "Sai.hpp",
        "include": "sai.hpp",
        "header_include": "bsp/interface/bsp_sai.h",
        "id_enum": "SaiId",
        "class": "Sai",
        "internal_id_type": "bsp_sai_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_sai_init(toInternal(id_))); }",
            "Status write(ByteView data) const { return statusFromInternal(bsp_sai_write(toInternal(id_), data.data(), static_cast<std::uint32_t>(data.size()))); }",
            "Status read(ByteSpan data) const { return statusFromInternal(bsp_sai_read(toInternal(id_), data.data(), static_cast<std::uint32_t>(data.size()))); }",
        ],
    },
    "sd": {
        "file": "Sd.hpp",
        "include": "sd.hpp",
        "header_include": "bsp/interface/bsp_sd.h",
        "id_enum": "SdId",
        "class": "Sd",
        "internal_id_type": "bsp_sd_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_sd_init(toInternal(id_))); }",
            "Status readBlocks(std::uint32_t block, ByteSpan data, std::uint32_t blockCount) const { return statusFromInternal(bsp_sd_read_blocks(toInternal(id_), block, data.data(), blockCount)); }",
            "Status writeBlocks(std::uint32_t block, ByteView data, std::uint32_t blockCount) const { return statusFromInternal(bsp_sd_write_blocks(toInternal(id_), block, data.data(), blockCount)); }",
        ],
    },
    "sdio": {
        "file": "Sdio.hpp",
        "include": "sdio.hpp",
        "header_include": "bsp/interface/bsp_sdio.h",
        "id_enum": "SdioId",
        "class": "Sdio",
        "internal_id_type": "bsp_sdio_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_sdio_init(toInternal(id_))); }",
            "Status readBlocks(std::uint32_t block, ByteSpan data, std::uint32_t blockCount) const { return statusFromInternal(bsp_sdio_read_blocks(toInternal(id_), block, data.data(), blockCount)); }",
            "Status writeBlocks(std::uint32_t block, ByteView data, std::uint32_t blockCount) const { return statusFromInternal(bsp_sdio_write_blocks(toInternal(id_), block, data.data(), blockCount)); }",
        ],
    },
    "smartcard": {
        "file": "Smartcard.hpp",
        "include": "smartcard.hpp",
        "header_include": "bsp/interface/bsp_smartcard.h",
        "id_enum": "SmartcardId",
        "class": "Smartcard",
        "internal_id_type": "bsp_smartcard_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_smartcard_init(toInternal(id_))); }",
        ],
    },
    "smbus": {
        "file": "Smbus.hpp",
        "include": "smbus.hpp",
        "header_include": "bsp/interface/bsp_smbus.h",
        "id_enum": "SmbusId",
        "class": "Smbus",
        "internal_id_type": "bsp_smbus_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_smbus_init(toInternal(id_))); }",
        ],
    },
    "usart": {
        "file": "Usart.hpp",
        "include": "usart.hpp",
        "header_include": "bsp/interface/bsp_usart.h",
        "id_enum": "UsartId",
        "class": "Usart",
        "internal_id_type": "bsp_usart_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_usart_init(toInternal(id_))); }",
        ],
    },
    "tsns": {
        "file": "Tsns.hpp",
        "include": "tsns.hpp",
        "header_include": "bsp/interface/bsp_tsns.h",
        "id_enum": "TsnsId",
        "class": "Tsns",
        "internal_id_type": "bsp_tsns_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_tsns_init(toInternal(id_))); }",
            "Status read(float &celsius) const { return statusFromInternal(bsp_tsns_read_celsius(toInternal(id_), &celsius)); }",
        ],
    },
    "tsens": {
        "file": "Tsens.hpp",
        "include": "tsens.hpp",
        "header_include": "bsp/interface/bsp_tsens.h",
        "id_enum": "TsensId",
        "class": "Tsens",
        "internal_id_type": "bsp_tsens_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_tsens_init(toInternal(id_))); }",
            "Status read(float &celsius) const { return statusFromInternal(bsp_tsens_read_celsius(toInternal(id_), &celsius)); }",
        ],
    },
    "mchtmr": {
        "file": "Mchtmr.hpp",
        "include": "mchtmr.hpp",
        "header_include": "bsp/interface/bsp_mchtmr.h",
        "id_enum": "MchtmrId",
        "class": "Mchtmr",
        "internal_id_type": "bsp_mchtmr_instance_t",
        "methods": [
            "Status count(std::uint64_t &ticks) const { return statusFromInternal(bsp_mchtmr_get_count(toInternal(id_), &ticks)); }",
            "Status delay(std::uint64_t ticks) const { return statusFromInternal(bsp_mchtmr_delay_ticks(toInternal(id_), ticks)); }",
        ],
    },
    "mailbox": {
        "file": "Mailbox.hpp",
        "include": "mbx.hpp",
        "header_include": "bsp/interface/bsp_mbx.h",
        "id_enum": "MailboxId",
        "class": "Mailbox",
        "internal_id_type": "bsp_mbx_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_mbx_init(toInternal(id_))); }",
            "Status send(std::uint32_t data) const { return statusFromInternal(bsp_mbx_try_send(toInternal(id_), data)); }",
            "Status receive(std::uint32_t &data) const { return statusFromInternal(bsp_mbx_try_receive(toInternal(id_), &data)); }",
        ],
    },
    "cache": {
        "file": "Cache.hpp",
        "include": "l1c.hpp",
        "header_include": "bsp/interface/bsp_l1c.h",
        "id_enum": "CacheId",
        "class": "Cache",
        "internal_id_type": "bsp_l1c_instance_t",
        "methods": [
            "Status status(bool &instructionEnabled, bool &dataEnabled) const { return statusFromInternal(bsp_l1c_get_status(toInternal(id_), &instructionEnabled, &dataEnabled)); }",
            "Status invalidateData() const { return statusFromInternal(bsp_l1c_invalidate_dcache_all(toInternal(id_))); }",
        ],
    },
    "eui": {
        "file": "Eui.hpp",
        "include": "eui.hpp",
        "header_include": "bsp/interface/bsp_eui.h",
        "id_enum": "EuiId",
        "class": "Eui",
        "internal_id_type": "bsp_eui_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_eui_init(toInternal(id_))); }",
            "Status enable(bool enabled) const { return statusFromInternal(bsp_eui_enable(toInternal(id_), stateFromBool(enabled))); }",
            "Status irqStatus(std::uint32_t &status) const { return statusFromInternal(bsp_eui_get_irq_status(toInternal(id_), &status)); }",
        ],
    },
    "owr": {
        "file": "Owr.hpp",
        "include": "owr.hpp",
        "header_include": "bsp/interface/bsp_owr.h",
        "id_enum": "OwrId",
        "class": "Owr",
        "internal_id_type": "bsp_owr_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_owr_init(toInternal(id_))); }",
            "Status presence(std::uint32_t &status) const { return statusFromInternal(bsp_owr_get_presence(toInternal(id_), &status)); }",
        ],
    },
    "lobs": {
        "file": "Lobs.hpp",
        "include": "lobs.hpp",
        "header_include": "bsp/interface/bsp_lobs.h",
        "id_enum": "LobsId",
        "class": "Lobs",
        "internal_id_type": "bsp_lobs_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_lobs_init(toInternal(id_))); }",
            "Status enable(bool enabled) const { return statusFromInternal(bsp_lobs_enable(toInternal(id_), stateFromBool(enabled))); }",
        ],
    },
    "plic": {
        "file": "Plic.hpp",
        "include": "plic.hpp",
        "header_include": "bsp/interface/bsp_plic.h",
        "id_enum": "PlicId",
        "class": "Plic",
        "internal_id_type": "bsp_plic_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_plic_init(toInternal(id_))); }",
            "Status configure(std::uint32_t irq, std::uint32_t priority, bool enable) const { return statusFromInternal(bsp_plic_config_irq(toInternal(id_), irq, priority, stateFromBool(enable))); }",
        ],
    },
    "plb": {
        "file": "Plb.hpp",
        "include": "plb.hpp",
        "header_include": "bsp/interface/bsp_plb.h",
        "id_enum": "PlbId",
        "class": "Plb",
        "internal_id_type": "bsp_plb_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_plb_init(toInternal(id_))); }",
            "Status counter(std::uint8_t channel, std::uint32_t &value) const { return statusFromInternal(bsp_plb_get_counter(toInternal(id_), channel, &value)); }",
        ],
    },
    "ppi": {
        "file": "Ppi.hpp",
        "include": "ppi.hpp",
        "header_include": "bsp/interface/bsp_ppi.h",
        "id_enum": "PpiId",
        "class": "Ppi",
        "internal_id_type": "bsp_ppi_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_ppi_init(toInternal(id_))); }",
            "Status timeout(std::uint16_t count, bool enable) const { return statusFromInternal(bsp_ppi_config_timeout(toInternal(id_), count, stateFromBool(enable))); }",
        ],
    },
    "ptpc": {
        "file": "Ptpc.hpp",
        "include": "ptpc.hpp",
        "header_include": "bsp/interface/bsp_ptpc.h",
        "id_enum": "PtpcId",
        "class": "Ptpc",
        "internal_id_type": "bsp_ptpc_instance_t",
        "methods": [
            "Status init(std::uint8_t timerIndex) const { return statusFromInternal(bsp_ptpc_init(toInternal(id_), timerIndex)); }",
            "Status time(std::uint8_t timerIndex, std::uint32_t &second, std::uint32_t &nanosecond) const { return statusFromInternal(bsp_ptpc_get_time(toInternal(id_), timerIndex, &second, &nanosecond)); }",
        ],
    },
    "synt": {
        "file": "Synt.hpp",
        "include": "synt.hpp",
        "header_include": "bsp/interface/bsp_synt.h",
        "id_enum": "SyntId",
        "class": "Synt",
        "internal_id_type": "bsp_synt_instance_t",
        "methods": [
            "Status init(std::uint32_t reloadCount) const { return statusFromInternal(bsp_synt_init(toInternal(id_), reloadCount)); }",
            "Status start() const { return statusFromInternal(bsp_synt_start(toInternal(id_))); }",
            "Status stop() const { return statusFromInternal(bsp_synt_stop(toInternal(id_))); }",
            "Status read(std::uint32_t &count) const { return statusFromInternal(bsp_synt_get_count(toInternal(id_), &count)); }",
        ],
    },
    "pll_ctl": {
        "file": "PllCtl.hpp",
        "include": "pllctlv2.hpp",
        "header_include": "bsp/interface/bsp_pllctlv2.h",
        "id_enum": "PllCtlId",
        "class": "PllCtl",
        "internal_id_type": "bsp_pllctlv2_instance_t",
        "methods": [
            "Status frequency(std::uint8_t pllIndex, std::uint32_t &frequencyHz) const { return statusFromInternal(bsp_pllctlv2_get_pll_freq(toInternal(id_), pllIndex, &frequencyHz)); }",
            "Status stable(std::uint8_t pllIndex, bool &isStable) const { return statusFromInternal(bsp_pllctlv2_is_pll_stable(toInternal(id_), pllIndex, &isStable)); }",
        ],
    },
    "ppor": {
        "file": "Ppor.hpp",
        "include": "ppor.hpp",
        "header_include": "bsp/interface/bsp_ppor.h",
        "id_enum": "PporId",
        "class": "Ppor",
        "internal_id_type": "bsp_ppor_instance_t",
        "methods": [
            "Status flags(std::uint32_t &value) const { return statusFromInternal(bsp_ppor_get_reset_flags(toInternal(id_), &value)); }",
            "Status clear(std::uint32_t mask) const { return statusFromInternal(bsp_ppor_clear_reset_flags(toInternal(id_), mask)); }",
        ],
    },
    "pdgo": {
        "file": "Pdgo.hpp",
        "include": "pdgo.hpp",
        "header_include": "bsp/interface/bsp_pdgo.h",
        "id_enum": "PdgoId",
        "class": "Pdgo",
        "internal_id_type": "bsp_pdgo_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_pdgo_init(toInternal(id_))); }",
            "Status wakeup(std::uint32_t &status) const { return statusFromInternal(bsp_pdgo_get_wakeup_status(toInternal(id_), &status)); }",
            "Status write(std::uint32_t index, std::uint32_t value) const { return statusFromInternal(bsp_pdgo_write_gpr(toInternal(id_), index, value)); }",
            "Status read(std::uint32_t index, std::uint32_t &value) const { return statusFromInternal(bsp_pdgo_read_gpr(toInternal(id_), index, &value)); }",
        ],
    },
    "usb_serial_jtag": {
        "file": "UsbSerialJtag.hpp",
        "include": "usb_serial_jtag.hpp",
        "header_include": "bsp/interface/bsp_usb_serial_jtag.h",
        "id_enum": "UsbSerialJtagId",
        "class": "UsbSerialJtag",
        "internal_id_type": "bsp_usb_serial_jtag_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_usb_serial_jtag_init(toInternal(id_))); }",
            "Status write(ByteView data, std::uint32_t timeoutMs = 0U) const { return statusFromInternal(bsp_usb_serial_jtag_write(toInternal(id_), data.data(), static_cast<std::uint32_t>(data.size()), timeoutMs)); }",
            "Status write(std::string_view text, std::uint32_t timeoutMs = 0U) const { return write(ByteView(reinterpret_cast<const std::uint8_t *>(text.data()), text.size()), timeoutMs); }",
            "Status read(ByteSpan buffer, std::uint32_t timeoutMs = 0U) const { return statusFromInternal(bsp_usb_serial_jtag_read(toInternal(id_), buffer.data(), static_cast<std::uint32_t>(buffer.size()), timeoutMs)); }",
        ],
    },
    "ana_cmpr": {
        "file": "AnaCmpr.hpp",
        "include": "acmp.hpp",
        "header_include": "bsp/interface/bsp_acmp.h",
        "id_enum": "AnaCmprId",
        "class": "AnaCmpr",
        "internal_id_type": "bsp_acmp_instance_t",
        "methods": [
            "Status init(std::uint8_t channel = 0U) const { return statusFromInternal(bsp_acmp_init(toInternal(id_), channel)); }",
        ],
    },
    "cam": {
        "file": "Cam.hpp",
        "include": "cam.hpp",
        "header_include": "bsp/interface/bsp_cam.h",
        "id_enum": "CamId",
        "class": "Cam",
        "internal_id_type": "bsp_cam_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_cam_init(toInternal(id_))); }",
        ],
    },
    "parlio": {
        "file": "Parlio.hpp",
        "include": "parlio.hpp",
        "header_include": "bsp/interface/bsp_parlio.h",
        "id_enum": "ParlioId",
        "class": "Parlio",
        "internal_id_type": "bsp_parlio_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_parlio_init(toInternal(id_))); }",
        ],
    },
    "ppa": {
        "file": "Ppa.hpp",
        "include": "ppa.hpp",
        "header_include": "bsp/interface/bsp_ppa.h",
        "id_enum": "PpaId",
        "class": "Ppa",
        "internal_id_type": "bsp_ppa_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_ppa_init(toInternal(id_))); }",
        ],
    },
    "pcnt": {
        "file": "Pcnt.hpp",
        "include": "pcnt.hpp",
        "header_include": "bsp/interface/bsp_pcnt.h",
        "id_enum": "PcntId",
        "class": "Pcnt",
        "internal_id_type": "bsp_pcnt_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_pcnt_init(toInternal(id_))); }",
        ],
    },
    "rmt": {
        "file": "Rmt.hpp",
        "include": "rmt.hpp",
        "header_include": "bsp/interface/bsp_rmt.h",
        "id_enum": "RmtId",
        "class": "Rmt",
        "internal_id_type": "bsp_rmt_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_rmt_init(toInternal(id_))); }",
        ],
    },
    "mcpwm": {
        "file": "Mcpwm.hpp",
        "include": "mcpwm.hpp",
        "header_include": "bsp/interface/bsp_mcpwm.h",
        "id_enum": "McpwmId",
        "class": "Mcpwm",
        "internal_id_type": "bsp_mcpwm_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_mcpwm_init(toInternal(id_))); }",
        ],
    },
    "sdspi": {
        "file": "Sdspi.hpp",
        "include": "sdspi.hpp",
        "header_include": "bsp/interface/bsp_sdspi.h",
        "id_enum": "SdspiId",
        "class": "Sdspi",
        "internal_id_type": "bsp_sdspi_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_sdspi_init(toInternal(id_))); }",
        ],
    },
    "sdmmc": {
        "file": "Sdmmc.hpp",
        "include": "sdmmc.hpp",
        "header_include": "bsp/interface/bsp_sdmmc.h",
        "id_enum": "SdmmcId",
        "class": "Sdmmc",
        "internal_id_type": "bsp_sdmmc_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_sdmmc_init(toInternal(id_))); }",
        ],
    },
    "sdm": {
        "file": "Sdm.hpp",
        "include": "sdm.hpp",
        "header_include": "bsp/interface/bsp_sdm.h",
        "id_enum": "SdmId",
        "class": "Sdm",
        "internal_id_type": "bsp_sdm_instance_t",
        "methods": [
            "Status init(std::uint8_t channel = 0U) const { return statusFromInternal(bsp_sdm_init(toInternal(id_), channel)); }",
            "Status status(std::uint32_t &value) const { return statusFromInternal(bsp_sdm_get_status(toInternal(id_), &value)); }",
        ],
    },
    "lcd": {
        "file": "Lcd.hpp",
        "include": "lcd.hpp",
        "header_include": "bsp/interface/bsp_lcd.h",
        "id_enum": "LcdId",
        "class": "Lcd",
        "internal_id_type": "bsp_lcd_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_lcd_init(toInternal(id_))); }",
        ],
    },
    "wifi": {
        "file": "Wifi.hpp",
        "include": "wifi.hpp",
        "header_include": "bsp/interface/bsp_wifi.h",
        "id_enum": "WifiId",
        "class": "Wifi",
        "internal_id_type": "bsp_wifi_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_wifi_init(toInternal(id_))); }",
        ],
    },
    "touch": {
        "file": "Touch.hpp",
        "include": "touch.hpp",
        "header_include": "bsp/interface/bsp_touch.h",
        "id_enum": "TouchId",
        "class": "Touch",
        "internal_id_type": "bsp_touch_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_touch_init(toInternal(id_))); }",
        ],
    },
    "i2s": {
        "file": "I2s.hpp",
        "include": "i2s.hpp",
        "header_include": "bsp/interface/bsp_i2s.h",
        "id_enum": "I2sId",
        "class": "I2s",
        "internal_id_type": "bsp_i2s_instance_t",
        "methods": [
            "Status init() const { return statusFromInternal(bsp_i2s_init(toInternal(id_))); }",
            "Status write(ByteView data) const { return statusFromInternal(bsp_i2s_write(toInternal(id_), data.data(), static_cast<std::uint32_t>(data.size()))); }",
            "Status read(ByteSpan data) const { return statusFromInternal(bsp_i2s_read(toInternal(id_), data.data(), static_cast<std::uint32_t>(data.size()))); }",
        ],
    },
}


def merged_module_spec(module_key: str, config: dict) -> dict:
    spec = dict(MODULES[module_key])
    overrides = config["modules"][module_key].get("generated", {})
    spec.update(overrides)
    return spec


def render_module_header(module_key: str, config: dict) -> str:
    spec = merged_module_spec(module_key, config)
    module_cfg = config["modules"][module_key]
    primary_include = spec["header_include"]
    includes = ["#include \"BoardIds.hpp\"", f"#include \"{primary_include}\""]
    for extra in spec.get("extra_includes", []):
        includes.append(f"#include {extra}")

    parts = [
        "// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.",
        "#pragma once",
        "",
        *includes,
        "",
    ]

    for module_enum in spec.get("module_enums", []):
        parts.append(module_enum)
        parts.append("")

    methods = list(spec["methods"])
    methods.extend(spec.get("append_methods", []))

    helpers = [switch_block(spec["id_enum"], spec["internal_id_type"], module_cfg["instances"])]
    helpers.extend(spec.get("extra_helpers", []))
    parts.append(class_block(spec["class"], spec["id_enum"], methods, helpers))
    parts.append("")
    return "\n".join(parts)


def render_board_ids_header(config: dict) -> str:
    includes = ["#include \"Common.hpp\""]
    for module_key in MODULE_ORDER:
        if module_key not in config.get("modules", {}):
            continue
        spec = merged_module_spec(module_key, config)
        include_line = f"#include \"{spec['header_include']}\""
        if include_line not in includes:
            includes.append(include_line)

    parts = [
        "// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.",
        "#pragma once",
        "",
        *includes,
        "",
    ]

    emitted_files: set[str] = set()
    for module_key in MODULE_ORDER:
        if module_key not in config.get("modules", {}):
            continue
        spec = merged_module_spec(module_key, config)
        if spec["file"] in emitted_files:
            continue
        emitted_files.add(spec["file"])
        module_cfg = config["modules"][module_key]
        parts.append(enum_block(spec["id_enum"], module_cfg["instances"]))
        parts.append("")

    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True, type=Path)
    parser.add_argument("--out-root", required=True, type=Path)
    args = parser.parse_args()

    config = json.loads(args.config.read_text(encoding="utf-8"))
    missing = [module for module in config.get("modules", {}) if module not in MODULES]
    if missing:
        raise SystemExit(f"Unsupported modules in config: {', '.join(sorted(missing))}")

    board = config["board"]
    out_root = args.out_root
    include_dir = out_root / "bsp" / "api"
    manifest_dir = out_root / "manifest"
    include_dir.mkdir(parents=True, exist_ok=True)
    manifest_dir.mkdir(parents=True, exist_ok=True)

    active_output_files = {
        merged_module_spec(module_key, config)["file"]
        for module_key in config.get("modules", {})
        if module_key in MODULES
    }
    for module_spec in MODULES.values():
        output_path = include_dir / module_spec["file"]
        if output_path.exists() and module_spec["file"] not in active_output_files:
            output_path.unlink()

    common_text = COMMON_HEADER
    board_ids_text = render_board_ids_header(config)
    (include_dir / "Common.hpp").write_text(common_text, encoding="utf-8")
    (include_dir / "BoardIds.hpp").write_text(board_ids_text, encoding="utf-8")
    for module_key in MODULE_ORDER:
        if module_key not in config.get("modules", {}):
            continue
        spec = merged_module_spec(module_key, config)
        module_text = render_module_header(module_key, config)
        (include_dir / spec["file"]).write_text(module_text, encoding="utf-8")

    (manifest_dir / f"{board}.json").write_text(
        json.dumps(config, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
