#ifndef BSP_CHIP_BOARD_CONFIG_H
#define BSP_CHIP_BOARD_CONFIG_H

#include "driver/gpio.h"
#include "driver/i2c.h"
#include "driver/spi_master.h"
#include "driver/uart.h"
#include "esp_adc/adc_oneshot.h"

#ifdef __cplusplus
extern "C" {
#endif

#define BSP_CHIP_ESP32S3

#define BSP_GPIO_LIST(X) \
    X(BSP_GPIO_LED, 0, 0, GPIO_NUM_2) \
    X(BSP_GPIO_KEY, 0, 0, GPIO_NUM_0)

#define BSP_UART_LIST(X) \
    X(BSP_UART_DEBUG, UART_NUM_0, 0, \
      BSP_UART_FEATURE_BLOCKING_TX | BSP_UART_FEATURE_CONFIGURABLE_BAUD | \
      BSP_UART_FEATURE_PARITY_NONE | BSP_UART_FEATURE_PARITY_ODD | BSP_UART_FEATURE_PARITY_EVEN | \
      BSP_UART_FEATURE_STOP_1 | BSP_UART_FEATURE_STOP_1_5 | BSP_UART_FEATURE_STOP_2 | \
      BSP_UART_FEATURE_WORD_7 | BSP_UART_FEATURE_WORD_8) \
    X(BSP_UART_APP, UART_NUM_1, 0, \
      BSP_UART_FEATURE_BLOCKING_TX | BSP_UART_FEATURE_CONFIGURABLE_BAUD | \
      BSP_UART_FEATURE_PARITY_NONE | BSP_UART_FEATURE_PARITY_ODD | BSP_UART_FEATURE_PARITY_EVEN | \
      BSP_UART_FEATURE_STOP_1 | BSP_UART_FEATURE_STOP_1_5 | BSP_UART_FEATURE_STOP_2 | \
      BSP_UART_FEATURE_WORD_7 | BSP_UART_FEATURE_WORD_8)

#define BSP_ADC16_LIST(X) \
    X(BSP_ADC16_MAIN, ADC_UNIT_1, 0, 0, ADC_CHANNEL_0, 0, 1, \
      BSP_ADC16_FEATURE_ONESHOT | BSP_ADC16_FEATURE_BLOCKING_READ)

#define BSP_GPTMR_FEATURE_PERIODIC   (1U << 0)
#define BSP_GPTMR_FEATURE_ONESHOT    (1U << 1)
#define BSP_GPTMR_FEATURE_CAPTURE    (1U << 2)
#define BSP_GPTMR_FEATURE_COMPARE    (1U << 3)

#define BSP_GPTMR_LIST(X) \
    X(BSP_GPTMR_TIMER, 0, 0, 0, 0, BSP_GPTMR_FEATURE_PERIODIC | BSP_GPTMR_FEATURE_ONESHOT | BSP_GPTMR_FEATURE_COMPARE, 1)

#define BSP_PWMV2_LIST(X) \
    X(BSP_PWMV2_MAIN, 0, 0, 0, 1)

#define BSP_PWM_LIST(X) \
    X(BSP_PWM_MAIN, BSP_PWM_BACKEND_ESP32_LEDC, 0, 0, 0, 0, 1, BSP_PWM_FEATURE_EDGE_ALIGNED)

#define BSP_SPI_LIST(X) \
    X(BSP_SPI_MAIN, SPI2_HOST, 0, 0, 1, \
      BSP_SPI_FEATURE_MASTER | BSP_SPI_FEATURE_BLOCKING | BSP_SPI_FEATURE_INTERRUPT | \
      BSP_SPI_FEATURE_DMA_TX | BSP_SPI_FEATURE_DMA_RX | BSP_SPI_FEATURE_FULL_DUPLEX | \
      BSP_SPI_FEATURE_TX_ONLY | BSP_SPI_FEATURE_RX_ONLY | BSP_SPI_FEATURE_CONFIGURABLE_CLOCK | \
      BSP_SPI_FEATURE_MSB_FIRST | BSP_SPI_FEATURE_LSB_FIRST)

#define BSP_I2C_LIST(X) \
    X(BSP_I2C_MAIN, I2C_NUM_0, 0, 0, 1, \
      BSP_I2C_FEATURE_MASTER | BSP_I2C_FEATURE_BLOCKING | BSP_I2C_FEATURE_CONFIGURABLE_CLOCK)

#define BSP_TSENS_LIST(X) \
    X(BSP_TSENS_MAIN)

#define BSP_USB_SERIAL_JTAG_LIST(X) \
    X(BSP_USB_SERIAL_JTAG_MAIN)

#define BSP_PCNT_LIST(X) \
    X(BSP_PCNT_MAIN, 0, 0)

#define BSP_RMT_LIST(X) \
    X(BSP_RMT_MAIN, 0, 0)

#define BSP_MCPWM_LIST(X) \
    X(BSP_MCPWM_MAIN, 0, 0)

#define BSP_SDSPI_LIST(X) \
    X(BSP_SDSPI_MAIN, SPI2_HOST, 0)

#define BSP_LCD_LIST(X) \
    X(BSP_LCD_MAIN, 0, 0)

#define BSP_WIFI_LIST(X) \
    X(BSP_WIFI_MAIN)

#define BSP_TOUCH_LIST(X) \
    X(BSP_TOUCH_MAIN, 0, 0)

#define BSP_I2S_LIST(X) \
    X(BSP_I2S_MAIN, 0, 0, 0U)

#define BSP_DAC_LIST(X) \
    X(BSP_DAC_MAIN, 0, 0, 0U)

#define BSP_ACMP_LIST(X) \
    X(BSP_ACMP0, 0, 0, 0U)

#define BSP_CAM_LIST(X) \
    X(BSP_CAM0, 0, 0U)

#define BSP_JPEG_LIST(X) \
    X(BSP_JPEG0, 0, 1U)

#define BSP_PARLIO_LIST(X) \
    X(BSP_PARLIO0, 0, 0U)

#define BSP_PPA_LIST(X) \
    X(BSP_PPA0, 0, 1U)

#define BSP_SDIO_LIST(X) \
    X(BSP_SDIO0, 0, 0U, 0U)

#define BSP_SDMMC_LIST(X) \
    X(BSP_SDMMC0, 0, 0U)

#define BSP_SDM_LIST(X) \
    X(BSP_SDM0, 0, 0, 0U)

#define BSP_UART_DEBUG_TX_PIN         GPIO_NUM_43
#define BSP_UART_DEBUG_RX_PIN         GPIO_NUM_44
#define BSP_UART_APP_TX_PIN           GPIO_NUM_17
#define BSP_UART_APP_RX_PIN           GPIO_NUM_18
#define BSP_UART_DEFAULT_BAUDRATE     (115200U)

#define BSP_SPI_MAIN_SCLK_PIN         GPIO_NUM_12
#define BSP_SPI_MAIN_MOSI_PIN         GPIO_NUM_11
#define BSP_SPI_MAIN_MISO_PIN         GPIO_NUM_13
#define BSP_SPI_MAIN_CLOCK_HZ         (10000000U)

#define BSP_I2C_MAIN_SCL_PIN          GPIO_NUM_9
#define BSP_I2C_MAIN_SDA_PIN          GPIO_NUM_8
#define BSP_I2C_MAIN_CLOCK_HZ         (400000U)

#define BSP_ADC16_MAIN_DEFAULT_CH     ADC_CHANNEL_0
#define BSP_ADC16_MAIN_ATTEN          ADC_ATTEN_DB_12
#define BSP_ADC16_MAIN_BITWIDTH       ADC_BITWIDTH_12

#define BSP_GPTMR_TIMER_RESOLUTION_HZ (1000000U)

#define BSP_PWMV2_MAIN_PIN            GPIO_NUM_2
#define BSP_PWMV2_MAIN_TIMER          LEDC_TIMER_0
#define BSP_PWMV2_MAIN_CHANNEL        LEDC_CHANNEL_0
#define BSP_PWMV2_MAIN_SPEED_MODE     LEDC_LOW_SPEED_MODE
#define BSP_PWMV2_MAIN_DUTY_BITS      LEDC_TIMER_10_BIT

#define BSP_PWM_MAIN_PIN              GPIO_NUM_2
#define BSP_PWM_MAIN_TIMER            LEDC_TIMER_0
#define BSP_PWM_MAIN_CHANNEL          LEDC_CHANNEL_0
#define BSP_PWM_MAIN_SPEED_MODE       LEDC_LOW_SPEED_MODE
#define BSP_PWM_MAIN_DUTY_BITS        LEDC_TIMER_10_BIT

#ifdef __cplusplus
}
#endif

#endif /* BSP_CHIP_BOARD_CONFIG_H */
