// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_adc16.h"

class Adc {
public:
    explicit constexpr Adc(AdcId id) : id_(id) {}
    Status init(AdcInitConfig config = {.resolution = BSP_ADC16_RESOLUTION_16_BITS, .clock_divider = BSP_ADC16_CLOCK_DIVIDER_4}) const { return statusFromInternal(bsp_adc16_init_ex(toInternal(id_), &config)); }
    Status clock(std::uint32_t &frequencyHz) const { return statusFromInternal(bsp_adc16_get_clock(toInternal(id_), &frequencyHz)); }
    Status read(std::uint16_t &value) const { return statusFromInternal(bsp_adc16_read_default(toInternal(id_), &value)); }
    Status read(std::uint8_t channel, std::uint16_t &value) const { return statusFromInternal(bsp_adc16_read_channel(toInternal(id_), channel, &value)); }
    Status configurePeriod(std::uint8_t channel, std::uint8_t prescalePow2, std::uint8_t periodCountMinus1) const { return statusFromInternal(bsp_adc16_configure_period(toInternal(id_), channel, prescalePow2, periodCountMinus1)); }
    Status configurePeriodHz(std::uint8_t channel, std::uint32_t sampleHz) const
    {
        if (sampleHz == 0U) {
            return Status::Param;
        }
        std::uint32_t adcClockHz = 0U;
        const auto clockStatus = clock(adcClockHz);
        if (clockStatus != Status::Ok) {
            return clockStatus;
        }
        std::uint8_t bestPrescalePow2 = 0U;
        std::uint8_t bestPeriodCountMinus1 = 0U;
        std::uint32_t bestErrorHz = 0xFFFFFFFFU;
        for (std::uint32_t prescalePow2 = 0U; prescalePow2 <= 31U; ++prescalePow2) {
            const std::uint64_t scale = (1ULL << prescalePow2);
            const std::uint64_t periodCounts = static_cast<std::uint64_t>(adcClockHz) / (static_cast<std::uint64_t>(sampleHz) * scale);
            if ((periodCounts == 0ULL) || (periodCounts > 256ULL)) {
                continue;
            }
            const std::uint32_t periodCountMinus1 = static_cast<std::uint32_t>(periodCounts - 1ULL);
            const std::uint64_t actualHz = static_cast<std::uint64_t>(adcClockHz) / (scale * static_cast<std::uint64_t>(periodCountMinus1 + 1U));
            const std::uint32_t errorHz = (actualHz > sampleHz)
                ? static_cast<std::uint32_t>(actualHz - sampleHz)
                : static_cast<std::uint32_t>(sampleHz - actualHz);
            if (errorHz < bestErrorHz) {
                bestErrorHz = errorHz;
                bestPrescalePow2 = static_cast<std::uint8_t>(prescalePow2);
                bestPeriodCountMinus1 = static_cast<std::uint8_t>(periodCountMinus1);
                if (errorHz == 0U) {
                    break;
                }
            }
        }
        if (bestErrorHz == 0xFFFFFFFFU) {
            return Status::Unsupported;
        }
        return configurePeriod(channel, bestPrescalePow2, bestPeriodCountMinus1);
    }
    Status readPeriod(std::uint8_t channel, std::uint16_t &value) const { return statusFromInternal(bsp_adc16_read_period(toInternal(id_), channel, &value)); }
    Status readAsync() const { return statusFromInternal(bsp_adc16_read_default_async(toInternal(id_))); }
    Status readAsync(std::uint8_t channel) const { return statusFromInternal(bsp_adc16_read_channel_async(toInternal(id_), channel)); }
    Status onSample(AdcSampleCallback callback, void *arg) const { return statusFromInternal(bsp_adc16_register_callback(toInternal(id_), callback, arg)); }
    Status routeSequenceTrigger(const AdcTriggerRoute &route) const { return statusFromInternal(bsp_adc16_set_sequence_trigger_route(toInternal(id_), &route)); }
    Status configureSequence(std::span<const std::uint8_t> channels, bool continuous = true, bool hardwareTrigger = false) const { return statusFromInternal(bsp_adc16_configure_sequence(toInternal(id_), channels.data(), static_cast<std::uint8_t>(channels.size()), stateFromBool(continuous), stateFromBool(hardwareTrigger))); }
    Status startSequence() const { return statusFromInternal(bsp_adc16_start_sequence(toInternal(id_))); }
    Status startSequenceDma(std::span<std::uint32_t> buffer, bool circular = true) const
    {
        const AdcDmaSequenceConfig config{.buffer = buffer.data(), .sample_count = static_cast<std::uint32_t>(buffer.size()), .circular = stateFromBool(circular)};
        return statusFromInternal(bsp_adc16_start_sequence_dma(toInternal(id_), &config));
    }
    Status onSequence(AdcSequenceCallback callback, void *arg) const { return statusFromInternal(bsp_adc16_register_sequence_callback(toInternal(id_), callback, arg)); }
    Status routePreemptionTrigger(const AdcTriggerRoute &route) const { return statusFromInternal(bsp_adc16_set_preemption_trigger_route(toInternal(id_), &route)); }
    Status configurePreemption(std::uint8_t triggerChannel, std::span<const std::uint8_t> channels, bool hardwareTrigger = false) const { return statusFromInternal(bsp_adc16_configure_preemption(toInternal(id_), triggerChannel, channels.data(), static_cast<std::uint8_t>(channels.size()), stateFromBool(hardwareTrigger))); }
    Status startPreemption() const { return statusFromInternal(bsp_adc16_start_preemption(toInternal(id_))); }
    Status onPreemption(AdcPreemptionCallback callback, void *arg) const { return statusFromInternal(bsp_adc16_register_preemption_callback(toInternal(id_), callback, arg)); }

private:
    static constexpr bsp_adc16_instance_t toInternal(AdcId id)
    {
        switch (id) {
        case AdcId::Main:
            return BSP_ADC16_MAIN;
        }
        return BSP_ADC16_MAIN;
    }

    AdcId id_;
};
