// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_acmp.h"

class AnaCmpr {
public:
    explicit constexpr AnaCmpr(AnaCmprId id) : id_(id) {}
    Status init(std::uint8_t channel = 0U) const { return statusFromInternal(bsp_acmp_init(toInternal(id_), channel)); }

private:
    static constexpr bsp_acmp_instance_t toInternal(AnaCmprId id)
    {
        switch (id) {
        case AnaCmprId::Main:
            return BSP_ACMP_MAIN;
        }
        return BSP_ACMP_MAIN;
    }

    AnaCmprId id_;
};
