// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "Common.hpp"
#include "bsp/interface/bsp_gpio.h"
#include "bsp/interface/bsp_gptmr.h"
#include "bsp/interface/bsp_pwm.h"
#include "bsp/interface/bsp_adc16.h"
#include "bsp/interface/bsp_trgm.h"
#include "bsp/interface/bsp_uart.h"
#include "bsp/interface/bsp_spi.h"
#include "bsp/interface/bsp_i2c.h"
#include "bsp/interface/bsp_mcan.h"
#include "bsp/interface/bsp_qeiv2.h"
#include "bsp/interface/bsp_qeov2.h"
#include "bsp/interface/bsp_dmav2.h"
#include "bsp/interface/bsp_crc.h"
#include "bsp/interface/bsp_ewdg.h"
#include "bsp/interface/bsp_rng.h"
#include "bsp/interface/bsp_rtc.h"
#include "bsp/interface/bsp_dac.h"
#include "bsp/interface/bsp_enet.h"
#include "bsp/interface/bsp_ecat.h"
#include "bsp/interface/bsp_mmc.h"
#include "bsp/interface/bsp_ospi.h"
#include "bsp/interface/bsp_qspi.h"
#include "bsp/interface/bsp_sai.h"
#include "bsp/interface/bsp_sd.h"
#include "bsp/interface/bsp_sdio.h"
#include "bsp/interface/bsp_tsns.h"
#include "bsp/interface/bsp_mchtmr.h"
#include "bsp/interface/bsp_mbx.h"
#include "bsp/interface/bsp_l1c.h"
#include "bsp/interface/bsp_eui.h"
#include "bsp/interface/bsp_owr.h"
#include "bsp/interface/bsp_lobs.h"
#include "bsp/interface/bsp_plic.h"
#include "bsp/interface/bsp_plb.h"
#include "bsp/interface/bsp_ppi.h"
#include "bsp/interface/bsp_ptpc.h"
#include "bsp/interface/bsp_synt.h"
#include "bsp/interface/bsp_pllctlv2.h"
#include "bsp/interface/bsp_ppor.h"
#include "bsp/interface/bsp_pdgo.h"
#include "bsp/interface/bsp_acmp.h"
#include "bsp/interface/bsp_sdm.h"
#include "bsp/interface/bsp_i2s.h"

enum class GpioId : std::uint8_t {
    Led,
    Led2,
    Led3,
    Led4,
    Key,
    LcdCs,
    LcdDc,
    LcdReset,
    LcdBacklight,
};

enum class TimerId : std::uint8_t {
    Main,
    Capture,
    Compare,
};

enum class PwmId : std::uint8_t {
    Main,
    Timer,
};

enum class AdcId : std::uint8_t {
    Main,
};

enum class TrgmId : std::uint8_t {
    Main,
};

enum class UartId : std::uint8_t {
    Debug,
    App,
};

enum class SpiId : std::uint8_t {
    Main,
};

enum class I2cId : std::uint8_t {
    Main,
};

enum class CanId : std::uint8_t {
    Main,
};

enum class EncoderId : std::uint8_t {
    Main,
};

enum class EncoderOutputId : std::uint8_t {
    Main,
};

enum class DmaId : std::uint8_t {
    Main,
};

enum class CrcId : std::uint8_t {
    Main,
};

enum class WatchdogId : std::uint8_t {
    Main,
};

enum class RngId : std::uint8_t {
    None,
};

enum class RtcId : std::uint8_t {
    None,
};

enum class DacId : std::uint8_t {
    None,
};

enum class EthId : std::uint8_t {
    Port0,
};

enum class EcatId : std::uint8_t {
    Port0,
};

enum class MmcId : std::uint8_t {
    None,
};

enum class OspiId : std::uint8_t {
    None,
};

enum class QspiId : std::uint8_t {
    None,
};

enum class SaiId : std::uint8_t {
    None,
};

enum class SdId : std::uint8_t {
    None,
};

enum class SdioId : std::uint8_t {
    None,
};

enum class TsnsId : std::uint8_t {
    Main,
};

enum class MchtmrId : std::uint8_t {
    Main,
};

enum class MailboxId : std::uint8_t {
    Local,
    Remote,
};

enum class CacheId : std::uint8_t {
    Main,
};

enum class EuiId : std::uint8_t {
    Main,
};

enum class OwrId : std::uint8_t {
    Main,
};

enum class LobsId : std::uint8_t {
    Main,
};

enum class PlicId : std::uint8_t {
    Main,
};

enum class PlbId : std::uint8_t {
    Main,
};

enum class PpiId : std::uint8_t {
    Main,
};

enum class PtpcId : std::uint8_t {
    Main,
};

enum class SyntId : std::uint8_t {
    Main,
};

enum class PllCtlId : std::uint8_t {
    Main,
};

enum class PporId : std::uint8_t {
    Main,
};

enum class PdgoId : std::uint8_t {
    Main,
};

enum class AnaCmprId : std::uint8_t {
    Main,
};

enum class SdmId : std::uint8_t {
    Main,
};

enum class I2sId : std::uint8_t {
    None,
};
