// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_l1c.h"

class Cache {
public:
    explicit constexpr Cache(CacheId id) : id_(id) {}
    Status status(bool &instructionEnabled, bool &dataEnabled) const { return statusFromInternal(bsp_l1c_get_status(toInternal(id_), &instructionEnabled, &dataEnabled)); }
    Status invalidateData() const { return statusFromInternal(bsp_l1c_invalidate_dcache_all(toInternal(id_))); }

private:
    static constexpr bsp_l1c_instance_t toInternal(CacheId id)
    {
        switch (id) {
        case CacheId::Main:
            return BSP_L1C_MAIN;
        }
        return BSP_L1C_MAIN;
    }

    CacheId id_;
};
