// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_mcan.h"
#include <cstring>

class Can {
public:
    explicit constexpr Can(CanId id) : id_(id) {}
    Status init(bool loopback = false) const { return statusFromInternal(bsp_mcan_init(toInternal(id_), loopback)); }
    Status defaultConfig(bsp_mcan_config_t &config, bool enableCanFd = false) const { return statusFromInternal(bsp_mcan_get_default_config(toInternal(id_), &config, enableCanFd)); }
    Status init(const bsp_mcan_config_t &config, std::uint8_t irqPriority = DefaultIrqPriority) const { return statusFromInternal(bsp_mcan_init_ex(toInternal(id_), &config, irqPriority)); }
    Status deinit() const { return statusFromInternal(bsp_mcan_deinit(toInternal(id_))); }
    Status write(const CanFrame &frame) const
    {
        if (frame.dlc > 8U) {
            return Status::Param;
        }
        const auto raw = toRawClassic(frame);
        return statusFromInternal(bsp_mcan_transmit(toInternal(id_), &raw));
    }
    Status read(CanFrame &frame) const
    {
        bsp_mcan_frame_t raw{};
        const auto status = statusFromInternal(bsp_mcan_receive(toInternal(id_), &raw));
        if (status != Status::Ok) {
            return status;
        }
        return fromRawClassic(raw, frame);
    }
    Status writeRaw(const bsp_mcan_frame_t &frame) const { return statusFromInternal(bsp_mcan_transmit(toInternal(id_), &frame)); }
    Status writeFifo(const bsp_mcan_frame_t &frame, std::uint32_t *fifoIndex = nullptr) const { return statusFromInternal(bsp_mcan_transmit_fifo(toInternal(id_), &frame, fifoIndex)); }
    Status writeBuffer(std::uint32_t bufferIndex, const bsp_mcan_frame_t &frame) const { return statusFromInternal(bsp_mcan_transmit_buffer(toInternal(id_), bufferIndex, &frame)); }
    Status readRaw(bsp_mcan_frame_t &frame) const { return statusFromInternal(bsp_mcan_receive(toInternal(id_), &frame)); }
    Status readFifo(std::uint32_t fifoIndex, bsp_mcan_frame_t &frame) const { return statusFromInternal(bsp_mcan_receive_fifo(toInternal(id_), fifoIndex, &frame)); }
    Status readBuffer(std::uint32_t bufferIndex, bsp_mcan_frame_t &frame) const { return statusFromInternal(bsp_mcan_receive_buffer(toInternal(id_), bufferIndex, &frame)); }
    Status loopback(const CanFrame &tx, CanFrame &rx) const
    {
        if (tx.dlc > 8U) {
            return Status::Param;
        }
        const auto rawTx = toRawClassic(tx);
        bsp_mcan_frame_t rawRx{};
        const auto status = statusFromInternal(bsp_mcan_loopback(toInternal(id_), &rawTx, &rawRx));
        if (status != Status::Ok) {
            return status;
        }
        return fromRawClassic(rawRx, rx);
    }
    Status loopbackRaw(const bsp_mcan_frame_t &tx, bsp_mcan_frame_t &rx) const
    {
        return statusFromInternal(bsp_mcan_loopback(toInternal(id_), &tx, &rx));
    }
    Status filters(const bsp_mcan_all_filters_config_t &config) const { return statusFromInternal(bsp_mcan_config_filters(toInternal(id_), &config)); }
    Status globalFilter(const bsp_mcan_global_filter_config_t &config) const { return statusFromInternal(bsp_mcan_set_global_filter(toInternal(id_), &config)); }
    Status protocolStatus(bsp_mcan_protocol_status_t &status) const { return statusFromInternal(bsp_mcan_get_protocol_status(toInternal(id_), &status)); }
    Status errorCount(bsp_mcan_error_count_t &count) const { return statusFromInternal(bsp_mcan_get_error_count(toInternal(id_), &count)); }
    Status readTxEvent(bsp_mcan_tx_event_fifo_elem_t &event) const { return statusFromInternal(bsp_mcan_read_tx_event(toInternal(id_), &event)); }
    Status rxTimestamp(const bsp_mcan_frame_t &frame, bsp_mcan_timestamp_value_t &timestamp) const { return statusFromInternal(bsp_mcan_get_timestamp_from_frame(toInternal(id_), &frame, &timestamp)); }
    Status txTimestamp(const bsp_mcan_tx_event_fifo_elem_t &event, bsp_mcan_timestamp_value_t &timestamp) const { return statusFromInternal(bsp_mcan_get_timestamp_from_tx_event(toInternal(id_), &event, &timestamp)); }
    Status cancel(std::uint32_t bufferIndex) const { return statusFromInternal(bsp_mcan_cancel_tx_request(toInternal(id_), bufferIndex)); }
    Status cancelled(std::uint32_t bufferIndex, bool &finished) const { return statusFromInternal(bsp_mcan_is_tx_request_cancelled(toInternal(id_), bufferIndex, &finished)); }
    Status onReceive(bsp_mcan_rx_callback_t callback, void *arg) const { return statusFromInternal(bsp_mcan_register_rx_callback(toInternal(id_), callback, arg)); }
    Status onTransmit(bsp_mcan_tx_callback_t callback, void *arg) const { return statusFromInternal(bsp_mcan_register_tx_callback(toInternal(id_), callback, arg)); }
    Status onEvent(bsp_mcan_event_callback_t callback, void *arg) const { return statusFromInternal(bsp_mcan_register_event_callback(toInternal(id_), callback, arg)); }
    static std::uint8_t payloadSize(std::uint8_t dlc) { return mcan_get_message_size_from_dlc(dlc); }
    Status clock(std::uint32_t &frequencyHz) const { return statusFromInternal(bsp_mcan_get_clock(toInternal(id_), &frequencyHz)); }
    Status configureBitrate(bsp_mcan_config_t &config, std::uint32_t nominalBitrate, std::uint32_t dataBitrate = 0U) const { return statusFromInternal(bsp_mcan_config_bitrate(toInternal(id_), &config, nominalBitrate, dataBitrate)); }
    Status initBitrate(std::uint32_t nominalBitrate, bool loopback = false, std::uint8_t irqPriority = DefaultIrqPriority) const
    {
        bsp_mcan_config_t config{};
        const auto configStatus = defaultConfig(config, false);
        if (configStatus != Status::Ok) {
            return configStatus;
        }
        config.mode = loopback ? mcan_mode_loopback_internal : mcan_mode_normal;
        const auto bitrateStatus = configureBitrate(config, nominalBitrate, 0U);
        if (bitrateStatus != Status::Ok) {
            return bitrateStatus;
        }
        return init(config, irqPriority);
    }
    Status initFd(bool bitrateSwitch = true, bool loopback = false, std::uint8_t irqPriority = DefaultIrqPriority) const
    {
        (void) bitrateSwitch;
        bsp_mcan_config_t config{};
        const auto configStatus = defaultConfig(config, true);
        if (configStatus != Status::Ok) {
            return configStatus;
        }
        config.mode = loopback ? mcan_mode_loopback_internal : mcan_mode_normal;
        return init(config, irqPriority);
    }
    Status initFdBitrate(std::uint32_t nominalBitrate, std::uint32_t dataBitrate, bool bitrateSwitch = true, bool loopback = false, std::uint8_t irqPriority = DefaultIrqPriority) const
    {
        (void) bitrateSwitch;
        bsp_mcan_config_t config{};
        const auto configStatus = defaultConfig(config, true);
        if (configStatus != Status::Ok) {
            return configStatus;
        }
        config.mode = loopback ? mcan_mode_loopback_internal : mcan_mode_normal;
        const auto bitrateStatus = configureBitrate(config, nominalBitrate, dataBitrate);
        if (bitrateStatus != Status::Ok) {
            return bitrateStatus;
        }
        return init(config, irqPriority);
    }

private:
    static constexpr bsp_mcan_instance_t toInternal(CanId id)
    {
        switch (id) {
        case CanId::Main:
            return BSP_MCAN_MAIN;
        }
        return BSP_MCAN_MAIN;
    }

    static inline bsp_mcan_frame_t toRawClassic(const CanFrame &frame)
    {
        bsp_mcan_frame_t raw{};
        raw.id = frame.id;
        raw.dlc = frame.dlc;
        raw.extended_id = frame.extendedId;
        std::memcpy(raw.data, frame.data.data(), frame.data.size());
        return raw;
    }

    static inline Status fromRawClassic(const bsp_mcan_frame_t &frame, CanFrame &publicFrame)
    {
        const auto bytes = mcan_get_message_size_from_dlc(frame.dlc);
        if (frame.fd_frame || frame.remote_frame || (bytes > publicFrame.data.size())) {
            return Status::Unsupported;
        }
        publicFrame = {};
        publicFrame.id = frame.id;
        publicFrame.dlc = frame.dlc;
        publicFrame.extendedId = frame.extended_id;
        if (bytes > 0U) {
            std::memcpy(publicFrame.data.data(), frame.data, bytes);
        }
        return Status::Ok;
    }

    CanId id_;
};
