// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include <array>
#include <cstdint>
#include <span>
#include <string_view>

#include "bsp/interface/bsp_common.h"
#include "bsp/interface/bsp_adc16.h"
#include "bsp/interface/bsp_enet.h"
#include "bsp/interface/bsp_gpio.h"
#include "bsp/interface/bsp_i2c.h"
#include "bsp/interface/bsp_pwm.h"
#include "bsp/interface/bsp_spi.h"
#include "bsp/interface/bsp_timer_common.h"
#include "bsp/interface/bsp_trgm.h"
#include "bsp/interface/bsp_uart.h"

enum class Status : std::int32_t {
    Ok = 0,
    Error = -1,
    Param = -2,
    Timeout = -3,
    Busy = -4,
    Unsupported = -5,
};

enum class Level : std::uint8_t {
    Low = 0,
    High = 1,
};

enum class GpioPull : std::uint8_t {
    None = 0,
    Up = 1,
    Down = 2,
};

enum class GpioOutputType : std::uint8_t {
    PushPull = 0,
    OpenDrain = 1,
};

enum class GpioMode : std::uint8_t {
    Input = 0,
    Output = 1,
    InterruptRising = 2,
    InterruptFalling = 3,
    InterruptBoth = 4,
};

enum class SpiMode : std::uint8_t {
    Mode0 = 0,
    Mode1 = 1,
    Mode2 = 2,
    Mode3 = 3,
};

enum class SpiBitOrder : std::uint8_t {
    MsbFirst = 0,
    LsbFirst = 1,
};

enum class SpiEvent : std::uint8_t {
    Write = 0,
    Read = 1,
    Transfer = 2,
};

enum class I2cEvent : std::uint8_t {
    Write = 0,
    Read = 1,
};

enum class TimerEvent : std::uint8_t {
    Elapsed = 0,
    Capture = 1,
    Compare = 2,
};

enum class PwmEvent : std::uint32_t {
    Reload = 1U << 0,
    Compare = 1U << 1,
    Fault = 1U << 2,
};

enum class UartParity : std::uint8_t {
    None = 0,
    Odd = 1,
    Even = 2,
    Always1 = 3,
    Always0 = 4,
};

enum class UartStopBits : std::uint8_t {
    One = 0,
    OneAndHalf = 1,
    Two = 2,
};

enum class UartWordLength : std::uint8_t {
    Bits5 = 0,
    Bits6 = 1,
    Bits7 = 2,
    Bits8 = 3,
};

enum class UartEvent : std::uint8_t {
    RxReady = 0,
    RxDone = 1,
    RxHalf = 2,
    RxIdle = 3,
    RxTimeout = 4,
    TxDone = 5,
    TxHalf = 6,
    Error = 7,
};

enum class TransferMode : std::uint8_t {
    Auto = 0,
    Blocking = 1,
    Interrupt = 2,
    Dma = 3,
};

using ByteView = std::span<const std::uint8_t>;
using ByteSpan = std::span<std::uint8_t>;
using AdcSample = bsp_adc16_sample_t;
using AdcTriggerRoute = bsp_adc16_trigger_route_t;
using AdcTriggerOutput = bsp_adc16_trigger_output_t;
using AdcResolution = bsp_adc16_resolution_t;
using AdcClockDivider = bsp_adc16_clock_divider_t;
using AdcInitConfig = bsp_adc16_init_config_t;
using AdcDmaSequenceConfig = bsp_adc16_dma_sequence_config_t;
using TrgmOutputRoute = bsp_trgm_output_route_t;
using TrgmOutputType = bsp_trgm_output_type_t;
using AdcSampleCallback = bsp_adc16_callback_t;
using AdcSequenceCallback = bsp_adc16_sequence_callback_t;
using AdcPreemptionCallback = bsp_adc16_preemption_callback_t;
using TimerEventCallback = bsp_timer_event_callback_t;
using PwmEventCallback = bsp_pwm_event_callback_t;
using SpiEventCallback = void(*)(bsp_spi_event_t event, std::int32_t status, void *arg);
using I2cEventCallback = void(*)(bsp_i2c_event_t event, std::int32_t status, void *arg);
using UartEventCallback = void(*)(bsp_uart_event_t event, std::uint8_t *data, std::uint16_t len, std::int32_t status, void *arg);
inline constexpr std::uint8_t DefaultIrqPriority = static_cast<std::uint8_t>(BSP_IRQ_PRIORITY_DEFAULT);

enum class MdioOwner : std::uint8_t {
    Enet = 0,
    Esc = 1,
};

enum class EthSpeed : std::uint8_t {
    Speed10M = 0,
    Speed100M = 1,
    Speed1000M = 2,
    Unknown = 3,
};

enum class EthDuplex : std::uint8_t {
    Half = 0,
    Full = 1,
    Unknown = 2,
};

struct EthLinkState {
    bool linkUp = false;
    EthSpeed speed = EthSpeed::Unknown;
    EthDuplex duplex = EthDuplex::Unknown;
};

struct CanFrame {
    std::uint32_t id = 0;
    std::uint8_t dlc = 0;
    bool extendedId = false;
    bool remoteFrame = false;
    bool fdFrame = false;
    bool bitrateSwitch = false;
    bool errorStateIndicator = false;
    std::array<std::uint8_t, 64> data{};
};

inline constexpr Status statusFromInternal(int status)
{
    switch (status) {
    case BSP_OK:
        return Status::Ok;
    case BSP_ERROR:
        return Status::Error;
    case BSP_ERROR_PARAM:
        return Status::Param;
    case BSP_ERROR_TIMEOUT:
        return Status::Timeout;
    case BSP_ERROR_BUSY:
        return Status::Busy;
    case BSP_ERROR_UNSUPPORTED:
        return Status::Unsupported;
    default:
        return Status::Error;
    }
}

inline constexpr bsp_level_t levelToInternal(Level level)
{
    return (level == Level::High) ? BSP_LEVEL_HIGH : BSP_LEVEL_LOW;
}

inline constexpr bsp_state_t stateFromBool(bool enabled)
{
    return enabled ? BSP_ENABLE : BSP_DISABLE;
}

inline constexpr bsp_gpio_pull_t gpioPullToInternal(GpioPull pull)
{
    switch (pull) {
    case GpioPull::Up:
        return BSP_GPIO_PULL_UP;
    case GpioPull::Down:
        return BSP_GPIO_PULL_DOWN;
    case GpioPull::None:
    default:
        return BSP_GPIO_PULL_NONE;
    }
}

inline constexpr bsp_gpio_output_type_t gpioOutputTypeToInternal(GpioOutputType type)
{
    return (type == GpioOutputType::OpenDrain) ? BSP_GPIO_OUTPUT_OPEN_DRAIN : BSP_GPIO_OUTPUT_PUSH_PULL;
}

inline constexpr bsp_gpio_mode_t gpioModeToInternal(GpioMode mode)
{
    switch (mode) {
    case GpioMode::Input:
        return BSP_GPIO_MODE_INPUT;
    case GpioMode::InterruptRising:
        return BSP_GPIO_MODE_IT_RISING;
    case GpioMode::InterruptFalling:
        return BSP_GPIO_MODE_IT_FALLING;
    case GpioMode::InterruptBoth:
        return BSP_GPIO_MODE_IT_BOTH;
    case GpioMode::Output:
    default:
        return BSP_GPIO_MODE_OUTPUT;
    }
}

inline constexpr bsp_spi_mode_t spiModeToInternal(SpiMode mode)
{
    switch (mode) {
    case SpiMode::Mode0:
        return BSP_SPI_MODE_0;
    case SpiMode::Mode1:
        return BSP_SPI_MODE_1;
    case SpiMode::Mode2:
        return BSP_SPI_MODE_2;
    case SpiMode::Mode3:
    default:
        return BSP_SPI_MODE_3;
    }
}

inline constexpr bsp_spi_bit_order_t spiBitOrderToInternal(SpiBitOrder order)
{
    return (order == SpiBitOrder::LsbFirst) ? BSP_SPI_BIT_ORDER_LSB_FIRST : BSP_SPI_BIT_ORDER_MSB_FIRST;
}

inline constexpr bsp_uart_parity_t uartParityToInternal(UartParity parity)
{
    switch (parity) {
    case UartParity::Odd:
        return BSP_UART_PARITY_ODD;
    case UartParity::Even:
        return BSP_UART_PARITY_EVEN;
    case UartParity::Always1:
        return BSP_UART_PARITY_ALWAYS_1;
    case UartParity::Always0:
        return BSP_UART_PARITY_ALWAYS_0;
    case UartParity::None:
    default:
        return BSP_UART_PARITY_NONE;
    }
}

inline constexpr bsp_uart_stop_bits_t uartStopBitsToInternal(UartStopBits stopBits)
{
    switch (stopBits) {
    case UartStopBits::OneAndHalf:
        return BSP_UART_STOP_BITS_1_5;
    case UartStopBits::Two:
        return BSP_UART_STOP_BITS_2;
    case UartStopBits::One:
    default:
        return BSP_UART_STOP_BITS_1;
    }
}

inline constexpr bsp_uart_word_length_t uartWordLengthToInternal(UartWordLength wordLength)
{
    switch (wordLength) {
    case UartWordLength::Bits5:
        return BSP_UART_WORD_LENGTH_5;
    case UartWordLength::Bits6:
        return BSP_UART_WORD_LENGTH_6;
    case UartWordLength::Bits7:
        return BSP_UART_WORD_LENGTH_7;
    case UartWordLength::Bits8:
    default:
        return BSP_UART_WORD_LENGTH_8;
    }
}

inline constexpr bsp_transfer_mode_t transferModeToInternal(TransferMode transferMode)
{
    switch (transferMode) {
    case TransferMode::Blocking:
        return BSP_TRANSFER_MODE_BLOCKING;
    case TransferMode::Interrupt:
        return BSP_TRANSFER_MODE_INTERRUPT;
    case TransferMode::Dma:
        return BSP_TRANSFER_MODE_DMA;
    case TransferMode::Auto:
    default:
        return BSP_TRANSFER_MODE_AUTO;
    }
}

inline constexpr bsp_mdio_owner_t mdioOwnerToInternal(MdioOwner owner)
{
    return (owner == MdioOwner::Esc) ? BSP_MDIO_OWNER_ESC : BSP_MDIO_OWNER_ENET;
}
