// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_crc.h"

class Crc {
public:
    explicit constexpr Crc(CrcId id) : id_(id) {}
    Status calculate(ByteView data, std::uint32_t &crc) const { return statusFromInternal(bsp_crc32_calculate(toInternal(id_), data.data(), static_cast<std::uint32_t>(data.size()), &crc)); }

private:
    static constexpr bsp_crc_instance_t toInternal(CrcId id)
    {
        switch (id) {
        case CrcId::Main:
            return BSP_CRC_MAIN;
        }
        return BSP_CRC_MAIN;
    }

    CrcId id_;
};
