// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_dac.h"

class Dac {
public:
    explicit constexpr Dac(DacId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_dac_init(toInternal(id_))); }
    Status write(std::uint8_t channel, std::uint32_t value) const { return statusFromInternal(bsp_dac_write(toInternal(id_), channel, value)); }

private:
    static constexpr bsp_dac_instance_t toInternal(DacId id)
    {
        switch (id) {
        case DacId::None:
            return BSP_DAC_NONE;
        }
        return BSP_DAC_NONE;
    }

    DacId id_;
};
