// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_dmav2.h"

class Dma {
public:
    explicit constexpr Dma(DmaId id) : id_(id) {}
    Status copy(ByteSpan destination, ByteView source) const
    {
        if (destination.size() != source.size()) {
            return Status::Param;
        }
        return statusFromInternal(bsp_dmav2_memcpy(toInternal(id_), destination.data(), source.data(), static_cast<std::uint32_t>(source.size())));
    }
    Status copyAsync(ByteSpan destination, ByteView source) const
    {
        if (destination.size() != source.size()) {
            return Status::Param;
        }
        return statusFromInternal(bsp_dmav2_memcpy_async(toInternal(id_), destination.data(), source.data(), static_cast<std::uint32_t>(source.size())));
    }
    Status onComplete(bsp_dmav2_callback_t callback, void *arg) const { return statusFromInternal(bsp_dmav2_register_callback(toInternal(id_), callback, arg)); }

private:
    static constexpr bsp_dmav2_instance_t toInternal(DmaId id)
    {
        switch (id) {
        case DmaId::Main:
            return BSP_DMAV2_MAIN;
        }
        return BSP_DMAV2_MAIN;
    }

    DmaId id_;
};
