// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_ecat.h"

class Ecat {
public:
    explicit constexpr Ecat(EcatId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_ecat_init(toInternal(id_))); }
    std::uintptr_t baseAddress() const { return bsp_ecat_get_base_address(toInternal(id_)); }
    Status initSwitchLed() const { return statusFromInternal(bsp_ecat_init_switch_led(toInternal(id_))); }
    Status initEepromPins() const { return statusFromInternal(bsp_ecat_init_eeprom_pins(toInternal(id_))); }
    Status initEepromI2cPins() const { return statusFromInternal(bsp_ecat_init_eeprom_as_i2c_pins(toInternal(id_))); }
    Status selectMdioOwner(MdioOwner owner) const { return statusFromInternal(bsp_ecat_set_mdio_owner(mdioOwnerToInternal(owner))); }
    Status coreClock(bool enable) const { return statusFromInternal(bsp_ecat_set_core_clock(toInternal(id_), enable)); }
    Status phyClock(bool enable) const { return statusFromInternal(bsp_ecat_set_phy_clock(toInternal(id_), enable)); }
    Status eepromClockConfig(const bsp_ecat_eeprom_clock_config_t &config) const { return statusFromInternal(bsp_ecat_config_eeprom_clock(toInternal(id_), &config)); }
    Status ctrlSignal(std::uint8_t index, bsp_ecat_ctrl_signal_function_t function, bool invert = false) const { return statusFromInternal(bsp_ecat_config_ctrl_signal(toInternal(id_), index, function, invert)); }
    Status nmiiLinkSource(bool link0FromIo, bool link1FromIo, bool link2FromIo) const { return statusFromInternal(bsp_ecat_config_nmii_link_source(toInternal(id_), link0FromIo, link1FromIo, link2FromIo)); }
    Status resetSource(bool resetFromEcatCore) const { return statusFromInternal(bsp_ecat_config_reset_source(toInternal(id_), resetFromEcatCore)); }
    Status pdiReset() const { return statusFromInternal(bsp_ecat_pdi_reset(toInternal(id_))); }
    Status phyOffset(std::uint8_t offset) const { return statusFromInternal(bsp_ecat_set_phy_offset(toInternal(id_), offset)); }
    Status mdioRead(std::uint8_t phyAddr, std::uint8_t regAddr, std::uint16_t &data) const { return statusFromInternal(bsp_ecat_mdio_read(toInternal(id_), phyAddr, regAddr, &data)); }
    Status mdioWrite(std::uint8_t phyAddr, std::uint8_t regAddr, std::uint16_t data) const { return statusFromInternal(bsp_ecat_mdio_write(toInternal(id_), phyAddr, regAddr, data)); }
    Status eepromLoading() const { return statusFromInternal(bsp_ecat_check_eeprom_loading(toInternal(id_))); }
    Status enableIrq(bsp_ecat_irq_mask_t mask) const { return statusFromInternal(bsp_ecat_enable_irq(toInternal(id_), mask)); }
    Status disableIrq(bsp_ecat_irq_mask_t mask) const { return statusFromInternal(bsp_ecat_disable_irq(toInternal(id_), mask)); }
    Status eepromCommand(bsp_ecat_eeprom_command_t &cmd) const { return statusFromInternal(bsp_ecat_get_eeprom_command(toInternal(id_), &cmd)); }
    Status eepromByteAddress(std::uint32_t &address) const { return statusFromInternal(bsp_ecat_get_eeprom_byte_address(toInternal(id_), &address)); }
    Status eepromWordAddress(std::uint32_t &address) const { return statusFromInternal(bsp_ecat_get_eeprom_word_address(toInternal(id_), &address)); }
    Status eepromData(std::uint64_t &data) const { return statusFromInternal(bsp_ecat_read_eeprom_data(toInternal(id_), &data)); }
    Status writeEepromData(std::uint64_t data) const { return statusFromInternal(bsp_ecat_write_eeprom_data(toInternal(id_), data)); }
    Status ackEepromEmulation(bsp_ecat_eeprom_command_t cmd, bool ackError = false, bool crcError = false) const { return statusFromInternal(bsp_ecat_ack_eeprom_emulation(toInternal(id_), cmd, ackError, crcError)); }

private:
    static constexpr bsp_ecat_port_t toInternal(EcatId id)
    {
        switch (id) {
        case EcatId::Port0:
            return BSP_ECAT_PORT0;
        }
        return BSP_ECAT_PORT0;
    }

    EcatId id_;
};
