// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_qeiv2.h"

class Encoder {
public:
    explicit constexpr Encoder(EncoderId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_qeiv2_init(toInternal(id_))); }
    Status position(std::uint32_t &value) const { return statusFromInternal(bsp_qeiv2_get_position(toInternal(id_), &value)); }
    Status angle(std::uint32_t &value) const { return statusFromInternal(bsp_qeiv2_get_angle(toInternal(id_), &value)); }
    Status phaseCount(std::uint32_t &value) const { return statusFromInternal(bsp_qeiv2_get_phase_count(toInternal(id_), &value)); }
    Status speed(std::uint32_t &value) const { return statusFromInternal(bsp_qeiv2_get_speed(toInternal(id_), &value)); }

private:
    static constexpr bsp_qeiv2_instance_t toInternal(EncoderId id)
    {
        switch (id) {
        case EncoderId::Main:
            return BSP_QEIV2_MAIN;
        }
        return BSP_QEIV2_MAIN;
    }

    EncoderId id_;
};
