// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_qeov2.h"

class EncoderOutput {
public:
    explicit constexpr EncoderOutput(EncoderOutputId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_qeov2_init(toInternal(id_))); }
    Status start() const { return statusFromInternal(bsp_qeov2_start(toInternal(id_))); }
    Status stop() const { return statusFromInternal(bsp_qeov2_stop(toInternal(id_))); }

private:
    static constexpr bsp_qeov2_instance_t toInternal(EncoderOutputId id)
    {
        switch (id) {
        case EncoderOutputId::Main:
            return BSP_QEOV2_MAIN;
        }
        return BSP_QEOV2_MAIN;
    }

    EncoderOutputId id_;
};
