// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_enet.h"

class Eth {
public:
    explicit constexpr Eth(EthId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_enet_init(toInternal(id_))); }
    std::uintptr_t baseAddress() const { return bsp_enet_get_base_address(toInternal(id_)); }
    Status initPins() const { return statusFromInternal(bsp_enet_init_pins(toInternal(id_))); }
    Status resetPhy() const { return statusFromInternal(bsp_enet_reset_phy(toInternal(id_))); }
    Status initRgmiiClockDelay() const { return statusFromInternal(bsp_enet_init_rgmii_clock_delay(toInternal(id_))); }
    Status initRmiiReferenceClock(bool internal) const { return statusFromInternal(bsp_enet_init_rmii_reference_clock(toInternal(id_), internal)); }
    Status initMiiClock() const { return statusFromInternal(bsp_enet_init_mii_clock(toInternal(id_))); }
    Status initPtpClock() const { return statusFromInternal(bsp_enet_init_ptp_clock(toInternal(id_))); }
    Status enableIrq() const { return statusFromInternal(bsp_enet_enable_irq(toInternal(id_))); }
    Status disableIrq() const { return statusFromInternal(bsp_enet_disable_irq(toInternal(id_))); }
    Status dmaPbl(std::uint8_t &pbl) const { return statusFromInternal(bsp_enet_get_dma_pbl(toInternal(id_), &pbl)); }
    Status readPhy(std::uint32_t phyAddr, std::uint32_t regAddr, std::uint16_t &value) const { return statusFromInternal(bsp_enet_read_phy(toInternal(id_), phyAddr, regAddr, &value)); }
    Status writePhy(std::uint32_t phyAddr, std::uint32_t regAddr, std::uint16_t value) const { return statusFromInternal(bsp_enet_write_phy(toInternal(id_), phyAddr, regAddr, value)); }
    Status selectMdioOwner(MdioOwner owner) const { return statusFromInternal(bsp_enet_set_mdio_owner(mdioOwnerToInternal(owner))); }
    Status linkState(EthLinkState &state) const
    {
        bsp_enet_link_state_t internal{};
        const auto status = statusFromInternal(bsp_enet_get_link_state(toInternal(id_), &internal));
        if (status == Status::Ok) {
            state.linkUp = (internal.link_up == BSP_ENABLE);
            switch (internal.speed) {
            case BSP_ENET_SPEED_10M:
                state.speed = EthSpeed::Speed10M;
                break;
            case BSP_ENET_SPEED_100M:
                state.speed = EthSpeed::Speed100M;
                break;
            case BSP_ENET_SPEED_1000M:
                state.speed = EthSpeed::Speed1000M;
                break;
            default:
                state.speed = EthSpeed::Unknown;
                break;
            }
            switch (internal.duplex) {
            case BSP_ENET_DUPLEX_HALF:
                state.duplex = EthDuplex::Half;
                break;
            case BSP_ENET_DUPLEX_FULL:
                state.duplex = EthDuplex::Full;
                break;
            default:
                state.duplex = EthDuplex::Unknown;
                break;
            }
        }
        return status;
    }
    Status defaultTxControl(bsp_enet_tx_control_config_t &config) const { return statusFromInternal(bsp_enet_get_default_tx_control(toInternal(id_), &config)); }
    Status defaultInterruptConfig(bsp_enet_interrupt_config_t &config) const { return statusFromInternal(bsp_enet_get_default_interrupt_config(toInternal(id_), &config)); }
    Status controllerInit(bsp_enet_interface_t infType, bsp_enet_desc_t &desc, bsp_enet_mac_config_t &macConfig, bsp_enet_interrupt_config_t *interruptConfig = nullptr) const { return statusFromInternal(bsp_enet_controller_init(toInternal(id_), infType, &desc, &macConfig, interruptConfig)); }
    Status lineSpeed(bsp_enet_speed_t speed) const { return statusFromInternal(bsp_enet_set_line_speed(toInternal(id_), speed)); }
    Status duplexMode(bsp_enet_duplex_t mode) const { return statusFromInternal(bsp_enet_set_duplex_mode(toInternal(id_), mode)); }
    Status rxResume() const { return statusFromInternal(bsp_enet_rx_resume(toInternal(id_))); }
    Status txDescChainInit(bsp_enet_desc_t &desc) const { return statusFromInternal(bsp_enet_tx_desc_chain_init(toInternal(id_), &desc)); }
    Status rxDescChainInit(bsp_enet_desc_t &desc) const { return statusFromInternal(bsp_enet_rx_desc_chain_init(toInternal(id_), &desc)); }
    Status dmaFlush() const { return statusFromInternal(bsp_enet_dma_flush(toInternal(id_))); }
    Status interruptStatus(std::uint32_t &status) const { return statusFromInternal(bsp_enet_get_interrupt_status(toInternal(id_), &status)); }
    Status maskInterruptEvent(std::uint32_t mask) const { return statusFromInternal(bsp_enet_mask_interrupt_event(toInternal(id_), mask)); }
    Status unmaskInterruptEvent(std::uint32_t mask) const { return statusFromInternal(bsp_enet_unmask_interrupt_event(toInternal(id_), mask)); }
    Status hasReceivedFrame(bsp_enet_rx_desc_t *&current, bsp_enet_rx_frame_info_t &info, bool &available) const
    {
        bsp_state_t internal = BSP_DISABLE;
        const auto status = statusFromInternal(bsp_enet_check_received_frame(&current, &info, &internal));
        if (status == Status::Ok) {
            available = (internal == BSP_ENABLE);
        }
        return status;
    }
    Status receivedFrame(bsp_enet_rx_desc_t *&current, bsp_enet_rx_frame_info_t &info, bsp_enet_frame_t &frame) const { return statusFromInternal(bsp_enet_get_received_frame(&current, &info, &frame)); }
    Status receivedFrameInterrupt(bsp_enet_rx_desc_t *&current, bsp_enet_rx_frame_info_t &info, std::uint32_t rxDescCount, bsp_enet_frame_t &frame) const { return statusFromInternal(bsp_enet_get_received_frame_interrupt(&current, &info, rxDescCount, &frame)); }
    Status prepareTxDesc(bsp_enet_tx_desc_t *&current, const bsp_enet_tx_control_config_t &config, std::uint16_t frameLength, std::uint16_t txBufferSize, bool &prepared) const
    {
        bsp_state_t internal = BSP_DISABLE;
        const auto status = statusFromInternal(bsp_enet_prepare_tx_desc(toInternal(id_), &current, &config, frameLength, txBufferSize, &internal));
        if (status == Status::Ok) {
            prepared = (internal == BSP_ENABLE);
        }
        return status;
    }
    Status prepareTxDescWithTimestamp(bsp_enet_tx_desc_t *&current, const bsp_enet_tx_control_config_t &config, std::uint16_t frameLength, std::uint16_t txBufferSize, bsp_enet_ptp_timestamp_t &timestamp, bool &prepared) const
    {
        bsp_state_t internal = BSP_DISABLE;
        const auto status = statusFromInternal(bsp_enet_prepare_tx_desc_with_timestamp(toInternal(id_), &current, &config, frameLength, txBufferSize, &timestamp, &internal));
        if (status == Status::Ok) {
            prepared = (internal == BSP_ENABLE);
        }
        return status;
    }
    Status defaultPtpConfig(std::uint32_t ptpClockHz, bsp_enet_ptp_config_t &config) const { return statusFromInternal(bsp_enet_get_default_ptp_config(toInternal(id_), ptpClockHz, &config)); }
    Status initPtp(const bsp_enet_ptp_config_t &config) const { return statusFromInternal(bsp_enet_init_ptp(toInternal(id_), &config)); }
    Status setPtpTimestamp(const bsp_enet_ptp_timestamp_update_t &timestamp) const { return statusFromInternal(bsp_enet_set_ptp_timestamp(toInternal(id_), &timestamp)); }
    Status ptpTimestamp(bsp_enet_ptp_timestamp_t &timestamp) const { return statusFromInternal(bsp_enet_get_ptp_timestamp(toInternal(id_), &timestamp)); }
    Status updatePtpTimeoffset(const bsp_enet_ptp_timestamp_update_t &timeoffset) const { return statusFromInternal(bsp_enet_update_ptp_timeoffset(toInternal(id_), &timeoffset)); }
    Status adjustPtpTimeFreq(std::int32_t adjustment) const { return statusFromInternal(bsp_enet_adjust_ptp_time_freq(toInternal(id_), adjustment)); }
    Status ptpVersion(bsp_enet_ptp_version_t version) const { return statusFromInternal(bsp_enet_set_ptp_version(toInternal(id_), version)); }
    Status enablePtpFrameType(bsp_enet_ptp_frame_type_t frameType, bool enable) const { return statusFromInternal(bsp_enet_enable_ptp_frame_type(toInternal(id_), frameType, enable)); }
    Status snapshotPtpMessageType(bsp_enet_ptp_message_type_t messageType) const { return statusFromInternal(bsp_enet_set_snapshot_ptp_message_type(toInternal(id_), messageType)); }
    Status pps0ControlOutput(bsp_enet_pps_control_t control) const { return statusFromInternal(bsp_enet_set_pps_control_output(toInternal(id_), control)); }
    Status ppsCommand(bsp_enet_pps_command_t cmd, bsp_enet_pps_index_t index = BSP_ENET_PPS_INDEX0) const { return statusFromInternal(bsp_enet_set_pps_command(toInternal(id_), cmd, index)); }
    Status ppsConfig(const bsp_enet_pps_config_t &config, bsp_enet_pps_index_t index = BSP_ENET_PPS_INDEX0) const { return statusFromInternal(bsp_enet_set_pps_config(toInternal(id_), &config, index)); }
    Status enableAuxSnapshot(bsp_enet_aux_snapshot_trigger_t index) const { return statusFromInternal(bsp_enet_enable_aux_snapshot(toInternal(id_), index)); }
    Status disableAuxSnapshot(bsp_enet_aux_snapshot_trigger_t index) const { return statusFromInternal(bsp_enet_disable_aux_snapshot(toInternal(id_), index)); }
    Status auxTimestamp(bsp_enet_ptp_aux_timestamp_t &timestamp) const { return statusFromInternal(bsp_enet_get_aux_timestamp(toInternal(id_), &timestamp)); }
    Status auxSnapshotStatus(bsp_enet_ptp_aux_status_t &status) const { return statusFromInternal(bsp_enet_get_aux_snapshot_status(toInternal(id_), &status)); }

private:
    static constexpr bsp_enet_port_t toInternal(EthId id)
    {
        switch (id) {
        case EthId::Port0:
            return BSP_ENET_PORT0;
        }
        return BSP_ENET_PORT0;
    }

    EthId id_;
};
