// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_eui.h"

class Eui {
public:
    explicit constexpr Eui(EuiId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_eui_init(toInternal(id_))); }
    Status enable(bool enabled) const { return statusFromInternal(bsp_eui_enable(toInternal(id_), stateFromBool(enabled))); }
    Status irqStatus(std::uint32_t &status) const { return statusFromInternal(bsp_eui_get_irq_status(toInternal(id_), &status)); }

private:
    static constexpr bsp_eui_instance_t toInternal(EuiId id)
    {
        switch (id) {
        case EuiId::Main:
            return BSP_EUI_MAIN;
        }
        return BSP_EUI_MAIN;
    }

    EuiId id_;
};
