// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_gpio.h"

class Gpio {
public:
    explicit constexpr Gpio(GpioId id) : id_(id) {}
    Status init(GpioMode mode = GpioMode::Output, GpioPull pull = GpioPull::None, GpioOutputType type = GpioOutputType::PushPull) const { return statusFromInternal(bsp_gpio_init(toInternal(id_), gpioModeToInternal(mode), gpioPullToInternal(pull), gpioOutputTypeToInternal(type))); }
    Status initInput(GpioPull pull = GpioPull::None) const { return init(GpioMode::Input, pull, GpioOutputType::PushPull); }
    Status initOutput(GpioOutputType type = GpioOutputType::PushPull, GpioPull pull = GpioPull::None) const { return init(GpioMode::Output, pull, type); }
    Status initInterruptRising(GpioPull pull = GpioPull::None) const { return init(GpioMode::InterruptRising, pull, GpioOutputType::PushPull); }
    Status initInterruptFalling(GpioPull pull = GpioPull::None) const { return init(GpioMode::InterruptFalling, pull, GpioOutputType::PushPull); }
    Status initInterruptBoth(GpioPull pull = GpioPull::None) const { return init(GpioMode::InterruptBoth, pull, GpioOutputType::PushPull); }
    Status onInterrupt(bsp_gpio_irq_callback_t callback, void *arg) const { return statusFromInternal(bsp_gpio_register_callback(toInternal(id_), callback, arg)); }
    void write(bool high) const { bsp_gpio_write(toInternal(id_), high ? BSP_LEVEL_HIGH : BSP_LEVEL_LOW); }
    bool read() const { return bsp_gpio_read(toInternal(id_)) == BSP_LEVEL_HIGH; }
    void toggle() const { bsp_gpio_toggle(toInternal(id_)); }

private:
    static constexpr bsp_gpio_pin_t toInternal(GpioId id)
    {
        switch (id) {
        case GpioId::Led:
            return BSP_GPIO_LED;
        case GpioId::Led2:
            return BSP_GPIO_LED2;
        case GpioId::Led3:
            return BSP_GPIO_LED3;
        case GpioId::Led4:
            return BSP_GPIO_LED4;
        case GpioId::Key:
            return BSP_GPIO_KEY;
        case GpioId::LcdCs:
            return BSP_GPIO_LCD_CS;
        case GpioId::LcdDc:
            return BSP_GPIO_LCD_DC;
        case GpioId::LcdReset:
            return BSP_GPIO_LCD_RST;
        case GpioId::LcdBacklight:
            return BSP_GPIO_LCD_BL;
        }
        return BSP_GPIO_LED;
    }

    GpioId id_;
};
