// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_i2c.h"

class I2c {
public:
    explicit constexpr I2c(I2cId id) : id_(id) {}
    Status init(std::uint32_t frequencyHz = 0U, bool tenBitAddressing = false, TransferMode transferMode = TransferMode::Auto, std::uint8_t irqPriority = DefaultIrqPriority) const { return statusFromInternal(bsp_i2c_init(toInternal(id_), frequencyHz, stateFromBool(tenBitAddressing), transferModeToInternal(transferMode), irqPriority)); }
    Status write(std::uint16_t deviceAddress, ByteView data) const { return statusFromInternal(bsp_i2c_write(toInternal(id_), deviceAddress, data.data(), static_cast<std::uint32_t>(data.size()))); }
    Status read(std::uint16_t deviceAddress, ByteSpan data) const { return statusFromInternal(bsp_i2c_read(toInternal(id_), deviceAddress, data.data(), static_cast<std::uint32_t>(data.size()))); }
    Status writeRegister(std::uint16_t deviceAddress, std::uint8_t reg, std::uint8_t value) const { const std::array<std::uint8_t, 2> payload = {reg, value}; return write(deviceAddress, ByteView(payload.data(), payload.size())); }
    Status writeAsync(std::uint16_t deviceAddress, ByteView data) const { return statusFromInternal(bsp_i2c_write_async(toInternal(id_), deviceAddress, data.data(), static_cast<std::uint32_t>(data.size()))); }
    Status readAsync(std::uint16_t deviceAddress, ByteSpan data) const { return statusFromInternal(bsp_i2c_read_async(toInternal(id_), deviceAddress, data.data(), static_cast<std::uint32_t>(data.size()))); }
    Status onEvent(I2cEventCallback callback, void *arg) const { return statusFromInternal(bsp_i2c_register_event_callback(toInternal(id_), callback, arg)); }
    Status readRegister(std::uint16_t deviceAddress, std::uint8_t reg, ByteSpan data) const
    {
        const auto status = write(deviceAddress, ByteView(&reg, 1U));
        if (status != Status::Ok) {
            return status;
        }
        return read(deviceAddress, data);
    }

private:
    static constexpr bsp_i2c_instance_t toInternal(I2cId id)
    {
        switch (id) {
        case I2cId::Main:
            return BSP_I2C_MAIN;
        }
        return BSP_I2C_MAIN;
    }

    I2cId id_;
};
