// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_i2s.h"

class I2s {
public:
    explicit constexpr I2s(I2sId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_i2s_init(toInternal(id_))); }
    Status write(ByteView data) const { return statusFromInternal(bsp_i2s_write(toInternal(id_), data.data(), static_cast<std::uint32_t>(data.size()))); }
    Status read(ByteSpan data) const { return statusFromInternal(bsp_i2s_read(toInternal(id_), data.data(), static_cast<std::uint32_t>(data.size()))); }

private:
    static constexpr bsp_i2s_instance_t toInternal(I2sId id)
    {
        switch (id) {
        case I2sId::None:
            return BSP_I2S_NONE;
        }
        return BSP_I2S_NONE;
    }

    I2sId id_;
};
