// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_lobs.h"

class Lobs {
public:
    explicit constexpr Lobs(LobsId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_lobs_init(toInternal(id_))); }
    Status enable(bool enabled) const { return statusFromInternal(bsp_lobs_enable(toInternal(id_), stateFromBool(enabled))); }

private:
    static constexpr bsp_lobs_instance_t toInternal(LobsId id)
    {
        switch (id) {
        case LobsId::Main:
            return BSP_LOBS_MAIN;
        }
        return BSP_LOBS_MAIN;
    }

    LobsId id_;
};
