// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_mbx.h"

class Mailbox {
public:
    explicit constexpr Mailbox(MailboxId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_mbx_init(toInternal(id_))); }
    Status send(std::uint32_t data) const { return statusFromInternal(bsp_mbx_try_send(toInternal(id_), data)); }
    Status receive(std::uint32_t &data) const { return statusFromInternal(bsp_mbx_try_receive(toInternal(id_), &data)); }

private:
    static constexpr bsp_mbx_instance_t toInternal(MailboxId id)
    {
        switch (id) {
        case MailboxId::Local:
            return BSP_MBX_LOCAL;
        case MailboxId::Remote:
            return BSP_MBX_REMOTE;
        }
        return BSP_MBX_LOCAL;
    }

    MailboxId id_;
};
