// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_mchtmr.h"

class Mchtmr {
public:
    explicit constexpr Mchtmr(MchtmrId id) : id_(id) {}
    Status count(std::uint64_t &ticks) const { return statusFromInternal(bsp_mchtmr_get_count(toInternal(id_), &ticks)); }
    Status delay(std::uint64_t ticks) const { return statusFromInternal(bsp_mchtmr_delay_ticks(toInternal(id_), ticks)); }

private:
    static constexpr bsp_mchtmr_instance_t toInternal(MchtmrId id)
    {
        switch (id) {
        case MchtmrId::Main:
            return BSP_MCHTMR_MAIN;
        }
        return BSP_MCHTMR_MAIN;
    }

    MchtmrId id_;
};
