// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_mmc.h"

class Mmc {
public:
    explicit constexpr Mmc(MmcId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_mmc_init(toInternal(id_))); }
    Status readBlocks(std::uint32_t block, ByteSpan data, std::uint32_t blockCount) const { return statusFromInternal(bsp_mmc_read_blocks(toInternal(id_), block, data.data(), blockCount)); }
    Status writeBlocks(std::uint32_t block, ByteView data, std::uint32_t blockCount) const { return statusFromInternal(bsp_mmc_write_blocks(toInternal(id_), block, data.data(), blockCount)); }

private:
    static constexpr bsp_mmc_instance_t toInternal(MmcId id)
    {
        switch (id) {
        case MmcId::None:
            return BSP_MMC_NONE;
        }
        return BSP_MMC_NONE;
    }

    MmcId id_;
};
