// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_ospi.h"

class Ospi {
public:
    explicit constexpr Ospi(OspiId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_ospi_init(toInternal(id_))); }
    Status read(std::uint32_t address, ByteSpan data) const { return statusFromInternal(bsp_ospi_read(toInternal(id_), address, data.data(), static_cast<std::uint32_t>(data.size()))); }
    Status write(std::uint32_t address, ByteView data) const { return statusFromInternal(bsp_ospi_write(toInternal(id_), address, data.data(), static_cast<std::uint32_t>(data.size()))); }

private:
    static constexpr bsp_ospi_instance_t toInternal(OspiId id)
    {
        switch (id) {
        case OspiId::None:
            return BSP_OSPI_NONE;
        }
        return BSP_OSPI_NONE;
    }

    OspiId id_;
};
