// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_owr.h"

class Owr {
public:
    explicit constexpr Owr(OwrId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_owr_init(toInternal(id_))); }
    Status presence(std::uint32_t &status) const { return statusFromInternal(bsp_owr_get_presence(toInternal(id_), &status)); }

private:
    static constexpr bsp_owr_instance_t toInternal(OwrId id)
    {
        switch (id) {
        case OwrId::Main:
            return BSP_OWR_MAIN;
        }
        return BSP_OWR_MAIN;
    }

    OwrId id_;
};
