// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_pdgo.h"

class Pdgo {
public:
    explicit constexpr Pdgo(PdgoId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_pdgo_init(toInternal(id_))); }
    Status wakeup(std::uint32_t &status) const { return statusFromInternal(bsp_pdgo_get_wakeup_status(toInternal(id_), &status)); }
    Status write(std::uint32_t index, std::uint32_t value) const { return statusFromInternal(bsp_pdgo_write_gpr(toInternal(id_), index, value)); }
    Status read(std::uint32_t index, std::uint32_t &value) const { return statusFromInternal(bsp_pdgo_read_gpr(toInternal(id_), index, &value)); }

private:
    static constexpr bsp_pdgo_instance_t toInternal(PdgoId id)
    {
        switch (id) {
        case PdgoId::Main:
            return BSP_PDGO_MAIN;
        }
        return BSP_PDGO_MAIN;
    }

    PdgoId id_;
};
