// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_plb.h"

class Plb {
public:
    explicit constexpr Plb(PlbId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_plb_init(toInternal(id_))); }
    Status counter(std::uint8_t channel, std::uint32_t &value) const { return statusFromInternal(bsp_plb_get_counter(toInternal(id_), channel, &value)); }

private:
    static constexpr bsp_plb_instance_t toInternal(PlbId id)
    {
        switch (id) {
        case PlbId::Main:
            return BSP_PLB_MAIN;
        }
        return BSP_PLB_MAIN;
    }

    PlbId id_;
};
