// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_plic.h"

class Plic {
public:
    explicit constexpr Plic(PlicId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_plic_init(toInternal(id_))); }
    Status configure(std::uint32_t irq, std::uint32_t priority, bool enable) const { return statusFromInternal(bsp_plic_config_irq(toInternal(id_), irq, priority, stateFromBool(enable))); }

private:
    static constexpr bsp_plic_instance_t toInternal(PlicId id)
    {
        switch (id) {
        case PlicId::Main:
            return BSP_PLIC_MAIN;
        }
        return BSP_PLIC_MAIN;
    }

    PlicId id_;
};
