// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_pllctlv2.h"

class PllCtl {
public:
    explicit constexpr PllCtl(PllCtlId id) : id_(id) {}
    Status frequency(std::uint8_t pllIndex, std::uint32_t &frequencyHz) const { return statusFromInternal(bsp_pllctlv2_get_pll_freq(toInternal(id_), pllIndex, &frequencyHz)); }
    Status stable(std::uint8_t pllIndex, bool &isStable) const { return statusFromInternal(bsp_pllctlv2_is_pll_stable(toInternal(id_), pllIndex, &isStable)); }

private:
    static constexpr bsp_pllctlv2_instance_t toInternal(PllCtlId id)
    {
        switch (id) {
        case PllCtlId::Main:
            return BSP_PLLCTLV2_MAIN;
        }
        return BSP_PLLCTLV2_MAIN;
    }

    PllCtlId id_;
};
