// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_ppi.h"

class Ppi {
public:
    explicit constexpr Ppi(PpiId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_ppi_init(toInternal(id_))); }
    Status timeout(std::uint16_t count, bool enable) const { return statusFromInternal(bsp_ppi_config_timeout(toInternal(id_), count, stateFromBool(enable))); }

private:
    static constexpr bsp_ppi_instance_t toInternal(PpiId id)
    {
        switch (id) {
        case PpiId::Main:
            return BSP_PPI_MAIN;
        }
        return BSP_PPI_MAIN;
    }

    PpiId id_;
};
