// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_ppor.h"

class Ppor {
public:
    explicit constexpr Ppor(PporId id) : id_(id) {}
    Status flags(std::uint32_t &value) const { return statusFromInternal(bsp_ppor_get_reset_flags(toInternal(id_), &value)); }
    Status clear(std::uint32_t mask) const { return statusFromInternal(bsp_ppor_clear_reset_flags(toInternal(id_), mask)); }

private:
    static constexpr bsp_ppor_instance_t toInternal(PporId id)
    {
        switch (id) {
        case PporId::Main:
            return BSP_PPOR_MAIN;
        }
        return BSP_PPOR_MAIN;
    }

    PporId id_;
};
