// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_ptpc.h"

class Ptpc {
public:
    explicit constexpr Ptpc(PtpcId id) : id_(id) {}
    Status init(std::uint8_t timerIndex) const { return statusFromInternal(bsp_ptpc_init(toInternal(id_), timerIndex)); }
    Status time(std::uint8_t timerIndex, std::uint32_t &second, std::uint32_t &nanosecond) const { return statusFromInternal(bsp_ptpc_get_time(toInternal(id_), timerIndex, &second, &nanosecond)); }

private:
    static constexpr bsp_ptpc_instance_t toInternal(PtpcId id)
    {
        switch (id) {
        case PtpcId::Main:
            return BSP_PTPC_MAIN;
        }
        return BSP_PTPC_MAIN;
    }

    PtpcId id_;
};
