// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_pwm.h"

enum class PwmAlign : std::uint8_t {
    Edge = 0,
    Center = 1,
};

class Pwm {
public:
    explicit constexpr Pwm(PwmId id) : id_(id) {}
    Status init(std::uint32_t frequencyHz, PwmAlign align) const { return statusFromInternal(bsp_pwm_init(toInternal(id_), frequencyHz, toInternal(align))); }
    Status frequency(std::uint32_t &frequencyHz) const { return statusFromInternal(bsp_pwm_get_frequency(toInternal(id_), &frequencyHz)); }
    Status duty(std::uint8_t channel, float percent) const { return statusFromInternal(bsp_pwm_set_duty(toInternal(id_), channel, percent)); }
    Status compareTicks(std::uint8_t compareIndex, std::uint32_t ticks) const { return statusFromInternal(bsp_pwm_set_compare_ticks(toInternal(id_), compareIndex, ticks)); }
    Status output(std::uint8_t channel, bool enable) const { return statusFromInternal(bsp_pwm_enable_output(toInternal(id_), channel, stateFromBool(enable))); }
    Status pair(std::uint8_t channel, bool enable) const { return statusFromInternal(bsp_pwm_enable_pair(toInternal(id_), channel, stateFromBool(enable))); }
    Status deadtime(std::uint8_t channel, std::uint16_t ticks) const { return statusFromInternal(bsp_pwm_set_deadtime(toInternal(id_), channel, ticks)); }
    Status complementary(std::uint8_t channel, bool enable, std::uint16_t deadtimeTicks = 0U) const
    {
        const auto deadtimeStatus = deadtime(channel, deadtimeTicks);
        if ((deadtimeStatus != Status::Ok) && (deadtimeStatus != Status::Unsupported)) {
            return deadtimeStatus;
        }
        return pair(channel, enable);
    }
    Status force(std::uint8_t channel, Level level) const { return statusFromInternal(bsp_pwm_force_output(toInternal(id_), channel, levelToInternal(level))); }
    Status start() const { return statusFromInternal(bsp_pwm_start(toInternal(id_))); }
    Status stop() const { return statusFromInternal(bsp_pwm_stop(toInternal(id_))); }
    Status onEvent(PwmEventCallback callback, void *arg) const { return statusFromInternal(bsp_pwm_register_event_callback(toInternal(id_), callback, arg)); }

private:
    static constexpr bsp_pwm_instance_t toInternal(PwmId id)
    {
        switch (id) {
        case PwmId::Main:
            return BSP_PWM_MAIN;
        case PwmId::Timer:
            return BSP_PWM_TIMER;
        }
        return BSP_PWM_MAIN;
    }

    static constexpr bsp_pwm_align_t toInternal(PwmAlign align)
    {
        return (align == PwmAlign::Center) ? BSP_PWM_ALIGN_CENTER : BSP_PWM_ALIGN_EDGE;
    }

    PwmId id_;
};
