// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_qspi.h"

class Qspi {
public:
    explicit constexpr Qspi(QspiId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_qspi_init(toInternal(id_))); }
    Status read(std::uint32_t address, ByteSpan data) const { return statusFromInternal(bsp_qspi_read(toInternal(id_), address, data.data(), static_cast<std::uint32_t>(data.size()))); }
    Status write(std::uint32_t address, ByteView data) const { return statusFromInternal(bsp_qspi_write(toInternal(id_), address, data.data(), static_cast<std::uint32_t>(data.size()))); }

private:
    static constexpr bsp_qspi_instance_t toInternal(QspiId id)
    {
        switch (id) {
        case QspiId::None:
            return BSP_QSPI_NONE;
        }
        return BSP_QSPI_NONE;
    }

    QspiId id_;
};
