// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_rng.h"

class Rng {
public:
    explicit constexpr Rng(RngId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_rng_init(toInternal(id_))); }
    Status read(std::uint32_t &value) const { return statusFromInternal(bsp_rng_get_u32(toInternal(id_), &value)); }

private:
    static constexpr bsp_rng_instance_t toInternal(RngId id)
    {
        switch (id) {
        case RngId::None:
            return BSP_RNG_NONE;
        }
        return BSP_RNG_NONE;
    }

    RngId id_;
};
