// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_rtc.h"

class Rtc {
public:
    explicit constexpr Rtc(RtcId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_rtc_init(toInternal(id_))); }
    Status now(std::uint32_t &unixSeconds) const { return statusFromInternal(bsp_rtc_get_unix_time(toInternal(id_), &unixSeconds)); }

private:
    static constexpr bsp_rtc_instance_t toInternal(RtcId id)
    {
        switch (id) {
        case RtcId::None:
            return BSP_RTC_NONE;
        }
        return BSP_RTC_NONE;
    }

    RtcId id_;
};
