// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_sai.h"

class Sai {
public:
    explicit constexpr Sai(SaiId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_sai_init(toInternal(id_))); }
    Status write(ByteView data) const { return statusFromInternal(bsp_sai_write(toInternal(id_), data.data(), static_cast<std::uint32_t>(data.size()))); }
    Status read(ByteSpan data) const { return statusFromInternal(bsp_sai_read(toInternal(id_), data.data(), static_cast<std::uint32_t>(data.size()))); }

private:
    static constexpr bsp_sai_instance_t toInternal(SaiId id)
    {
        switch (id) {
        case SaiId::None:
            return BSP_SAI_NONE;
        }
        return BSP_SAI_NONE;
    }

    SaiId id_;
};
