// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_sd.h"

class Sd {
public:
    explicit constexpr Sd(SdId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_sd_init(toInternal(id_))); }
    Status readBlocks(std::uint32_t block, ByteSpan data, std::uint32_t blockCount) const { return statusFromInternal(bsp_sd_read_blocks(toInternal(id_), block, data.data(), blockCount)); }
    Status writeBlocks(std::uint32_t block, ByteView data, std::uint32_t blockCount) const { return statusFromInternal(bsp_sd_write_blocks(toInternal(id_), block, data.data(), blockCount)); }

private:
    static constexpr bsp_sd_instance_t toInternal(SdId id)
    {
        switch (id) {
        case SdId::None:
            return BSP_SD_NONE;
        }
        return BSP_SD_NONE;
    }

    SdId id_;
};
