// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_sdio.h"

class Sdio {
public:
    explicit constexpr Sdio(SdioId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_sdio_init(toInternal(id_))); }
    Status readBlocks(std::uint32_t block, ByteSpan data, std::uint32_t blockCount) const { return statusFromInternal(bsp_sdio_read_blocks(toInternal(id_), block, data.data(), blockCount)); }
    Status writeBlocks(std::uint32_t block, ByteView data, std::uint32_t blockCount) const { return statusFromInternal(bsp_sdio_write_blocks(toInternal(id_), block, data.data(), blockCount)); }

private:
    static constexpr bsp_sdio_instance_t toInternal(SdioId id)
    {
        switch (id) {
        case SdioId::None:
            return BSP_SDIO_NONE;
        }
        return BSP_SDIO_NONE;
    }

    SdioId id_;
};
