// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_sdm.h"

class Sdm {
public:
    explicit constexpr Sdm(SdmId id) : id_(id) {}
    Status init(std::uint8_t channel = 0U) const { return statusFromInternal(bsp_sdm_init(toInternal(id_), channel)); }
    Status status(std::uint32_t &value) const { return statusFromInternal(bsp_sdm_get_status(toInternal(id_), &value)); }

private:
    static constexpr bsp_sdm_instance_t toInternal(SdmId id)
    {
        switch (id) {
        case SdmId::Main:
            return BSP_SDM_MAIN;
        }
        return BSP_SDM_MAIN;
    }

    SdmId id_;
};
