// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_spi.h"

class Spi {
public:
    explicit constexpr Spi(SpiId id) : id_(id) {}
    Status init(SpiMode mode = SpiMode::Mode3, std::uint32_t frequencyHz = 0U, SpiBitOrder bitOrder = SpiBitOrder::MsbFirst, TransferMode transferMode = TransferMode::Auto, std::uint8_t irqPriority = DefaultIrqPriority) const { return statusFromInternal(bsp_spi_init(toInternal(id_), spiModeToInternal(mode), frequencyHz, spiBitOrderToInternal(bitOrder), transferModeToInternal(transferMode), irqPriority)); }
    Status transfer(ByteView tx, ByteSpan rx) const
    {
        if (tx.size() != rx.size()) {
            return Status::Param;
        }
        return statusFromInternal(bsp_spi_transfer(toInternal(id_), tx.data(), rx.data(), static_cast<std::uint32_t>(tx.size())));
    }
    Status write(ByteView data) const { return statusFromInternal(bsp_spi_transfer(toInternal(id_), data.data(), nullptr, static_cast<std::uint32_t>(data.size()))); }
    Status transferAsync(ByteView tx, ByteSpan rx) const
    {
        if (tx.size() != rx.size()) {
            return Status::Param;
        }
        return statusFromInternal(bsp_spi_transfer_async(toInternal(id_), tx.data(), rx.data(), static_cast<std::uint32_t>(tx.size())));
    }
    Status onEvent(SpiEventCallback callback, void *arg) const { return statusFromInternal(bsp_spi_register_event_callback(toInternal(id_), callback, arg)); }

private:
    static constexpr bsp_spi_instance_t toInternal(SpiId id)
    {
        switch (id) {
        case SpiId::Main:
            return BSP_SPI_MAIN;
        }
        return BSP_SPI_MAIN;
    }

    SpiId id_;
};
