// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_synt.h"

class Synt {
public:
    explicit constexpr Synt(SyntId id) : id_(id) {}
    Status init(std::uint32_t reloadCount) const { return statusFromInternal(bsp_synt_init(toInternal(id_), reloadCount)); }
    Status start() const { return statusFromInternal(bsp_synt_start(toInternal(id_))); }
    Status stop() const { return statusFromInternal(bsp_synt_stop(toInternal(id_))); }
    Status read(std::uint32_t &count) const { return statusFromInternal(bsp_synt_get_count(toInternal(id_), &count)); }

private:
    static constexpr bsp_synt_instance_t toInternal(SyntId id)
    {
        switch (id) {
        case SyntId::Main:
            return BSP_SYNT_MAIN;
        }
        return BSP_SYNT_MAIN;
    }

    SyntId id_;
};
