// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_gptmr.h"

enum class TimerMode : std::uint8_t {
    Periodic = 0,
    Oneshot = 1,
    CaptureRising = 2,
    Compare = 3,
};

class Timer {
public:
    explicit constexpr Timer(TimerId id) : id_(id) {}
    Status init(TimerMode mode, std::uint32_t ticks) const { return statusFromInternal(bsp_gptmr_init(toInternal(id_), toInternal(mode), ticks)); }
    Status start() const { return statusFromInternal(bsp_gptmr_start(toInternal(id_))); }
    Status stop() const { return statusFromInternal(bsp_gptmr_stop(toInternal(id_))); }
    Status read(std::uint32_t &value) const { return statusFromInternal(bsp_gptmr_get_counter(toInternal(id_), &value)); }
    Status capture(std::uint32_t &value) const { return statusFromInternal(bsp_gptmr_get_capture(toInternal(id_), &value)); }
    Status compare(std::uint32_t ticks) const { return statusFromInternal(bsp_gptmr_set_compare(toInternal(id_), ticks)); }
    Status onEvent(TimerEventCallback callback, void *arg) const { return statusFromInternal(bsp_gptmr_register_event_callback(toInternal(id_), callback, arg)); }

private:
    static constexpr bsp_gptmr_instance_t toInternal(TimerId id)
    {
        switch (id) {
        case TimerId::Main:
            return BSP_GPTMR_TIMER;
        case TimerId::Capture:
            return BSP_GPTMR_CAPTURE;
        case TimerId::Compare:
            return BSP_GPTMR_COMPARE;
        }
        return BSP_GPTMR_TIMER;
    }

    static constexpr bsp_gptmr_mode_t toInternal(TimerMode mode)
    {
        switch (mode) {
        case TimerMode::Periodic:
            return BSP_GPTMR_MODE_PERIODIC;
        case TimerMode::Oneshot:
            return BSP_GPTMR_MODE_ONESHOT;
        case TimerMode::CaptureRising:
            return BSP_GPTMR_MODE_CAPTURE_RISING;
        case TimerMode::Compare:
            return BSP_GPTMR_MODE_COMPARE;
        }
        return BSP_GPTMR_MODE_PERIODIC;
    }

    TimerId id_;
};
