// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_trgm.h"

class Trgm {
public:
    explicit constexpr Trgm(TrgmId id) : id_(id) {}
    Status routeOutput(const TrgmOutputRoute &route) const { return statusFromInternal(bsp_trgm_route_output(toInternal(id_), &route)); }
    Status dmaRequest(std::uint8_t dmaOutput, std::uint8_t dmaSource) const { return statusFromInternal(bsp_trgm_dma_request(toInternal(id_), dmaOutput, dmaSource)); }
    Status ioOutput(std::uint32_t mask, bool enable) const { return statusFromInternal(bsp_trgm_io_output(toInternal(id_), mask, stateFromBool(enable))); }

private:
    static constexpr bsp_trgm_instance_t toInternal(TrgmId id)
    {
        switch (id) {
        case TrgmId::Main:
            return BSP_TRGM_MAIN;
        }
        return BSP_TRGM_MAIN;
    }

    TrgmId id_;
};
