// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_tsns.h"

class Tsns {
public:
    explicit constexpr Tsns(TsnsId id) : id_(id) {}
    Status init() const { return statusFromInternal(bsp_tsns_init(toInternal(id_))); }
    Status read(float &celsius) const { return statusFromInternal(bsp_tsns_read_celsius(toInternal(id_), &celsius)); }

private:
    static constexpr bsp_tsns_instance_t toInternal(TsnsId id)
    {
        switch (id) {
        case TsnsId::Main:
            return BSP_TSNS_MAIN;
        }
        return BSP_TSNS_MAIN;
    }

    TsnsId id_;
};
