// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_uart.h"

class Uart {
public:
    explicit constexpr Uart(UartId id) : id_(id) {}
    Status init(std::uint32_t baudrate = 0U, UartParity parity = UartParity::None, UartStopBits stopBits = UartStopBits::One, UartWordLength wordLength = UartWordLength::Bits8, TransferMode transferMode = TransferMode::Auto, std::uint8_t irqPriority = DefaultIrqPriority) const { return statusFromInternal(bsp_uart_init(toInternal(id_), baudrate, uartParityToInternal(parity), uartStopBitsToInternal(stopBits), uartWordLengthToInternal(wordLength), transferModeToInternal(transferMode), irqPriority)); }
    Status write(ByteView data, std::uint32_t timeoutMs = 0U) const { return statusFromInternal(bsp_uart_send(toInternal(id_), const_cast<std::uint8_t *>(data.data()), static_cast<std::uint16_t>(data.size()), timeoutMs)); }
    Status write(std::string_view text, std::uint32_t timeoutMs = 0U) const { return write(ByteView(reinterpret_cast<const std::uint8_t *>(text.data()), text.size()), timeoutMs); }
    Status writeAsync(ByteView data) const { return statusFromInternal(bsp_uart_send_async(toInternal(id_), data.data(), static_cast<std::uint16_t>(data.size()))); }
    Status writeAsync(std::string_view text) const { return writeAsync(ByteView(reinterpret_cast<const std::uint8_t *>(text.data()), text.size())); }
    Status readAsync(ByteSpan buffer) const { return statusFromInternal(bsp_uart_receive_it(toInternal(id_), buffer.data(), static_cast<std::uint16_t>(buffer.size()))); }
    Status onEvent(UartEventCallback callback, void *arg) const { return statusFromInternal(bsp_uart_register_event_callback(toInternal(id_), callback, arg)); }

private:
    static constexpr bsp_uart_instance_t toInternal(UartId id)
    {
        switch (id) {
        case UartId::Debug:
            return BSP_UART_DEBUG;
        case UartId::App:
            return BSP_UART_APP;
        }
        return BSP_UART_DEBUG;
    }

    UartId id_;
};
