// Auto-generated by tools/clight_codegen/generate_cpp_api.py. Do not edit manually.
#pragma once

#include "BoardIds.hpp"
#include "bsp/interface/bsp_ewdg.h"

class Watchdog {
public:
    explicit constexpr Watchdog(WatchdogId id) : id_(id) {}
    Status init(std::uint32_t timeoutMs) const { return statusFromInternal(bsp_ewdg_init(toInternal(id_), timeoutMs)); }
    Status refresh() const { return statusFromInternal(bsp_ewdg_refresh(toInternal(id_))); }
    Status deinit() const { return statusFromInternal(bsp_ewdg_deinit(toInternal(id_))); }

private:
    static constexpr bsp_ewdg_instance_t toInternal(WatchdogId id)
    {
        switch (id) {
        case WatchdogId::Main:
            return BSP_EWDG_MAIN;
        }
        return BSP_EWDG_MAIN;
    }

    WatchdogId id_;
};
