#ifndef BSP_CHIP_BOARD_CONFIG_H
#define BSP_CHIP_BOARD_CONFIG_H

#include "main.h"

#ifdef __cplusplus
extern "C" {
#endif

#define BSP_CHIP_STM32H723VGTX

#define BSP_GPIO_LIST(X) \
    X(BSP_GPIO_ACCEL_CS, ACC_CS_GPIO_Port, 0U, ACC_CS_Pin) \
    X(BSP_GPIO_GYRO_CS, GYRO_CS_GPIO_Port, 0U, GYRO_CS_Pin) \
    X(BSP_GPIO_ACCEL_INT, ACC_INT_GPIO_Port, 0U, ACC_INT_Pin) \
    X(BSP_GPIO_GYRO_INT, GYRO_INT_GPIO_Port, 0U, GYRO_INT_Pin)

#define BSP_TIM_FEATURE_PERIODIC   (1U << 0)
#define BSP_TIM_FEATURE_ONESHOT    (1U << 1)
#define BSP_TIM_FEATURE_CAPTURE    (1U << 2)
#define BSP_TIM_FEATURE_COMPARE    (1U << 3)
#define BSP_TIM_FEATURE_TRIGGER_OUTPUT (1U << 4)

#define BSP_TIM_LIST(X) \
    X(BSP_TIM_MAIN, TIM12, TIM8_BRK_TIM12_IRQn, BSP_TIM_FEATURE_PERIODIC | BSP_TIM_FEATURE_ONESHOT, 1U) \
    X(BSP_TIM_ADC_TRIGGER, TIM2, TIM2_IRQn, BSP_TIM_FEATURE_PERIODIC | BSP_TIM_FEATURE_ONESHOT | BSP_TIM_FEATURE_TRIGGER_OUTPUT, 1U)

#define BSP_UART_LIST(X) \
    X(BSP_UART_DEBUG, USART1, USART1_IRQn, \
      BSP_UART_FEATURE_BLOCKING_TX | BSP_UART_FEATURE_INTERRUPT_TX | BSP_UART_FEATURE_INTERRUPT_RX | \
      BSP_UART_FEATURE_DMA_TX | BSP_UART_FEATURE_DMA_RX | BSP_UART_FEATURE_RX_IDLE | \
      BSP_UART_FEATURE_CONFIGURABLE_BAUD | BSP_UART_FEATURE_PARITY_NONE | BSP_UART_FEATURE_PARITY_ODD | \
      BSP_UART_FEATURE_PARITY_EVEN | BSP_UART_FEATURE_STOP_1 | BSP_UART_FEATURE_STOP_1_5 | \
      BSP_UART_FEATURE_STOP_2 | BSP_UART_FEATURE_WORD_7 | BSP_UART_FEATURE_WORD_8)

#define BSP_SPI_LIST(X) \
    X(BSP_SPI_MAIN, SPI2, SPI2_IRQn, 0U, 1U, \
      BSP_SPI_FEATURE_MASTER | BSP_SPI_FEATURE_BLOCKING | BSP_SPI_FEATURE_INTERRUPT | \
      BSP_SPI_FEATURE_DMA_TX | BSP_SPI_FEATURE_DMA_RX | BSP_SPI_FEATURE_FULL_DUPLEX | \
      BSP_SPI_FEATURE_TX_ONLY | BSP_SPI_FEATURE_RX_ONLY | BSP_SPI_FEATURE_CONFIGURABLE_CLOCK | \
      BSP_SPI_FEATURE_MSB_FIRST | BSP_SPI_FEATURE_LSB_FIRST) \
    X(BSP_SPI_AUX, SPI6, SPI6_IRQn, 0U, 1U, \
      BSP_SPI_FEATURE_MASTER | BSP_SPI_FEATURE_BLOCKING | BSP_SPI_FEATURE_INTERRUPT | \
      BSP_SPI_FEATURE_TX_ONLY | BSP_SPI_FEATURE_CONFIGURABLE_CLOCK | \
      BSP_SPI_FEATURE_MSB_FIRST | BSP_SPI_FEATURE_LSB_FIRST)

/* Generic chip-level default mapping: I2C1 on PB8/PB9. */
#define BSP_I2C_LIST(X) \
    X(BSP_I2C_MAIN, I2C1, I2C1_EV_IRQn, 0U, 1U, \
      BSP_I2C_FEATURE_MASTER | BSP_I2C_FEATURE_BLOCKING | BSP_I2C_FEATURE_INTERRUPT | \
      BSP_I2C_FEATURE_TEN_BIT_ADDRESS | BSP_I2C_FEATURE_FIXED_TIMING | BSP_I2C_FEATURE_CONFIGURABLE_CLOCK)

/* Generic chip-level default mapping: ADC1 regular channel defaults to CH0. */
#define BSP_ADC16_LIST(X) \
    X(BSP_ADC16_MAIN, ADC1, ADC_IRQn, 0U, 0U, 0U, 1U, \
      BSP_ADC16_FEATURE_ONESHOT | BSP_ADC16_FEATURE_BLOCKING_READ | BSP_ADC16_FEATURE_INTERRUPT_READ | \
      BSP_ADC16_FEATURE_SEQUENCE | BSP_ADC16_FEATURE_SEQUENCE_HARDWARE_TRIGGER | \
      BSP_ADC16_FEATURE_PREEMPTION | BSP_ADC16_FEATURE_PREEMPTION_HARDWARE_TRIGGER | \
      BSP_ADC16_FEATURE_CONFIGURABLE_RESOLUTION | BSP_ADC16_FEATURE_CONFIGURABLE_CLOCK_DIVIDER | \
      BSP_ADC16_FEATURE_GET_CLOCK | BSP_ADC16_FEATURE_TRIGGER_ROUTE | \
      BSP_ADC16_FEATURE_SEQUENCE_DMA | BSP_ADC16_FEATURE_CONTINUOUS_DMA)

#ifdef ADC_EXTERNALTRIG_T2_TRGO
#define BSP_ADC16_STM32_TRIGGER_TIM2_TRGO        ADC_EXTERNALTRIG_T2_TRGO
#define BSP_ADC16_STM32_TRIGGER_EDGE_RISING      ADC_EXTERNALTRIGCONVEDGE_RISING
#define BSP_ADC16_STM32_TRIGGER_EDGE_FALLING     ADC_EXTERNALTRIGCONVEDGE_FALLING
#define BSP_ADC16_STM32_TRIGGER_EDGE_BOTH        ADC_EXTERNALTRIGCONVEDGE_RISINGFALLING
#endif

#ifdef ADC_EXTERNALTRIGINJEC_T1_TRGO2
#define BSP_ADC16_STM32_INJECTED_TRIGGER_TIM1_TRGO2   ADC_EXTERNALTRIGINJEC_T1_TRGO2
#define BSP_ADC16_STM32_INJECTED_TRIGGER_TIM8_TRGO2   ADC_EXTERNALTRIGINJEC_T8_TRGO2
#define BSP_ADC16_STM32_INJECTED_TRIGGER_TIM1_CC4     ADC_EXTERNALTRIGINJEC_T1_CC4
#define BSP_ADC16_STM32_INJECTED_TRIGGER_TIM8_CC4     ADC_EXTERNALTRIGINJEC_T8_CC4
#define BSP_ADC16_STM32_INJECTED_EDGE_RISING          ADC_EXTERNALTRIGINJECCONV_EDGE_RISING
#define BSP_ADC16_STM32_INJECTED_EDGE_FALLING         ADC_EXTERNALTRIGINJECCONV_EDGE_FALLING
#define BSP_ADC16_STM32_INJECTED_EDGE_BOTH            ADC_EXTERNALTRIGINJECCONV_EDGE_RISINGFALLING
#endif

#define BSP_FDCAN_LIST(X) \
    X(BSP_FDCAN_MAIN, FDCAN1, FDCAN1_IT0_IRQn, 1U, 0U, \
      BSP_FDCAN_FEATURE_CLASSIC | BSP_FDCAN_FEATURE_CAN_FD | BSP_FDCAN_FEATURE_BITRATE_SWITCH | \
      BSP_FDCAN_FEATURE_INTERNAL_LOOPBACK | BSP_FDCAN_FEATURE_TX_FIFO | BSP_FDCAN_FEATURE_RX_FIFO0 | \
      BSP_FDCAN_FEATURE_STANDARD_ID | BSP_FDCAN_FEATURE_EXTENDED_ID | BSP_FDCAN_FEATURE_REMOTE_FRAME | \
      BSP_FDCAN_FEATURE_FILTER_MASK | BSP_FDCAN_FEATURE_PROTOCOL_STATUS | BSP_FDCAN_FEATURE_ERROR_COUNT | \
      BSP_FDCAN_FEATURE_AUTO_BITRATE | BSP_FDCAN_FEATURE_RX_CALLBACK | BSP_FDCAN_FEATURE_TX_CALLBACK | \
      BSP_FDCAN_FEATURE_GLOBAL_FILTER | BSP_FDCAN_FEATURE_TX_EVENT_FIFO | BSP_FDCAN_FEATURE_TIMESTAMP) \
    X(BSP_FDCAN_AUX, FDCAN2, FDCAN2_IT0_IRQn, 1U, 128U, \
      BSP_FDCAN_FEATURE_CLASSIC | BSP_FDCAN_FEATURE_CAN_FD | BSP_FDCAN_FEATURE_BITRATE_SWITCH | \
      BSP_FDCAN_FEATURE_INTERNAL_LOOPBACK | BSP_FDCAN_FEATURE_TX_FIFO | BSP_FDCAN_FEATURE_RX_FIFO0 | \
      BSP_FDCAN_FEATURE_STANDARD_ID | BSP_FDCAN_FEATURE_EXTENDED_ID | BSP_FDCAN_FEATURE_REMOTE_FRAME | \
      BSP_FDCAN_FEATURE_FILTER_MASK | BSP_FDCAN_FEATURE_PROTOCOL_STATUS | BSP_FDCAN_FEATURE_ERROR_COUNT | \
      BSP_FDCAN_FEATURE_AUTO_BITRATE | BSP_FDCAN_FEATURE_RX_CALLBACK | BSP_FDCAN_FEATURE_TX_CALLBACK | \
      BSP_FDCAN_FEATURE_GLOBAL_FILTER | BSP_FDCAN_FEATURE_TX_EVENT_FIFO | BSP_FDCAN_FEATURE_TIMESTAMP)

/*
 * Public Pwm is a capability mapping. The BSP port decides whether each
 * instance is implemented by TIM, HRTIM, GPTMR, PWMV2, PTW, etc.
 */
#define BSP_PWM_LIST(X) \
    X(BSP_PWM_MAIN, BSP_PWM_BACKEND_STM32_TIM, TIM1, TIM1_UP_IRQn, 0U, 1U, 1U, \
      BSP_PWM_FEATURE_EDGE_ALIGNED | BSP_PWM_FEATURE_CENTER_ALIGNED | BSP_PWM_FEATURE_COMPLEMENTARY | BSP_PWM_FEATURE_DEADTIME | BSP_PWM_FEATURE_TRIGGER_COMPARE) \
    X(BSP_PWM_BUZZER, BSP_PWM_BACKEND_STM32_TIM, TIM12, TIM8_BRK_TIM12_IRQn, 0U, 2U, 1U, \
      BSP_PWM_FEATURE_EDGE_ALIGNED)

#define BSP_PWMV2_LIST(X) \
    X(BSP_PWMV2_MAIN, TIM1, TIM1_UP_IRQn, 0U, 1U)

/* Encoder is exported through the shared QEIV2-style API; current board has no TIM3 pinmux. */
#define BSP_QEIV2_LIST(X) \
    X(BSP_QEIV2_MAIN, TIM3, TIM3_IRQn, 0U, 2048U, 0U)

#define BSP_ENCODER_LIST(X) \
    X(BSP_ENCODER_MAIN, TIM3, TIM3_IRQn, 0U, 2048U)

#define BSP_CRC_LIST(X) \
    X(BSP_CRC_MAIN, CRC, 0U, BSP_CRC_FEATURE_CRC32)

#define BSP_EWDG_LIST(X) \
    X(BSP_EWDG_MAIN, IWDG1, 0U, BSP_EWDG_FEATURE_INIT | BSP_EWDG_FEATURE_REFRESH)

#define BSP_WWDG_LIST(X) \
    X(BSP_WWDG_MAIN, WWDG1, WWDG_IRQn, BSP_WWDG_FEATURE_INIT | BSP_WWDG_FEATURE_REFRESH)

#define BSP_DMAV2_LIST(X) \
    X(BSP_DMAV2_MAIN, DMA1_Stream3, DMA1_Stream3_IRQn, 0U)

#define BSP_RNG_LIST(X) \
    X(BSP_RNG_MAIN, RNG, BSP_RNG_FEATURE_U32)

#define BSP_RTC_LIST(X) \
    X(BSP_RTC_MAIN, RTC, BSP_RTC_FEATURE_UNIX_TIME)

#define BSP_CORDIC_LIST(X) \
    X(BSP_CORDIC_MAIN, CORDIC)

#define BSP_FMAC_LIST(X) \
    X(BSP_FMAC_MAIN, FMAC)

#define BSP_DMA2D_LIST(X) \
    X(BSP_DMA2D_MAIN, DMA2D)

#define BSP_MDMA_LIST(X) \
    X(BSP_MDMA_MAIN, MDMA)

#define BSP_DAC_LIST(X) \
    X(BSP_DAC_MAIN, DAC1, 0U, 0U)

#define BSP_COMP_LIST(X) \
    X(BSP_COMP1, COMP1, 0U) \
    X(BSP_COMP2, COMP2, 0U)

#define BSP_DCMI_LIST(X) \
    X(BSP_DCMI, DCMI, 0U)

#define BSP_DFSDM_LIST(X) \
    X(BSP_DFSDM1, DFSDM1_Filter0, 0U)

#define BSP_JPEG_LIST(X) \
    X(BSP_JPEG_MAIN, 0U, 0U)

#define BSP_LTDC_LIST(X) \
    X(BSP_LTDC, LTDC, 0U)

#define BSP_MMC_LIST(X) \
    X(BSP_MMC1, SDMMC1, 0U, 0U) \
    X(BSP_MMC2, SDMMC2, 0U, 0U)

#define BSP_OPAMP_LIST(X) \
    X(BSP_OPAMP1, OPAMP1, 0U) \
    X(BSP_OPAMP2, OPAMP2, 0U)

#define BSP_OSPI_LIST(X) \
    X(BSP_OSPI1, OCTOSPI1, 0U, 0U) \
    X(BSP_OSPI2, OCTOSPI2, 0U, 0U)

#define BSP_QSPI_LIST(X) \
    X(BSP_QSPI1, 0U, 0U, 0U)

#define BSP_PCD_LIST(X) \
    X(BSP_PCD_HS, USB_OTG_HS, 0U)

#define BSP_HCD_LIST(X) \
    X(BSP_HCD_HS, USB_OTG_HS, 0U)

#define BSP_PSSI_LIST(X) \
    X(BSP_PSSI, PSSI, 0U)

#define BSP_SAI_LIST(X) \
    X(BSP_SAI1, SAI1, 0U, 0U) \
    X(BSP_SAI4, SAI4, 0U, 0U)

#define BSP_SD_LIST(X) \
    X(BSP_SDMMC1, SDMMC1, 0U, 0U) \
    X(BSP_SDMMC2, SDMMC2, 0U, 0U)

#define BSP_SDIO_LIST(X) \
    X(BSP_SDIO1, SDMMC1, 0U, 0U) \
    X(BSP_SDIO2, SDMMC2, 0U, 0U)

#define BSP_I2S_LIST(X) \
    X(BSP_I2S_MAIN, 0U, 0U, 0U)

#define BSP_SMARTCARD_LIST(X) \
    X(BSP_SMARTCARD_USART1, USART1, 0U) \
    X(BSP_SMARTCARD_USART2, USART2, 0U) \
    X(BSP_SMARTCARD_USART3, USART3, 0U) \
    X(BSP_SMARTCARD_USART6, USART6, 0U) \
    X(BSP_SMARTCARD_USART10, USART10, 0U)

#define BSP_SMBUS_LIST(X) \
    X(BSP_SMBUS_I2C1, I2C1, 0U) \
    X(BSP_SMBUS_I2C2, I2C2, 0U) \
    X(BSP_SMBUS_I2C3, I2C3, 0U) \
    X(BSP_SMBUS_I2C4, I2C4, 0U) \
    X(BSP_SMBUS_I2C5, I2C5, 0U)

#define BSP_USART_LIST(X) \
    X(BSP_USART1, USART1, 0U) \
    X(BSP_USART2, USART2, 0U) \
    X(BSP_USART3, USART3, 0U) \
    X(BSP_USART6, USART6, 0U) \
    X(BSP_USART10, USART10, 1U)

#define BSP_DMA_LIST(X) \
    X(BSP_DMA_SPI2_RX, DMA1_Stream0, DMA1_Stream0_IRQn) \
    X(BSP_DMA_SPI2_TX, DMA1_Stream1, DMA1_Stream1_IRQn) \
    X(BSP_DMA_MEM2MEM, DMA1_Stream3, DMA1_Stream3_IRQn)

#define BSP_UART_DEFAULT_BAUDRATE     (115200U)
#define BSP_SPI_MAIN_CLOCK_HZ         (10000000U)
#define BSP_SPI_DISPLAY_CLOCK_HZ      (12000000U)
#define BSP_I2C_MAIN_TIMING           (0x10C0ECFFU)
#define BSP_TIM_MAIN_DEFAULT_PRESCALER (549U)

#ifdef __cplusplus
}
#endif

#endif /* BSP_CHIP_BOARD_CONFIG_H */
